<?php $url = $this->isEditMode() ? Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/pYsVAQ') :
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/N4sVAQ');
?>
<div id="block_notice_buy_listing_general_search" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In this Section you can specify the source from which the values for Item Rakuten.com SKU will be taken in case you have those for your Items. <br/><br/>
    These Settings will be used during the List process. <br/>
    For example if you have Rakuten.com SKU Attribute with valid value in your Item, M2E Pro will perform Search on Rakuten.com according to the data provided in this Attribute <br/>
    and, if the match is found, link the Magento Product to Rakuten.com Item.
    These Setting will also be used during automatic Rakuten.com SKU Search. <br/>
    In this case the parameters are used according to the following logic:

    <ul class="list">
        <li>the Product is searched by specified Item Rakuten.com SKU. (if specified)</li>
        <li>if no result by Rakuten.com SKU parameter, then additional Search by Magento Product Name is performed. (if enabled)</li>
    </ul>
    <br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.', $url
    ); ?>
</div>

<?php

    /** @var Ess_M2ePro_Helper_Magento_Attribute $magentoAttributeHelper */
    $magentoAttributeHelper = Mage::helper('M2ePro/Magento_Attribute');

    $attributesByInputTypes = array(
        'text' => $magentoAttributeHelper->filterByInputTypes($this->getData('general_attributes'), array('text')),
    );

?>

<script type="text/javascript">
    // Data for current tab
    // ----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Buy'); ?>,
        'Ess_M2ePro_Helper_Component_Buy'
    );

    //-----------------------------
    Event.observe(window, 'load', function() {

        BuyListingChannelSettingsHandlerObj = new CommonBuyListingChannelSettingsHandler();
        BuyListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Buy_Listing'); ?>');

        $('general_id_mode').observe('change', BuyListingChannelSettingsHandlerObj.general_id_mode_change);
        $F('general_id_mode') && $('general_id_mode').simulate('change');
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_buy_listing_channel_settings_source">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Search Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="general_id_mode_container">
                    <td class="label">
                        <label for="general_id_mode"><?php echo Mage::helper('M2ePro')->__('Rakuten.com SKU') ?>:</label>
                    </td>
                    <td class="value">
                        <input type="hidden" id="general_id_custom_attribute" name="general_id_custom_attribute" value="<?php echo $this->getData('general_id_custom_attribute');?>"/>

                        <select id="general_id_mode" name="general_id_mode" class="M2ePro-custom-attribute-can-be-created" allowed_attribute_types="text">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET ?>" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attribute">
                                <?php foreach ($attributesByInputTypes['text'] as $attribute): ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_CUSTOM_ATTRIBUTE ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($this->getData('general_id_custom_attribute') == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                                <?php endforeach ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('This Setting is the source of value for Rakuten.com will be used at the time of Automatic Search of Rakuten.com Products.'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_buy_listing_add_search_advanced">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Additional Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="search_by_magento_title_mode"><?php echo Mage::helper('M2ePro')->__('Search by Product Name'); ?>:
                    </td>
                    <td class="value">
                        <select id="search_by_magento_title_mode" name="search_by_magento_title_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE ?>" <?php if ($this->getData('search_by_magento_title_mode') == Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Disable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES ?>" <?php if ($this->getData('search_by_magento_title_mode') == Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Enable') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If no results are found by Identifiers, the additional Search will be performed by Magento Product Name.'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>