<div id="block_notice_ebay_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Choose whether you want to use M2E Pro in <b>Simple</b> Mode or <b>Advanced</b> Mode.
         More Settings become available if you choose Advanced Mode.<br/><br/>
         More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
         Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/OgAJAQ')
    ); ?>
</div>