<div id="block_notice_ebay_orders_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows Orders imported from eBay.<br/><br/>
        Click the line with the Order in the Table below to <b>View Order Details</b> such as the eBay Transaction Details, Buyer Information, Payment Details and the Order Log.<br/><br/>
        Filters are available to show Orders for a specifc <b>eBay Site</b> or <b>Account</b> only.
        You can also filter to <b>Show eBay Orders without Magento Orders</b>.
        This is useful to show which eBay Orders need further Action from you.<br/><br/>
        <b>Note:</b> Magento Orders, Invoices, and Shipments are created automatically according to the eBay Accounts Settings
        for your eBay Accounts found in %menu_label%.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration', 'Accounts', '[eBay Account] > Orders Tab'),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/RQAJAQ')
    ); ?>
</div>