<?php /** @var $this Ess_M2ePro_Block_Adminhtml_Listing_AutoAction_Mode_Global */ ?>

<?php
    $formData = $this->getFormData();
    $default  = $this->getDefault();
    $formData = array_merge($default, $formData);
?>

<script type="text/javascript">
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Listing'); ?>, 'Ess_M2ePro_Model_Listing');
</script>

<script type="text/javascript">

    $('auto_global_adding_mode')
        .observe('change', ListingAutoActionHandlerObj.addingModeChange)
        .simulate('change');

    $('continue_button')
        .stopObserving('click')
        .observe('click', ListingAutoActionHandlerObj.globalStepTwo);

    $('reset_button')
        .observe('click', function() {
            ListingAutoActionHandlerObj.reset(false);
        });

</script>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('M2ePro')->__('Global (all Products)'); ?></h3></td>
        </tr>
    </table>
</div>

<div id="data_container" style="padding-bottom: 10px;">

    <form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

        <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
        <input name="auto_mode" value="<?php echo Ess_M2ePro_Model_Listing::AUTO_MODE_GLOBAL ?>" type="hidden" id="auto_mode" />

        <table class="form-list">
            <tr>
                <td class="label" style="width: 200px;">
                    <label for="auto_global_adding_mode"><?php echo Mage::helper('M2ePro')->__('New Product Added to Magento') ?>:</label>
                </td>
                <td class="value">
                    <select name="auto_global_adding_mode" id="auto_global_adding_mode" style="width: 275px;">
                        <option value="<?php echo Ess_M2ePro_Model_Listing::ADDING_MODE_NONE ?>" <?php if ($formData['auto_global_adding_mode'] == Ess_M2ePro_Model_Listing::ADDING_MODE_NONE): ?>selected="selected"<?php endif; ?> ><?php echo Mage::helper('M2ePro')->__('No Action') ?></option>
                        <option value="<?php echo Ess_M2ePro_Model_Listing::ADDING_MODE_ADD ?>" <?php if ($formData['auto_global_adding_mode'] == Ess_M2ePro_Model_Listing::ADDING_MODE_ADD): ?>selected="selected"<?php endif; ?> ><?php echo Mage::helper('M2ePro')->__('Add to the Listing') ?></option>
                    </select>
                </td>
                <td class="value">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/tool-tip-icon.png'); ?>" class="tool-tip-image">
                    <span class="tool-tip-message" style="display: none;">
                        <img src="<?php echo $this->getSkinUrl('M2ePro/images/help.png'); ?>">
                        <span><?php echo Mage::helper('M2ePro')->__('Action which will be applied automatically.'); ?></span>
                    </span>
                </td>
            </tr>
        </table>

        <div style="padding-top: 20px;"></div>

        <table class="form-list">
            <tr>
                <td class="label" style="width: 200px;">
                    <label for=""><?php echo Mage::helper('M2ePro')->__('Product Deleted from Magento') ?>:</label>
                </td>
                <td class="value">
                    <select name="auto_global_deleting_mode" id="auto_global_deleting_mode" style="width: 275px;" disabled="disabled">
                        <option value="<?php echo Ess_M2ePro_Model_Listing::DELETING_MODE_STOP_REMOVE ?>"><?php echo Mage::helper('M2ePro')->__('Stop on Channel and Delete from Listing') ?></option>
                    </select>
                </td>
                <td class="value">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/tool-tip-icon.png'); ?>" class="tool-tip-image">
                    <span class="tool-tip-message" style="display: none;">
                        <img src="<?php echo $this->getSkinUrl('M2ePro/images/help.png'); ?>">
                        <span><?php echo Mage::helper('M2ePro')->__('Action which will be applied automatically.'); ?></span>
                    </span>
                </td>
            </tr>
        </table>

    </form>

</div>

<?php if ($this->hasFormData()): ?>
<div style="float: left; margin: 10px 5px 0;">
    <a id="reset_button" href="javascript: void(0);" onclick=""><?php echo Mage::helper('M2ePro')->__('Reset Automatic Action Rule'); ?></a>
</div>
<?php endif; ?>
<div style="float: right; margin: 10px 0;">
    <?php if (!$this->hasFormData()): ?>
        <a id="reset_button" href="" style="display: none;"></a>
        <a id="close_button" href="javascript: void(0);" onclick="ListingAutoActionHandlerObj.loadAutoActionHtml();"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
    <?php endif; ?>
    &nbsp;
    &nbsp;
    &nbsp;
    <?php echo $this->getChildHtml('confirm_button'); ?>
    <?php echo $this->getChildHtml('continue_button'); ?>
</div>