<script type="application/javascript">
    WalmartListingVariationProductManageHandlerObj = new WalmartListingVariationProductManageHandler();
</script>

<div id="vocabulary_attributes_pupup_template" style="display: none;">
    <div style="padding: 10px;">
        <?php echo Mage::helper('M2ePro')->__('
            You set the correspondence between <strong>Magento Variational Attribute(s)</strong> and <strong>Walmart Variant Attribute(s)</strong> that was not defined before:<br/><br/>
    
            %attributes%<br/>
    
            Do you want M2E Pro to <strong>remember</strong> these Attributes matching to use it <strong>automatically</strong> in the future?<br/><br/>
        '); ?>

        <input type="hidden" id="vocabulary_attributes_data" value="">

        <div class="clear"></div>
        <div class="left">
            <div style="margin-left: 20px">
                <input id="vocabulary_attributes_remember_checkbox" type="checkbox">
                &nbsp;&nbsp;
                <label for="vocabulary_attributes_remember_checkbox"><?php echo Mage::helper('M2ePro')->__('Remember my choice') ?></label>
            </div>
        </div>
        <div class="right">
            <?php echo $this->getChildHtml('yes_btn'); ?>
            <div style="display: inline-block;"></div>
            <?php echo $this->getChildHtml('no_btn'); ?>
        </div>
        <div class="clear"></div>
    </div>

</div>