<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Variation_Product_VocabularyOptionsPopup */

?>

<script type="application/javascript">
    WalmartListingVariationProductManageObj = new WalmartListingVariationProductManage();
</script>

<div id="vocabulary_options_pupup_template" style="display: none;">
    <div style="padding: 10px;">
        <?php echo Mage::helper('M2ePro')->__('
            You set the correspondence between <strong>Magento Variational Options(s)</strong> and <strong>Walmart Variant Option(s)</strong> that was not defined before:<br/><br/>
    
            %options%<br/>
    
            Do you want M2E Pro to <strong>remember</strong> these Options matching to use it <strong>automatically</strong> in the future?<br/><br/>
        '); ?>

        <input type="hidden" id="vocabulary_options_data" value="">

        <div class="clear"></div>
        <div class="left">
            <div style="margin-left: 20px">
                <input id="vocabulary_options_remember_checkbox" type="checkbox">
                &nbsp;&nbsp;
                <label for="vocabulary_options_remember_checkbox"><?php echo Mage::helper('M2ePro')->__('Remember my choice') ?></label>
            </div>
        </div>
        <div class="right">
            <?php echo $this->getChildHtml('yes_btn'); ?>
            <div style="display: inline-block;"></div>
            <?php echo $this->getChildHtml('no_btn'); ?>
        </div>
        <div class="clear"></div>
    </div>

</div>