<div id="block_notice_motors_view_group" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selected Groups'); ?>" style="margin-top: 15px;">
    <?php echo Mage::helper('M2ePro')->__('
        In this Block you can see the list of the saved Groups of ePID(s)/kType(s) or
        Filter(s). In case you do not want some of these Groups to be Used, they can be
        Removed by selecting the appropriate Option from the mass actions bulk.
    '); ?>
</div>

<div class="hor-scroll">

    <div id="motors">
        <?php echo $this->getChildHtml('view_group_grid'); ?>
    </div>

</div>

<div style="float: right; margin-top: 10px; margin-bottom: 8px;">
    <?php echo $this->getChildHtml('motor_close_btn'); ?>
</div>