<div id="block_notice_motors_view_item" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selected Items'); ?>" style="margin-top: 15px;">
    <?php echo Mage::helper('M2ePro')->__('
        In this Block you can see the list of the selected ePID(s)/kType(s).
        In case you do not need some of them, you can Choose the appropriate
        Option from the mass actions bulk to Remove the ePID(s)/kType(s).
    '); ?>
</div>

<div class="hor-scroll">

    <div id="motors">
        <?php echo $this->getChildHtml('view_item_grid'); ?>
    </div>

</div>

<div style="float: right; margin-top: 10px; margin-bottom: 8px;">
    <?php echo $this->getChildHtml('motor_close_btn'); ?>
</div>