<div id="block_notice_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This Section allows you to set preferences for automatic update of Products on eBay.<br/><br/>

        You have to Enable/Disable automatic Synchronization Tasks for List/Relist/Revise/Stop Rules of Synchronization Policy used for Products.<br/><br/>

        <strong>Note:</strong> You can start the Synchronization manually by clicking Synchronize Button.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/AwAJAQ')
    ); ?>
</div>