<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Listing_Moving_View */

?>

<div class="hor-scroll">
    <div id="listing_moving" >
        <?php echo $this->getChildHtml('listing_moving_help'); ?>
        <?php echo $this->getChildHtml('listing_moving_grid'); ?>
    </div>
</div>
