<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Variation_Product_Manage_Tabs_Variations */

?>

<div id="walmartVariationsProductManageVariationsGrid" style="height: 510px;">
    <?php
    $url = $this->getUrl('*/adminhtml_walmart_listing_variation_product_manage/viewVariationsGrid',
        array(
            'product_id'                => $this->getListingProductId(),
            'listing_product_id_filter' => $this->getListingProductIdForFilter(),
            'filter'                    => $this->getRequest()->getParam('filter')
        )
    );
    ?>
    <input type="hidden" id="walmartVariationsProductManageVariationsGridIframeUrl" value="<?php echo $url ?>">
</div>