<div id="block_notice_buy_template_synchronization_relist" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Relist Rules'); ?>">
    <?php echo Mage::helper('M2ePro')->__('If <strong>Relist Action</strong> is enabled, M2E Pro will Relist Items on Rakuten.com if they meet all the Conditions you set.<br/><br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/-4MVAQ')
    ); ?>
</div>

<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();
$defaults = array(
    'relist_mode' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES,
    'relist_filter_user_lock' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES,
    'relist_status_enabled' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES,
    'relist_is_in_stock' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES,

    'relist_qty_magento'           => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE,
    'relist_qty_magento_value'     => '1',
    'relist_qty_magento_value_max' => '10',

    'relist_qty_calculated'           => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE,
    'relist_qty_calculated_value'     => '1',
    'relist_qty_calculated_value_max' => '10'
);
$formData = array_merge($defaults, $formData);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.formData.relist_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_mode']); ?>';
    M2ePro.formData.relist_status_enabled = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_status_enabled']); ?>';
    M2ePro.formData.relist_is_in_stock = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_is_in_stock']); ?>';

    M2ePro.formData.relist_qty_magento = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_magento']); ?>';
    M2ePro.formData.relist_qty_magento_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_magento_value']); ?>';
    M2ePro.formData.relist_qty_magento_value_max = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_magento_value_max']); ?>';

    M2ePro.formData.relist_qty_calculated = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_calculated']); ?>';
    M2ePro.formData.relist_qty_calculated_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_calculated_value']); ?>';
    M2ePro.formData.relist_qty_calculated_value_max = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_calculated_value_max']); ?>';

    Event.observe(window, 'load', function() {
        $('relist_mode').observe('change', BuyTemplateSynchronizationHandlerObj.relistMode_change);
        $('relist_qty_magento').observe('change', BuyTemplateSynchronizationHandlerObj.relistQty_change);
        $('relist_qty_calculated').observe('change', BuyTemplateSynchronizationHandlerObj.relistQty_change);
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_buy_template_synchronization_relist_filters">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist Action'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_mode" name="relist_mode" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enables/Disables the Relist Action for the Listings, which use current Synchronization Policy.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_filter_user_lock_tr_container" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist When Stopped Manually'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_filter_user_lock" name="relist_filter_user_lock" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically Relists Item(s) even it has been Stopped manually within M2E Pro.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_template_synchronization_relist_rules" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Relist Conditions'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Product Status'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_status_enabled" name="relist_status_enabled" class="required-entry M2ePro-validate-stop-relist-conditions-product-status">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_NONE; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Product Status at which the Item(s) have to be Relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stock Availability'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_is_in_stock" name="relist_is_in_stock" class="required-entry M2ePro-validate-stop-relist-conditions-stock-availability">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_NONE; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('In Stock'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Stock Availability at which the Item(s) have to be Relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Magento Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_qty_magento" name="relist_qty_magento" class="required-entry M2ePro-validate-stop-relist-conditions-item-qty" qty_type="magento">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Magento Product(s) Quantity at which the Item(s) have to be Relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_qty_magento_value_container" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_magento_value">
                            <span id="relist_qty_magento_item" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="relist_qty_magento_item_min" <?php if ($formData['relist_qty_magento'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_magento_value" name="relist_qty_magento_value" value="<?php echo $this->escapeHtml($formData['relist_qty_magento_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="relist_qty_magento_value_max_container" <?php if ($formData['relist_qty_magento'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_magento_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_magento_value_max" name="relist_qty_magento_value_max" value="<?php echo $this->escapeHtml($formData['relist_qty_magento_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Calculated Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_qty_calculated" name="relist_qty_calculated" class="required-entry M2ePro-validate-stop-relist-conditions-item-qty" qty_type="calculated">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Calculated Quantity according to the Selling Format Policy at which the Item(s) have to be Relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_qty_calculated_value_container" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_calculated_value">
                            <span id="relist_qty_calculated_item" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="relist_qty_calculated_item_min" <?php if ($formData['relist_qty_calculated'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_calculated_value" name="relist_qty_calculated_value" value="<?php echo $this->escapeHtml($formData['relist_qty_calculated_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="relist_qty_calculated_value_max_container" <?php if ($formData['relist_qty_calculated'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_calculated_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_calculated_value_max" name="relist_qty_calculated_value_max" value="<?php echo $this->escapeHtml($formData['relist_qty_calculated_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>