<div id="block_notice_amazon_add_products_search_asin" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Existing Amazon Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Since most of the Products already exist in Amazon Catalog, M2E Pro makes it possible to find them and to make a link between your Magento Products and existing Amazon Products. <br/><br/>

    You can use a Manual Search for each added Product by clicking on the icon in the "ASIN/ISBN" Column of the Grid. <br/>

    Also you can use Automatic Search for added Product(s) by choosing <i class="underline">"Search ASIN/ISBN Automatically"</i> Option in a mass Actions bulk in the top right corner of the Grid. The Search will be performed according to the values which set in Search Settings. <br/><br/>

    You can always set or change Settings of the source for ASIN/ISBN and UPC/EAN by clicking <i class="underline">"Edit Search Settings"</i> Button in the right top corner. <br/><br/>

    <b>Note:</b> The process of Automatic Search might be time-consuming, depending on the number of added Products the Search is applied to.<br/><br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/2YcVAQ')); ?>
</div>