<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Wizard_InstallationAmazon_Presentation $this */

?>

<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Amazon Channel'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <div>
       <?php echo Mage::helper('M2ePro')->__('Setting up Settings to be able to sell on <strong>Amazon</strong>.'); ?>
    </div>

    <div class="step_container_buttons">
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>
</div>
