<div id="block_notice_walmart_logs_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">

    <?php echo Mage::helper('M2ePro')->__(
        'This Log contains information about the actions applied to M2E Pro Listings and related Items.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "x/L4taAQ")
    ); ?>

</div>