<style>
    .list {
        margin: 10px 0px !important;
        padding-left: 30px !important;
        list-style: disc outside;
    }
</style>
<div id="switch_to_parent_popup" style="display: none;">

    <div style="margin-top: 10px;">
        <?php echo Mage::helper('M2ePro')->__(
            'M2E Pro is able to work with Magento Variational Products in two different Modes:
            <ul class="list">
                <li>Selling Magento Variational Product as an Amazon Product with Parent/Child relation;</li>
                <li>Selling certain Variation of Magento Product as Individual Amazon Product.</li>
            </ul>

            You can read more about those two Modes in M2E Pro <a href="%url%" target="_blank">documentation</a>. <br/>
            This Product is now being treated as <strong>Individual Amazon Product</strong>, do you want to switch to <strong>Parent/Child Mode</strong>? <br/><br/>',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(Ess_M2ePro_Helper_Component_Amazon::NICK, 'Multi-Variational+Products')
        ); ?>
    </div>

    <div style="margin-left: 10px; float: left;">
        <input id="switch_to_parent_remember_checkbox" type="checkbox">
        &nbsp;&nbsp;
        <label for="switch_to_parent_remember_checkbox"><?php echo Mage::helper('M2ePro')->__('Remember my choice') ?></label>
    </div>

    <div style="float: right;">
        <?php echo $this->getChildHtml('yes_btn'); ?>
        &nbsp;&nbsp;
        <?php echo $this->getChildHtml('no_btn'); ?>
    </div>

</div>