<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Listing_Variation_Product_SwitchToParentPopup */

?>

<style>
    .list {
        margin: 10px 0px !important;
        padding-left: 30px !important;
        list-style: disc outside;
    }
</style>
<div id="switch_to_parent_popup" style="display: none;">

    <div style="margin-top: 10px;">
        <?php echo Mage::helper('M2ePro')->__(
            'You can sell Magento Variational Product on Amazon in two different ways:
            <ul class="list">
                <li>as Amazon Variational Product using Parent/Child Mode;</li>
                <li>as Amazon Individual Product using Individual Mode.</li>
            </ul>
            Find more details <a href="%url%" target="_blank" class="external-link">here</a>. <br/>

            This Product is currently managed under <strong>Individual Mode</strong>. Do you want to switch it to 
            <strong>Parent/Child Mode</strong>? <br/><br/>',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'multi-variational-products')
        ); ?>
    </div>

    <div style="margin-left: 10px; float: left;">
        <input id="switch_to_parent_remember_checkbox" type="checkbox">
        &nbsp;&nbsp;
        <label for="switch_to_parent_remember_checkbox"><?php echo Mage::helper('M2ePro')->__('Remember my choice') ?></label>
    </div>

    <div style="float: right;">
        <?php echo $this->getChildHtml('yes_btn'); ?>
        &nbsp;&nbsp;
        <?php echo $this->getChildHtml('no_btn'); ?>
    </div>

</div>