<div id="block_notice_amazon_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    This Page shows the Products you\'ve added to the current M2E Pro Listing.<br/><br/>

    Use the filters to find the Product you want to manage.<br/><br/>

    If ASIN/ISBN is available, clicking it will take you to the Product on Amazon.
    Click the <strong>Add Products</strong> Button to add new Magento Products to the M2E Pro Listing.
    Click <strong>Edit Settings</strong> to adjust the Settings for this Listing.
    To Add a new M2E Pro Listing or switch between different M2E Pro Listings, click the
    Arrow Icon to the right of the M2E Pro Listing Title above.<br/><br/>

    There are 4 <strong>View Modes</strong> available to you:
    <ul class="list">
    <li><strong>Amazon</strong> - displays Product information related to Amazon. In this Mode, you can easily find Products by Amazon information, perform Actions in bulk (i.e. List, Revise, Relist, Stop, etc);</li>
    <li><strong>Settings</strong> – displays Products settings like Description Policy assigned, etc. In this View Mode you can still perform some Actions in bulk.</li>
    <li><strong>Seller Central</strong> - displays Products the way they are shown on Amazon Seller Central (each Product shown individually). In this View Mode you can still perform some Actions in bulk.</li>
    <li><strong>Magento</strong> - displays Products information related to Magento Catalog. In this Mode, you can easily find Products using Magento Products information (i.e. Magento QTY, Stock Status, etc);</li>
    </ul>
    You can switch between Modes using Dropdown at the top of the Products Grid.<br/><br/>

    <strong>Note:</strong> If you need to Search by Magento Product Attributes not shown in the Filters of the Grid, click <strong>Show Advanced Filter</strong> above the Table on the right.<br/><br/>

    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/ZogVAQ')); ?>
</div>