<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('License'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->licenseMode; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Expired Date'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->licenseExpirationDate; ?>
        </td>
    </tr>

</table>