<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Configuration_Category_Help */

?>

<div id="block_notice_ebay_configuration_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Categories In Use'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows the eBay Categories you\'re currently using in your M2E Pro Listings.
        Categories are highlighted if the eBay Category no longer exists due to Category changes made by eBay.<br/><br/>
        Click the line with the Order in the Table below to <b>Edit</b> the eBay Category and Item Specifics for that Category.<br/><br/>
        Any changes you make will affect all M2E Pro Listings that use that Category.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/DQAJAQ')
    ); ?>
</div>