<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Configuration_Category_Help */

?>

<div id="block_notice_ebay_configuration_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Categories'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows eBay Categories that are currently used in your M2E Pro Listings.<br/>
        Any changes you make on this page will affect M2E Pro Listings where these Categories are used.
        Read <a href="%url%" target="_blank">the article</a> to learn how to manage eBay Categories.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'x/A4V8AQ')
    ); ?>
</div>
