<?php
    $errors = $this->getErrors();
?>
<style type="text/css">
    #errors-table {
        background-color: #FFF7EA !important;
        border: 1px dashed #FF7A7A !important;
    }
    #errors-table th, #errors-table td {
        padding: 10px !important;
    }
    #errors-table th {
        border-bottom: 1px solid #D6D6D6 !important;
    }
    #errors-table td.total {
        font-weight: bold;
    }
    #errors-buttons {
        padding: 10px 0 !important;
        text-align: right;
    }
</style>
<div class="entry-edit" style="padding-top: 10px;">

    <div><?php echo Mage::helper('M2ePro')->__('Fee cannot be estimated because of next error(s)') ?>:</div>

    <div class="hor-scroll" style="padding-top: 10px;">
        <table id="errors-table" cellspacing="0" class="form-list" style="width: 100%;">
            <tbody>
                <?php foreach ($errors as $error): ?>
                    <tr>
                        <td class="value"><?php echo Mage::helper('M2ePro')->escapeHtml($error['text']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div id="errors-buttons">
    <?php echo $this->getChildHtml('close_button') ?>
</div>