<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_View_Fee_Product */

$feeDetailsId = uniqid('fee-details-');

?>

<div id="<?php echo $feeDetailsId ?>" style="display: none;">
    <?php echo $this->getChildHtml('details'); ?>
</div>
<span><?php echo $this->getTotalFee() ?>&nbsp;[<a href="javascript:void(0);" onclick="EbayListingEbayGridObj.openFeePopUp($('<?php echo $feeDetailsId ?>').innerHTML);"><?php echo Mage::helper('M2ePro')->__('details') ?></a>]</span>