<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Magento_Product_Rule */

$_element = $this->getElement();
?>

<div class="rule-tree">
    <div id="<?php echo $_element->getHtmlId(); ?>">
        <?php echo $_element->getChildrenHtml() ?>
    </div>
</div>
<script type="text/javascript">
<?php echo $_element->getHtmlId() ?> = new VarienRulesForm('<?php echo $_element->getHtmlId() ?>', '<?php echo $this->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()): ?>
    <?php echo $_element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>
</script>
