<div id="block_notice_ebay_feedbacks_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Feedback'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page contains Feedback received from eBay Buyers and your responses to them.<br/><br/>
        You can respond to Feedback that hasn\'t already been responded to by clicking the <b>Response</b> Button for the Order and completing the form.<br/><br/>
        <b>Note:</b> Auto-responses to Feedback are sent according to the eBay Accounts > Feedback Settings.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/OAAJAQ')
    ); ?>
</div>