<div id="block_notice_walmart_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">

    <?php echo Mage::helper('M2ePro')->__('
        In this section, you can configure the general settings for interaction between M2E Pro and Walmart Marketplaces.<br/><br/>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/L4taAQ")
    ); ?>

</div>