<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_About */

?>

<!-- ########################################################################################### -->

<div class="box-left">

    <div class="entry-edit" id="magento_block_controlPanel_info_location">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Location'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('location') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_controlPanel_info_license_information">

       <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Billing Info'); ?></h4>
       </div>

       <div class="fieldset">
           <div class="hor-scroll">

               <?php echo $this->getChildHtml('license_information') ?>

           </div>
       </div>

    </div>

</div>

<!-- ########################################################################################### -->

<div class="box-right">

    <div class="entry-edit" id="magento_block_controlPanel_info_magento">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Magento'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('magento') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_controlPanel_info_system">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('System'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('system') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_controlPanel_info_php">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('PHP'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('php') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_controlPanel_info_mysql_info">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('MySQL'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('mysql_info') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_controlPanel_info_mysql_summary">

        <div class="controlPanel_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('MySQL Summary'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('mysql_summary') ?>

            </div>
        </div>

    </div>

</div>

<!-- ########################################################################################### -->