<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_Debug */

?>

<div id="magento_block_controlPanel_debug_commands">

    <table class="simple_commands_list">

        <tr>
            <td>
                <a href="<?php echo $this->getUrl('*/adminhtml_controlPanel/firstTest') ?>" target="_blank">First Test</a>
                <p>Command for quick development</p>
            </td>
        </tr>

        <tr>
            <td>
                <a href="<?php echo $this->getUrl('*/adminhtml_controlPanel/secondTest') ?>" target="_blank">Second Test</a>
                <p>Command for quick development</p>
            </td>
        </tr>

    </table>

</div>