<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_Inspection */

?>

<script>
    <?php if ($this->getRequest()->isXmlHttpRequest()): ?>
        ControlPanelInspectionObj = new ControlPanelInspection();
    <?php else: ?>
    Event.observe(window, 'load', function() {
        ControlPanelInspectionObj = new ControlPanelInspection();
    });
    <?php endif; ?>
</script>

<div>
    <?php echo $this->getChildHtml('inspections') ?>
</div>
