<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_Module */

?>

<div class="entry-edit group_container" id="magento_block_controlPanel_module_integration">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_module_integration'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_module_integration_ebay">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration [eBay]'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_module_integration_ebay'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_module_integration_amazon">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration [Amazon]'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_module_integration_amazon'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_module_integration_walmart">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration [Walmart]'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_module_integration_walmart'); ?>
    </div>

</div>