<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_Tools */

?>

<div class="entry-edit group_container" id="magento_block_controlPanel_tools_m2epro_general">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('M2E Pro (General)'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_tools_m2epro_general'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_tools_m2epro_install">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('M2E Pro (Install / Upgrade)'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_tools_m2epro_install'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_tools_magento">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Magento'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_tools_magento'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_controlPanel_tools_additional">

    <div class="controlPanel_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Additional'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('controlPanel_tools_additional'); ?>
    </div>

</div>