<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Wizard_InstallationEbay_Notification $this */

?>

<script type="text/javascript">

</script>

<?php

$version = Mage::helper('M2ePro/Module')->getPublicVersion();
$startWizardLink = $this->getUrl("*/adminhtml_wizard_installationEbay");

?>

<div class="wizard-note">

    <div>
        <?php

        echo Mage::helper('M2ePro')->__(
            'You have successfully installed <strong>M2E Pro v. %version%</strong>.<br/>
             Click
             <a href="%url%">Start Configuration</a> Wizard to quickly set up main Settings',
            $version,
            $startWizardLink
        );

        ?>
    </div>

</div>
