<div id="block_notice_walmart_accounts_general" class="block_notices_module marketplace-required-field marketplace-required-field-id-not-null" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">

    <div class="marketplace-required-field marketplace-required-field-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_US ?>">
        <?php echo Mage::helper('M2ePro')->__(
            'Under this section, you need to connect M2E Pro with your Walmart account. Please complete the following steps:<br>
        <ul class="list">
            <li>Select Walmart marketplace.</li>
            <li>Click <b>Get Access Data</b>. You will be redirected to the Walmart Developer Center.</li>
            <li>Log in using your Walmart Seller credentials.</li>
            <li>Under <i>Username > API Keys > Digital Signature</i>, copy your <i>Consumer ID</i> and paste it into the current M2E Pro page. </li>
            <li>Under <i>Username > Delegate Access</i>, provide M2E Pro with the full access permissions to all API sections. Click <b>API Keys</b> to generate <i>Client ID</i> and <i>Client Secret</i>.</li>
            <li>Copy your <i>Client ID</i> and <i>Client Secret</i> and paste the keys into the current M2E Pro page.</li>
            <li>Click <b>Save and Continue Edit</b>. Extension will be granted access to your Walmart account data.</li>
        </ul>
        
        <b>Note:</b> Your <i>Consumer ID</i> must not be changed once it is obtain. <i>Consumer ID</i> is unique seller identifier M2E Pro requires to act on your behalf. <br>
        If you need to reauthorize Extension, please generate new <i>Client ID</i> and <i>Client Secret</i> for M2E Pro under <i>Username > Delegate Access</i> in Developer Center. <br><br>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, '/x/io1aAQ')
        ); ?>
    </div>

    <div class="marketplace-required-field marketplace-required-field-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_CA ?>">
        <?php echo Mage::helper('M2ePro')->__(
            'Under this section, you need to connect M2E Pro with your Walmart account. Please complete the following steps:<br/>

        <ul class="list">
            <li>Click <b>Get Access Data</b>. You will be redirected to the Walmart website</li>
            <li>Log in to your Seller Center Account.</li>
            <li>In admin panel, navigate to <i>Settings > API > Consumer IDs & Private Keys</i>.</li>
            <li>Copy the generated <i>Consumer ID</i> and <i>Private Key</i> to the corresponding fields on the current page.</li>
            <li>Click <b>Save and Continue Edit</b>. The Extension will be granted access to your Walmart Account data.</li>
        </ul>
        
        <b>Note:</b> Make sure that you copy valid API credentials, i.e <i>Consumer ID</i> and <i>Private Key</i>.<br><br>
        
        <b>Important note:</b> <i>Private Key</i> is common for all applications you are using. Regeneration of the Key will deactivate your previous <i>Private Key</i>. This may cause the apps to no longer function properly<br><br>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, '/x/io1aAQ')
        ); ?>
    </div>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $defaults = array(
        'title'           => '',
        'marketplace_id'  => 0,
        'consumer_id'     => '',
        'old_private_key' => '',
        'client_id'       => '',
        'client_secret'   => ''
    );

    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');

    $licenseMessage = '';

    if ($isEdit) {
        $licenseMessage = (string)Mage::helper('M2ePro/Data_Global')->getValue('license_message');
    }
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Account'); ?>,
        'Ess_M2ePro_Model_Walmart_Account'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component_Walmart'
    );

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_walmart_account')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_walmart_account/save', array('id' => $this->getRequest()->getParam('id'))),
        '*/*/delete' => $this->getUrl('M2ePro/adminhtml_walmart_account/delete'),

        'adminhtml_walmart_account/beforeGetToken' => $this->getUrl('M2ePro/adminhtml_walmart_account/beforeGetToken', array('wizard' => (bool)$this->getRequest()->getParam('wizard', false))),
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.' => Mage::helper('M2ePro')->__('Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.'),
        'Please enter correct value.' => Mage::helper('M2ePro')->__('Please enter correct value.'),
        'Coefficient is not valid.' => Mage::helper('M2ePro')->__('Coefficient is not valid.'),
        'on_delete_account_message' => Mage::helper('M2ePro')->__('Attention! By applying this action you delete the Account data only from current M2E Pro instance. It does not affect the Subscription status and Billing process for this Channel Account. <br><br>
                                                                   To delete Channel Account which you don\'t need to manage under M2E Pro Subscription Plan, go to the <a href="%url%" target="_blank">Clients Portal</a>.',
                                                                   Mage::helper('M2ePro/Module_Support')->getClientsPortalBaseUrl())
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        <?php echo $licenseMessage; ?>

        WalmartAccountHandlerObj = new WalmartAccountHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        $('marketplace_id')
            .observe('change', WalmartAccountHandlerObj.changeMarketplace)
            .simulate('change');

        var urlHash = location.hash.substr(1);
        if (urlHash != '') {
            setTimeout(function() {
                walmartAccountEditTabsJsTabs.tabs.each(function(tab){
                    if (tab.name == urlHash) {
                        walmartAccountEditTabsJsTabs.showTabContent(tab);
                    }
                });
                location.hash = '';
            }, 100);
        }
    });
    //-----------------------------

</script>

<script type="M2ePro/template" id="on_delete_account_template"><?php echo $this->getChildHtml('confirm_popup'); ?></script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'The specified Title is already used for other Account. Account Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Account. Account Title must be unique.'),
        'You must choose Marketplace first.' => Mage::helper('M2ePro')->__('You must choose Marketplace first.'),
        'M2E Pro was not able to get access to the Walmart Account' => Mage::helper('M2ePro')->__('M2E Pro could not get access to your Walmart account. 
                                                                                                    For Walmart CA, please check if you entered valid Consumer ID and Private Key.
                                                                                                    For Walmart US, please ensure to provide M2E Pro with full access permissions to all API sections and enter valid Consumer ID, Client ID, and Client Secret.'),
        'M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%')
    )); ?>);

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_walmart_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or Identifier of Walmart Account for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    <div class="locked_block">

        <div class="locked_wrapper">
            <div><?php echo Mage::helper('M2ePro')->__('Synchronizing Now') ?></div>
        </div>
<?php } ?>

<?php if ($isEdit && !$formData['client_id'] && $formData['marketplace_id'] != Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_CA) { ?>
    <div id="messages">
        <ul class="messages">
            <li class="warning-msg">
                <ul>
                    <li>
                        <?php echo Mage::helper('M2ePro')->__(
                            '<p>
                                Attention! M2E Pro needs to be reauthorized.<br>
                                Authentication based on the Private Key will be deprecated soon. You need to grant M2E Pro access based on the new Walmart Access Token based Authentication.<br>
                                To reauthorize M2E Pro, please generate <i>Client ID</i> and <i>Client Secret</i> following the instruction in the Help block above.
                            </p>
                            <p>Important: Your <i>Consumer ID</i> must not be changed once it is obtain. <i>Consumer ID</i> is unique seller identifier M2E Pro requires to act on your behalf.</p>'
                        ); ?>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
<?php } ?>

<div class="entry-edit" id="magento_block_walmart_accounts_marketplaces_access" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Access Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">

                        <select id="marketplace_id" name="marketplace_id" <?php if ($isEdit) { ?>disabled="disabled"<?php } ?> class="required-entry">

                            <?php if (!$isEdit) { ?>
                                <option style="display:none;"></option>
                            <?php } ?>

                            <?php foreach ($this->marketplaces as $marketplaceRow) { ?>
                                <option value="<?php echo $marketplaceRow['id']; ?>" <?php if ($formData['marketplace_id'] == $marketplaceRow['id']) { ?>selected="selected"<?php } ?>>
                                    <?php echo Mage::helper('M2ePro')->__($marketplaceRow['title']); ?>
                                </option>
                            <?php } ?>

                        </select>

                        <?php if ($isEdit) : ?>
                            <input type="hidden" name="marketplace_id" value="<?php echo $formData['marketplace_id']; ?>" />
                        <?php endif; ?>

                    </td>
                </tr>

                <?php foreach ($this->marketplaces as $marketplaceRow) { ?>

                    <tr class="marketplace-required-field marketplace-required-field-id<?php echo $marketplaceRow['id']; ?>">
                        <td class="label"></td>
                        <td class="value">
                            <a href="<?php echo Mage::helper('M2ePro/Component_Walmart')->getRegisterUrl($marketplaceRow['id']); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get Access Data') ?></a>
                        </td>
                    </tr>

                <?php } ?>

                <tr class="marketplace-required-field marketplace-required-field-id-not-null">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Consumer ID'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="consumer_id" type="text" name="consumer_id" <?php if ($isEdit) echo ' value="'.$formData['consumer_id'].'" disabled="disabled"'; ?> class="input-text required-entry M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('A unique seller identifier on the website. <br><b>Note:</b> Your <i>Consumer ID</i> must not be changed once it is obtain.'); ?></span>
                        </p>

                        <?php if ($isEdit) : ?>
                            <input type="hidden" name="consumer_id" value="<?php echo $formData['consumer_id']; ?>" />
                        <?php endif; ?>
                    </td>
                </tr>

                <tr class="marketplace-required-field marketplace-required-field-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_CA ?>">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Private Key'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <textarea name="old_private_key" id="old_private_key" cols="50" rows="10" class="marketplace-required-input marketplace-required-input-text-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_CA ?> input-text M2ePro-required-when-visible" style="height: 15em;"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['old_private_key']); ?></textarea>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Walmart Private Key generated from your Seller Center Account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="marketplace-required-field marketplace-required-field-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_US ?>">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Client ID'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="client_id" type="text" name="client_id" <?php if ($isEdit) echo ' value="'.$formData['client_id'].'"'; ?> class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('A unique API key retrieved to get an access token.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="marketplace-required-field marketplace-required-field-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_US ?>">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Client Secret'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <textarea name="client_secret" id="client_secret" cols="50" rows="10" class="marketplace-required-input marketplace-required-input-text-id<?php echo Ess_M2ePro_Helper_Component_Walmart::MARKETPLACE_US ?> input-text M2ePro-required-when-visible" style="height: 5em;"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['client_secret']); ?></textarea>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('A unique API key retrieved to get an access token.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    </div>
<?php } ?>
