<div id="block_notice_walmart_accounts_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Provide an Account Title and select Walmart Marketplace.<br><br>

        To connect M2E Pro with your Walmart Account, please complete the following steps:<br/>
        <ul class="list">
            <li>Click Get Access Data. You will be redirected to the Walmart website.</li>
            <li>Log in to your Seller Center Account.</li>
            <li>In admin panel, navigate to <i>Settings > API > Consumer IDs & Private Keys (Client ID and Client Secret)</i>.</li>
            <li>Copy the generated Consumer ID and Private Key to the corresponding fields on the current page.</li>
            <li>Click Save and Continue Edit. Extension will be granted access to your Walmart Account data.</li>
        </ul>
        
        <b>Note:</b> Make sure that you copy the valid API credentials, i.e. <b>Consumer ID</b> and <b>Private Key</b>.<br><br>
        
        <b>Important note:</b> The Private Key is common for all applications you are using. Regeneration of the Key will deactivate your previous Private Key.
        This may cause the apps to no longer function properly.<br><br>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/L4taAQ')
    ); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $defaults = array(
        'title'           => '',
        'marketplace_id'  => 0,
        'consumer_id'     => '',
        'private_key'     => ''
    );

    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');

    $licenseMessage = '';

    if ($isEdit) {
        $licenseMessage = (string)Mage::helper('M2ePro/Data_Global')->getValue('license_message');
    }
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Account'); ?>,
        'Ess_M2ePro_Model_Walmart_Account'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component_Walmart'
    );

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_walmart_account')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_walmart_account/save', array('id' => $this->getRequest()->getParam('id'))),
        '*/*/delete' => $this->getUrl('M2ePro/adminhtml_walmart_account/delete'),

        'adminhtml_walmart_account/beforeGetToken' => $this->getUrl('M2ePro/adminhtml_walmart_account/beforeGetToken', array('wizard' => (bool)$this->getRequest()->getParam('wizard', false))),
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.' => Mage::helper('M2ePro')->__('Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.'),
        'Please enter correct value.' => Mage::helper('M2ePro')->__('Please enter correct value.'),
        'Coefficient is not valid.' => Mage::helper('M2ePro')->__('Coefficient is not valid.'),
        'on_delete_account_message' => Mage::helper('M2ePro')->__('Attention! By applying this action you delete the Account data only from current M2E Pro instance. It does not affect the Subscription status and Billing process for this Channel Account. <br><br>
                                                                   To delete Channel Account which you don\'t need to manage under M2E Pro Subscription Plan, go to the <a href="%url%" target="_blank">Clients Portal</a>.',
                                                                   Mage::helper('M2ePro/Module_Support')->getClientsPortalBaseUrl())
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        <?php echo $licenseMessage; ?>

        WalmartAccountHandlerObj = new WalmartAccountHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        <?php if ($isEdit) { ?>
            WalmartAccountHandlerObj.showGetAccessData(<?php echo $formData['marketplace_id']; ?>);
        <?php } else {?>
            if ($('marketplace_id').value) {
                $('marketplace_id').simulate('change');
            }
        <?php } ?>

        var urlHash = location.hash.substr(1);
        if (urlHash != '') {
            setTimeout(function() {
                walmartAccountEditTabsJsTabs.tabs.each(function(tab){
                    if (tab.name == urlHash) {
                        walmartAccountEditTabsJsTabs.showTabContent(tab);
                    }
                });
                location.hash = '';
            }, 100);
        }
    });
    //-----------------------------

</script>

<script type="M2ePro/template" id="on_delete_account_template"><?php echo $this->getChildHtml('confirm_popup'); ?></script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'The specified Title is already used for other Account. Account Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Account. Account Title must be unique.'),
        'You must choose Marketplace first.' => Mage::helper('M2ePro')->__('You must choose Marketplace first.'),
        'M2E Pro was not able to get access to the Walmart Account. Please, make sure, that you choose correct Option on Private Key Authorization Page and enter correct Consumer ID.' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Walmart Account. Please, make sure, that you choose correct Option on Private Key Authorization Page and enter correct Consumer ID / Private Key Auth Token'),
        'M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%')
    )); ?>);

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_walmart_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or Identifier of Walmart Account for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    <div class="locked_block">

        <div class="locked_wrapper">
            <div><?php echo Mage::helper('M2ePro')->__('Synchronizing Now') ?></div>
        </div>
<?php } ?>

<div class="entry-edit" id="magento_block_walmart_accounts_marketplaces_access" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Access Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">

                        <select id="marketplace_id" name="marketplace_id" <?php if ($isEdit) { ?>disabled="disabled"<?php } ?> onchange="WalmartAccountHandlerObj.showGetAccessData(this.value);" class="required-entry">

                            <?php if (!$isEdit) { ?>
                                <option style="display:none;"></option>
                            <?php } ?>

                            <?php foreach ($this->marketplaces as $marketplaceRow) { ?>
                                <option value="<?php echo $marketplaceRow['id']; ?>" <?php if ($formData['marketplace_id'] == $marketplaceRow['id']) { ?>selected="selected"<?php } ?>>
                                    <?php echo Mage::helper('M2ePro')->__($marketplaceRow['title']); ?>
                                </option>
                            <?php } ?>

                        </select>

                        <?php if ($isEdit) : ?>
                            <input type="hidden" name="marketplace_id" value="<?php echo $formData['marketplace_id']; ?>" />
                        <?php endif; ?>

                    </td>
                </tr>

                <?php foreach ($this->marketplaces as $marketplaceRow) { ?>

                    <tr class="marketplaces_view_element" id="marketplaces_register_url_container_<?php echo $marketplaceRow['id']; ?>" style="display:none;">
                        <td class="label"></td>
                        <td class="value">
                            <a href="<?php echo Mage::helper('M2ePro/Component_Walmart')->getRegisterUrl($marketplaceRow['id']); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get Access Data') ?></a>
                        </td>
                    </tr>

                <?php } ?>

                <tr id="marketplaces_consumer_id_container">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Consumer ID'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="consumer_id" type="text" name="consumer_id" <?php if ($isEdit) echo ' value="'.$formData['consumer_id'].'"'; ?> class="input-text required-entry M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Walmart Consumer ID generated from your Seller Center Account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="marketplaces_private_key_container">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Private Key'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <textarea name="private_key" id="private_key" cols="50" rows="10" class="required-entry input-text M2ePro-marketplace-merchant M2ePro-required-when-visible" style="height: 15em;"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['private_key']); ?></textarea>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Walmart Private Key generated from your Seller Center Account.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    </div>
<?php } ?>