<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Account_Edit_Tabs_General */

?>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $defaults = Mage::getModel('M2ePro/Walmart_Account_Builder')->getDefaultData();

    $formData = array_merge($defaults, $formData);

    $licenseMessage = (string)Mage::helper('M2ePro/Data_Global')->getValue('license_message');

    $marketplace = $this->getMarketplace();
?>

<div id="block_notice_walmart_accounts_general-" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">

    <div>
        <?php echo Mage::helper('M2ePro')->__(
            'Under this section, you can link your Walmart account to M2E Pro. Read how to <a href="%url%" target="_blank">get the API credentials</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'account-configuration')
        ); ?>
    </div>

</div>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Account'); ?>, 'Ess_M2ePro_Model_Walmart_Account');
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>, 'Ess_M2ePro_Helper_Component_Walmart');

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_walmart_account')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_walmart_account/save', array('id' => $this->getRequest()->getParam('id'))),
        '*/*/delete' => $this->getUrl('M2ePro/adminhtml_walmart_account/delete'),
        'adminhtml_walmart_account/beforeGetToken' => $this->getUrl('M2ePro/adminhtml_walmart_account/beforeGetToken', array('wizard' => (bool)$this->getRequest()->getParam('wizard', false))),
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Please enter correct value.' => Mage::helper('M2ePro')->__('Please enter correct value.'),
        'Coefficient is not valid.' => Mage::helper('M2ePro')->__('Coefficient is not valid.'),
        'on_delete_account_message' => Mage::helper('M2ePro')->__(
            <<<HTML
<p>You are about to delete your eBay/Amazon/Walmart seller account from M2E Pro. This will remove the
account-related Listings and Products from the extension and disconnect the synchronization.
Your listings on the channel will <b>not</b> be affected.</p>
<p>Please confirm if you would like to delete the account.</p>
<p>Note: once the account is no longer connected to your M2E Pro, please remember to delete it from
<a href="%url%">M2E Accounts</a></p>
HTML
            ,
            Mage::helper('M2ePro/Module_Support')->getAccountsUrl()
        )
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        <?php echo $licenseMessage; ?>

        WalmartAccountObj.initValidation();
        WalmartAccountObj.initTokenValidation();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        $('marketplace_id').disable();

        var urlHash = location.hash.substr(1);
        if (urlHash != '') {
            setTimeout(function() {
                walmartAccountEditTabsJsTabs.tabs.each(function(tab){
                    if (tab.name == urlHash) {
                        walmartAccountEditTabsJsTabs.showTabContent(tab);
                    }
                });
                location.hash = '';
            }, 100);
        }
    });
    //-----------------------------

</script>

<script type="M2ePro/template" id="on_delete_account_template"><?php echo $this->getChildHtml('confirm_popup'); ?></script>

<script type="text/javascript">

    M2ePro.translator.add(<?php echo json_encode(array(
        'The specified Title is already used for other Account. Account Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Account. Account Title must be unique.'),
        'M2E Pro was not able to get access to the Walmart Account' => Mage::helper('M2ePro')->__(
            'M2E Pro could not get access to your Walmart account. 
            For Walmart CA, please check if you entered valid Consumer ID and Private Key.'
        ),
        'M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Walmart Account. Reason: %error_message%'),
    )); ?>);

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';

</script>

<div class="entry-edit" id="magento_block_walmart_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or Identifier of Walmart Account for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">

                        <select name="marketplace_id" class="required-entry disabled">

                            <option value="<?php echo $marketplace->getId(); ?>" <?php if ($formData['marketplace_id'] == $marketplace->getId()) { ?>selected="selected"<?php } ?>>
                                <?php echo Mage::helper('M2ePro')->__($marketplace->getTitle()); ?>
                            </option>

                        </select>

                        <input type="hidden" name="marketplace_id" id="marketplace_id" value="<?php echo $formData['marketplace_id']; ?>" />

                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_walmart_accounts_marketplaces_access" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Access Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <div style="margin-left: 10%">
                    <?php echo $this->getChildHtml('update_access_button'); ?>
                </div>

            </table>

        </div>
    </div>

</div>
