<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_PickupStore_Variation_Product_View_Help */

?>

<div id="block_notice_ebay_product_manage_variations" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Product Variations'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        In this section, you can observe Store and Product Variation details as well as their Quantity and Logs
        for each Variation separately.
    '); ?>
</div>