<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Wizard_MigrationNewAmazon_Notification $this */

$startWizardLink = $this->getUrl("*/adminhtml_wizard_migrationNewAmazon");

?>

<div class="wizard-note">

    <div>
        <?php

        echo Mage::helper('M2ePro')->__(
            'Click
            <a href="%url_1%">Start Configuration</a> Wizard to start migration process to <strong>new M2E Pro Amazon</strong> generation.',
            $startWizardLink
        );

        ?>
    </div>

</div>