<div id="block_notice_ebay_listings_pickup_sotre_step_stores" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Assign Products to Stores'); ?>">
    <p>
        <?php echo Mage::helper('M2ePro')->__('
            Select the Products which should be assigned to the Store to make them available for In-Store Pickup
            Service.<br/>
            <strong>Please note</strong>, only those Products that are presented in the current M2E Pro
            Listing are available for selection. In case you want to add other Products to the Store, you
            should add them to the M2E Pro Listing first.
        '); ?>
    </p>

</div>