<div id="block_notice_buy_listings_add_products" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Displayed Products have the same Attribute Set as the Listing you are going to add them to.<br/><br/>
    <b>Note:</b> A Product can be added to the Listing only once. If a Product was added to the Listing earlier, it will not be displayed. '); ?>
</div>