<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Log_Listing_Help */

?>

<div id="block_notice_walmart_logs_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains information about the actions applied to M2E Pro Listings and related Items.<br/><br/>
        Find detailed info in <a href="%url%" target="_blank">the article</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'logs-events-walmart#6b081a88d8be4fa0a927dfd372080610')
    ); ?>
</div>