<?php
    /** @var Ess_M2ePro_Model_Requirements_Manager $manager */
    $manager = Mage::getModel('M2ePro/Requirements_Manager');
?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label" style="width:200px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Properties'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Minimum / Recommended Value'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Current Value'); ?></strong>
        </td>
    </tr>

    <?php foreach($manager->getChecks() as $check) { ?>
        <tr>
            <td class="label">
                <label><?php echo $check->getRenderer()->getTitle(); ?></label>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getMin(); ?>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getReal(); ?>
            </td>
        </tr>
    <?php } ?>

</table>