<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_View_Help */

?>

<div id="block_notice_walmart_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    On this page, you can review Products that you added to the current M2E Pro Listing. Use filter and sort options to quickly find the required Item in the grid below.<br>
    Click <i>Show Advanced Filter</i> to narrow your search results based on the defined conditions, e.g. find the Item by specified Magento Attribute value.<br/><br/>

    Switch between 3 View Modes to manage the related Item data:
    <ul class="list">
        <li>
            <strong>Walmart</strong> - displays the Products based on their Channel information, i.e. the current Item Price, Quantity, Status, etc. on Walmart.<br>
            For each individual Item, you can edit the related SKU or Product ID values. The Mass Actions allows managing Walmart Items in bulk, i.e. List, Revise, Relist, Stop the Item, etc.<br>
            In Manage Variation pop-up, Walmart Variant Groups can be configured.
        </li>
        <li>
            <strong>Settings</strong> – allows you to assign a new Category Policy to the selected Item, duplicate the Item in the current Listing or move it to another one.
        </li>
        <li>
            <strong>Magento</strong> - displays the Products based on their Magento information, i.e. the current Product Price, Quantity, Stock Availability, Status, etc. in Magento.
        </li>
    </ul>
    To edit the entire Listing configurations, click Edit Settings.<br/><br/>

    The detailed information can be found <a href="%url%" target="_blank">here</a>.',

    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'walmart-integration')); ?>
</div>