<div id="block_notice_amazon_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        Enable Inventory Synchronization to automatically update your Amazon Listings based on Synchronization Rules.<br/><br/>

        Please be advised that if you disable Inventory Synchronization, you will be required to monitor the Product changes by yourself and timely update the related information on the Channel.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',
        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/k4cVAQ")
    ); ?>
</div>