<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Synchronization_Edit_Form */

$translations = array();

// ->__('Synchronization Settings have been saved.')
$text = 'Synchronization Settings have been saved.';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Running All Enabled Tasks')
$text = 'Running All Enabled Tasks';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Another Synchronization Is Already Running.')
$text = 'Another Synchronization Is Already Running.';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Getting information. Please wait ...')
$text = 'Getting information. Please wait ...';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Preparing to start. Please wait ...')
$text = 'Preparing to start. Please wait ...';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Synchronization has successfully ended.')
$text = 'Synchronization has successfully ended.';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Synchronization ended with warnings. <a target="_blank" href="%url%">View Log</a> for details.')
$text = 'Synchronization ended with warnings. <a target="_blank" href="%url%">View Log</a> for details.';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Synchronization ended with errors. <a target="_blank" href="%url%">View Log</a> for details.')
$text = 'Synchronization ended with errors. <a target="_blank" href="%url%">View Log</a> for details.';
$translations[$text] = Mage::helper('M2ePro')->__($text);

// ->__('Revise All')
$text = 'Revise All';
$translations[$text] = Mage::helper('M2ePro')->__($text);

$translations = json_encode($translations);

?>

    <script type="text/javascript">

        M2ePro.url.add(<?php echo json_encode(array(
            'formSubmit' => $this->getUrl('M2ePro/adminhtml_walmart_synchronization/save'),
            'logViewUrl' => $this->getUrl('M2ePro/adminhtml_walmart_log/synchronization',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_walmart_synchronization/index'))),

            'runReviseAll'        => $this->getUrl('M2ePro/adminhtml_walmart_synchronization/runReviseAll'),

            'synchCheckProcessingNow' => $this->getUrl('M2ePro/adminhtml_walmart_synchronization/synchCheckProcessingNow')
        )); ?>);

        M2ePro.translator.add(<?php echo $translations; ?>);

        Event.observe(window, 'load', function() {
            setTimeout(function() {
                SynchronizationProgressHandlerObj = new SynchProgressHandler(SynchProgressBarObj, SynchWrapperObj );
                SynchronizationHandlerObj = new SynchronizationHandler(SynchronizationProgressHandlerObj);

                editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

                <?php if ($this->getChildBlockId() !== null) { ?>
                <?php
                $childBlockId = Mage::helper('M2ePro')->escapeJs($this->getChildBlockId());
                $destinationBlockId = Mage::helper('M2ePro')->escapeJs($this->getForm()->getId());
                ?>
                SynchronizationHandlerObj.moveChildBlockContent('<?php echo $childBlockId; ?>', '<?php echo $destinationBlockId; ?>');
                <?php } ?>

            }, 350);
        });

    </script>

    <form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

        <div id="<?php echo $this->getContainerId(); ?>">

            <div class="entry-edit" id="magento_block_walmart_synchronization_templates">

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Inventory Synchronization'); ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">

                        <table class="form-list" cellspacing="0" cellpadding="0">

                            <tr>
                                <td class="label">
                                    <label for="walmart_instructions_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>:</label>
                                </td>
                                <td class="value">
                                    <?php $instructions_mode = $this->instructionsMode ? $this->instructionsMode : 0; ?>
                                    <select id="walmart_instructions_mode" name="walmart_instructions_mode">
                                        <option value="0"<?php if (0 == $instructions_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                        <option value="1"<?php if (1 == $instructions_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Enable to automatically update Walmart Listings based on Synchronization Rules'); ?></span>
                                    </p>
                                </td>
                            </tr>

                        </table>

                        <div style="padding: 12px"></div>

                        <?php if ($this->isShowReviseAll()) { ?>
                            <div id="block_notice_walmart_synchronization_revise_all" style="<?php if (!$instructions_mode) echo 'display: none'; ?>" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

                                <?php echo Mage::helper('M2ePro')->__('If your Walmart Listings for some reason were asynchronized with the Products in Magento, <a href="javascript:" onclick="%script_code%">turn on</a> the Revise All action to catch data up.
        <br/>Revise is performed by the Inventory Synchronization, 100 Items per a cycle.
    <br/><br/>',
                                    'SynchronizationHandlerObj.showReviseAllConfirmPopup(\''.Ess_M2ePro_Helper_Component_Walmart::NICK.'\');'
                                )?>

                                <span id="walmart_revise_all_start" style="display: none">

                            <span style="color: blue">
                                <?php echo Mage::helper('M2ePro')->__('In Progress, start date - ') ?>
                            </span>

                            <span id="walmart_revise_all_start_date" style="color: blue">
                                <?php echo $this->reviseAllStartDate; ?>
                            </span>

                        </span>

                                <span id="walmart_revise_all_end" style="display: none">

                            <span style="color: green">
                                <?php echo Mage::helper('M2ePro')->__('Finished, end date - ') ?>
                            </span>

                            <span id="walmart_revise_all_end_date" style="color: green">
                                <?php echo $this->reviseAllEndDate; ?>
                            </span>

                        </span>

                            </div>
                        <?php } ?>

                    </div>
                </div>

            </div>

            <div class="entry-edit" id="magento_block_walmart_synchronization_templates_text">

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Advanced Settings'); ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">

                        <div class="block_notices_module" style="border: 0 !important; margin-bottom: 0 !important;" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                            <?php echo Mage::helper('M2ePro')->__('
                        If you update Magento Product Information not via Magento backend and Standard Magento Model functionality 
                        (e.g. direct SQL injections or Custom Code that does not support a Magento Core Models), you can use 
                        predefined <strong>M2E Pro Models</strong> to notify Extension about Product changes.<br/>
                        More detailed information you can find <a href="%url1%" target="_blank">here</a><br/><br/>
    
                        If you use Magmi Import Tool to update Magento Product Information, it is required to set up a predefined 
                        <strong>M2E Pro Plug-in for Magmi Import Tool</strong> to notify Extension about Product Changes.<br/>
                        More detailed information you can find <a href="%url2%" target="_blank">here</a><br/><br/>
    
                        It is <strong>highly recommended</strong> to use one of the options above to decrease the impact on M2E Pro performance.',
                                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'x/xYQVAQ'),
                                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'x/CQ1PAQ')
                            ) ?>
                        </div>

                        <div id="block_notice_walmart_synchronization_stock_level" class="block_notices_module" style="border: 0 !important; margin-bottom: 0 !important;" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                            <?php $inspectorMode = ($this->inspectorMode == 1)?'<span style="color: green"> (enabled) </span>':''; ?>
                            <?php echo Mage::helper('M2ePro')->__('
                                Alternatively, you can enable
                                <a target="_blank" href="%url%#magento_block_configuration_settings_advanced">\'Track Direct Database Changes\'</a>
                                %mode_status% to detect Product changes.<br/><br/>
        
                                <strong>Important note:</strong> the tracking of direct Database changes is resource-consuming and may affect the performance 
                                of your Magento Site and Synchronization with Channels. Set \'Yes\' only in case of extreme necessity 
                                when the use of other predefined M2E Pro Models is impossible for some reasons.',
                                Mage::helper('M2ePro/View_Configuration')->getSettingsUrl(),
                                $inspectorMode
                            ) ?>
                        </div>

                    </div>
                </div>

            </div>

        </div>

        <div id="walmart_revise_all_confirm_popup" style="display: none;">
            <div style="margin: 17px 0">

                <?php echo Mage::helper('M2ePro')->__(
                    'Click \'Confirm\' and Revise will be performed by the Inventory Synchronization, 100 Items per a cycle.'
                ); ?>

            </div>

            <div class="clear"></div>

            <div class="right">
                <a href="javascript:void(0);" onclick="Windows.getFocusedWindow().close()"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->getChildHtml('revise_all_confirm_popup_ok_button'); ?>
            </div>

            <div class="clear"></div>

        </div>

        <?php if ($this->isShowReviseAll()) { ?>
            <script type="text/javascript">

                Event.observe(window, 'load', function() {
                    setTimeout(function() {
                        SynchronizationHandlerObj.initReviseAllInfo(
                            <?php echo json_encode($this->reviseAllInProcessingState) ?>,
                            '<?php echo $this->reviseAllStartDate ?>',
                            '<?php echo $this->reviseAllEndDate ?>',
                            '<?php echo Ess_M2ePro_Helper_Component_Walmart::NICK ?>'
                        );
                    }, 400);
                });

            </script>
        <?php } ?>

    </form>