<div class="errors_summary_title">
    <?php echo Mage::helper('M2ePro')->__('Errors Summary'); ?>
    <a href="javascript:void(0);" onclick="$('listing_container_errors_summary').hide();" title="<?php echo Mage::helper('M2ePro')->__('Close'); ?>">
        <span class="errors_summary_close">&times;</span>
    </a>
</div>

<div class="errors_summary_content">

    <?php foreach($this->errors as $error) { ?>

        <div class="errors_summary_line">
            <div class="errors_summary_type">
                <?php if ((int)$error['count_products'] == 0) { ?>
                    <?php echo Mage::helper('M2ePro')->__('Global'); ?>
                <?php } else { ?>
                    <?php echo (int)$error['count_products']; ?>
                    <?php echo Mage::helper('M2ePro')->__('Product(s)'); ?>
                <?php } ?>
            </div>
            <div class="errors_summary_text">
                <?php echo $error['description']; ?>
            </div>
        </div>

    <?php } ?>

</div>