<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Log_Listing_AbstractView */

$headerText = $this->getHeaderText();

?>

<?php if (!empty($headerText)): ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php endif; ?>
<div class="filter_block">
    <?php echo $this->getFiltersHtml() ?>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>