<div id="block_notice_buy_template_newProduct" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('New SKU Policy'); ?>">
    <?php
    echo Mage::helper('M2ePro')->__('These type of Policies is used for creation of new Products on Rakuten.com.
        <ul class="list">
        <li>to create a new Policy, click on <i>Add New SKU Policy</i>;</li>
        <li>to assign one of the existing Policies to Products click on <i>Assing To This Policy</i> link.</li>
        </ul>
        <b>Note:</b> Attribute Sets of New ASIN/ISBN Policy must include all Attribute Sets of current M2E Pro Listing to be assigned.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/_IsVAQ')
    ); ?>
</div>