<div id="block_notice_ebay_category_chooser_attributes_type" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php echo Mage::helper('M2ePro')->__('The only common (presented in all Attribute sets) "Text Field" or "Dropdown" Attributes available for selection.') ?>
</div>
<div id="chooser_attributes">
    <table id="chooser_attributes_table">
        <thead>
            <td width="225px"></td>
            <td width="115px"></td>
            <td width="225px"></td>
            <td width="105px"></td>
        </thead>
    </table>
</div>