<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Category_Chooser_Tabs_Attribute */

?>

<div id="block_notice_ebay_category_chooser_attributes_type" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php echo Mage::helper('M2ePro')->__('The only common (presented in all Attribute sets) "Text Field" or "Dropdown" Attributes available for selection.') ?>
</div>
<div id="chooser_attributes">
    <table id="chooser_attributes_table">
        <thead>
            <tr>
                <td width="225px"></td>
                <td width="115px"></td>
                <td width="225px"></td>
                <td width="105px"></td>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>