<div id="chooser_search_input_container">
    <input id="query" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter keyword(s) or Category ID...'); ?>" onkeypress="EbayListingCategoryChooserHandlerObj.keyPressQuery(event)"><button onclick="EbayListingCategoryChooserHandlerObj.search()"><?php echo Mage::helper('M2ePro')->__('Search'); ?></button>&nbsp;&nbsp;&nbsp;&nbsp;<button onclick="EbayListingCategoryChooserHandlerObj.searchReset()"><?php echo Mage::helper('M2ePro')->__('Reset'); ?></button>
</div>
<div id="chooser_search_results"></div>