<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Category_Chooser_Tabs_Search */

?>

<div id="chooser_search_input_container">
    <input id="query" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter keyword(s) or Category ID...'); ?>" onkeypress="EbayListingCategoryChooserHandlerObj.keyPressQuery(event)"><button onclick="EbayListingCategoryChooserHandlerObj.search()"><?php echo Mage::helper('M2ePro')->__('Search'); ?></button>&nbsp;&nbsp;&nbsp;&nbsp;<button onclick="EbayListingCategoryChooserHandlerObj.searchReset()"><?php echo Mage::helper('M2ePro')->__('Reset'); ?></button>
</div>
<div id="chooser_search_results"></div>