<div id="block_notice_ebay_listing" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('M2E Pro Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows the M2E Pro Listings you\'ve set up.<br/><br/>
        Click a line in the Table below to manage the Products current Listed using that M2E Pro Listing.
        Otherwise use the Dropdown Menu in the <b>Actions</b> Column for more Options.<br/><br/>
        To clear the Logs or delete more than one M2E Pro Listing at a time, use the <b>Actions</b> Dropdown at the very top of the Table.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/agAJAQ')
    ); ?>
</div>