<style type="text/css">
    .massaction-checkbox {
        display: block;
        margin: 5px auto 0;
        width: 50px;
    }

    .massaction td {
        padding: 1px 8px !important;
    }

    .grid th, .grid td {
        padding: 2px 4px!important;
    }

    #pickupStore-grid-popup-stores {
        padding: 15px 0 0;
        height: 380px;
        overflow-y: auto;
    }

    .button-area {
        float: right;
        padding: 10px 0;
    }
</style>
<div id="pickupStore-grid-popup-stores">
    <?php echo $this->getChildHtml('stores'); ?>
</div>

<script type="M2ePro/template" id="button-template">
    <div class="button-area">
        <?php echo $this->getChildHtml('back'); ?>
        &nbsp;
        <?php echo $this->getChildHtml('done'); ?>
    </div>
    <div style="clear: both"></div>
</script>