<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Host'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationHost; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Domain'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationDomain; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('IP'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationIp; ?>
        </td>
    </tr>

</table>