<div id="block_notice_walmart_template_synchronization_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('List Rules'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    Synchronization Policy includes rules and conditions based on which M2E Pro automatically transfers your Magento data to the Channel. You may configure the List, Revise, Relist and Stop Rules.<br><br>

    Enable the List Action and define the List Conditions based on which M2E Pro will automatically list the Not Listed Items on Walmart.
    If the initial list fails, the Module will reattempt the Item listing after the Product Status, Stock Availability or Quantity are changed.<br><br>

    <strong>Note:</strong> Inventory Synchronization must be enabled under the <i>%navigation%</i>. Otherwise, Synchronization Policy Rules will not take effect.<br><br>

    <strong>Note:</strong> Synchronization Policy is required when you create a new offer on Walmart.<br><br>
    
    The detailed information can be found <a href="%url%" target="_blank">here</a>.',

    Mage::helper('M2ePro/View_Walmart')->getPageNavigationPath('configuration', 'Synchronization'),
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/L4taAQ')
    ); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();
    $defaults = array(
        'list_mode'           => Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_YES,
        'list_status_enabled' => Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_STATUS_ENABLED_YES,
        'list_is_in_stock'    => Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_IS_IN_STOCK_YES,

        'list_qty_magento'           => Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE,
        'list_qty_magento_value'     => '1',
        'list_qty_magento_value_max' => '10',

        'list_qty_calculated'           => Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE,
        'list_qty_calculated_value'     => '1',
        'list_qty_calculated_value_max' => '10'
    );
    $formData = array_merge($defaults, $formData);

    $isEdit = (bool)$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    Event.observe(window, 'load', function() {
        $('list_mode').observe('change', WalmartTemplateSynchronizationHandlerObj.listMode_change);
        $('list_qty_magento').observe('change', WalmartTemplateSynchronizationHandlerObj.listQty_change);
        $('list_qty_calculated').observe('change', WalmartTemplateSynchronizationHandlerObj.listQty_change);
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_walmart_template_synchronization_general_list">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('List Action'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('List Action'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="list_mode" name="list_mode" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_NONE; ?>" <?php if ($formData['list_mode'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_YES; ?>" <?php if ($formData['list_mode'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enable to automatically list the Not Listed Item(s) when the List Conditions are met.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_walmart_template_synchronization_list_rules" <?php if ($formData['list_mode'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('List Conditions'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Product Status'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="list_status_enabled" name="list_status_enabled" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_STATUS_ENABLED_NONE; ?>" <?php if ($formData['list_status_enabled'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_STATUS_ENABLED_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_STATUS_ENABLED_YES; ?>" <?php if ($formData['list_status_enabled'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_STATUS_ENABLED_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Magento Product Status at which the Item(s) have to be listed.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stock Availability'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="list_is_in_stock" name="list_is_in_stock" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_IS_IN_STOCK_NONE; ?>" <?php if ($formData['list_is_in_stock'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_IS_IN_STOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_IS_IN_STOCK_YES; ?>" <?php if ($formData['list_is_in_stock'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_IS_IN_STOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('In Stock'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Magento Stock Availability at which the Item(s) have to be listed.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Magento Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="list_qty_magento" name="list_qty_magento" class="required-entry" qty_type="magento">
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE; ?>" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_LESS; ?>" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_MORE; ?>" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN; ?>" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Magento Product Quantity at which the Item(s) have to be listed.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="list_qty_magento_value_container" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="list_qty_magento_value">
                            <span id="list_qty_magento_item" <?php if ($formData['list_qty_magento'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="list_qty_magento_item_min" <?php if ($formData['list_qty_magento'] != Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="list_qty_magento_value" name="list_qty_magento_value" value="<?php echo $this->escapeHtml($formData['list_qty_magento_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="list_qty_magento_value_max_container" <?php if ($formData['list_qty_magento'] != Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="list_qty_magento_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="list_qty_magento_value_max" name="list_qty_magento_value_max" value="<?php echo $this->escapeHtml($formData['list_qty_magento_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Calculated Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="list_qty_calculated" name="list_qty_calculated" class="required-entry" qty_type="calculated">
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE; ?>" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_LESS; ?>" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_MORE; ?>" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN; ?>" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Item Quantity calculated based on the Selling Policy settings at which the Item(s) have to be listed.<br>
                                <strong>Note:</strong> This option will be ignored for Magento Variational Product listed as Walmart Variant Group.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="list_qty_calculated_value_container" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="list_qty_calculated_value">
                            <span id="list_qty_calculated_item" <?php if ($formData['list_qty_calculated'] == Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="list_qty_calculated_item_min" <?php if ($formData['list_qty_calculated'] != Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="list_qty_calculated_value" name="list_qty_calculated_value" value="<?php echo $this->escapeHtml($formData['list_qty_calculated_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="list_qty_calculated_value_max_container" <?php if ($formData['list_qty_calculated'] != Ess_M2ePro_Model_Walmart_Template_Synchronization::LIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="list_qty_calculated_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="list_qty_calculated_value_max" name="list_qty_calculated_value_max" value="<?php echo $this->escapeHtml($formData['list_qty_calculated_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>