<?php
    /** @var Ess_M2ePro_Block_Adminhtml_Common_Amazon_Template_Description_Category_Chooser_Tabs_Browse $this */
?>

<style>
    .category-children-block {
        display: inline-block;
        margin-left: 10px;
    }
</style>

<script type="text/javascript">

    AmazonTemplateDescriptionCategoryChooserHandlerObj.renderTopLevelCategories('chooser_browser');

</script>

<div id="block_notice_amazon_template_description_category_chooser_browser_refresh" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php echo Mage::helper('M2ePro')->__('If you cannot find necessary Category, try to <a href="javascript:void(0)" onclick="AmazonTemplateDescriptionCategoryChooserHandlerObj.refreshAmazonCategories()">Update Amazon Marketplaces data</a>.') ?>
</div>

<div id="chooser_browser"></div>