<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Listing_View_Sellercentral_Repricing_RegularPricePopup */

?>

<div id="regular_price_popup">
    <div style="padding: 10px;">
        <?php echo Mage::helper('M2ePro')->__('
            Some of the selected Products will not be added to Amazon Repricing Tool since B2C Price is not specified for them. Only Products with B2C Price can be repriced.
        '); ?>

        <div class="clear"></div>

        <div style="text-align: right">
            <a href="javascript:"
               onclick="Windows.getFocusedWindow().close();"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <?php echo $this->getChildHtml('yes_btn'); ?>
        </div>
    </div>

</div>