<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Template_SellingFormat_TaxCodes */

?>

<style>
    #taxCodesGrid {
        padding-top: 10px;
    }
    #taxCodesGrid_table .a-left, #taxCodesGrid_table .no-link {
        padding: 5px;
    }
    #taxCodesGrid .filter-actions.a-right {
        padding-right: 10px
    }
    .dialog.popup-window {
        width: 950px;
    }
</style>

<div class="hor-scroll" style="height: 450px">
    <div id="tax_codes" >
        <?php echo $this->getChildHtml('tax_codes_grid'); ?>
    </div>
</div>

<div style="float: right; margin-top: 20px; margin-bottom: 12px;">
    <?php echo $this->getChildHtml('tax_codes_close_btn'); ?>
</div>