<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Amazon Channel'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <div>
       <?php echo Mage::helper('M2ePro')->__('Setting up Settings to be able to sell on <strong>Amazon</strong>.'); ?>
    </div>

    <div class="step_container_buttons">
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>
</div>
