<div id="block_notice_amazon_accounts_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Fill in the Title, choose the Marketplace you want to work with and click the <i class="underline">Get Access Data</i> link.
        <br/>You will be redirected to the Amazon Website.<br/><br/>
    <b>Note:</b> To be eligible to sell on Amazon Sellers must have at least one of the following: a non-individual <i>Selling on Amazon Account</i>,
    an <i>Amazon WebStore Account</i>, a <i>Checkout by Amazon Account</i>, or an <i>Amazon Product Ads Account</i>.<br/>
    If you are an individual Seller you have to upgrade to a Pro Merchant Seller Account from the Amazon Services Selling on Amazon Page.
        <br/>
        <br/>Sign-in and complete steps of getting access for each Marketplace:
        <ul class="list">
            <li>Select - <i>\'I want to use an application to access my Amazon Seller Account with MWS.\'</i></li>
            <li>Fill in Application Name and Application\'s Developer Account Number, which you can find in the Marketplaces Section on the current Page.</li>
            <li>Accept the Amazon MWS License Agreement.</li>
            <li>Copy generated "Merchant ID" / "MWS Auth Token" and paste it in the corresponding fields of the current Page.</li>
        </ul>
        Continue working with 3rd Party Listings and Orders Settings Tabs.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/qoIVAQ')
    ); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $defaults = array(
        'title'          => '',
        'marketplace_id' => 0,
        'merchant_id'    => '',
        'token'          => ''
    );

    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Amazon_Account'); ?>,
        'Ess_M2ePro_Model_Amazon_Account'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Amazon'); ?>,
        'Ess_M2ePro_Helper_Component_Amazon'
    );

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_common_amazon_account')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_common_amazon_account/save', array('id' => $this->getRequest()->getParam('id'))),
        'deleteAction' => $this->getUrl('M2ePro/adminhtml_common_amazon_account/delete', array('id' => $this->getRequest()->getParam('id')))
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.' => Mage::helper('M2ePro')->__('Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.'),
        'Unlink Repricing Tool' => Mage::helper('M2ePro')->__('Unlink From Repricing Tool'),
        'Please enter correct value.' => Mage::helper('M2ePro')->__('Please enter correct value.'),
        'Coefficient is not valid.' => Mage::helper('M2ePro')->__('Coefficient is not valid.'),
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        AmazonAccountHandlerObj = new CommonAmazonAccountHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        <?php if ($isEdit) { ?>
            AmazonAccountHandlerObj.showGetAccessData(<?php echo $formData['marketplace_id']; ?>);
        <?php } ?>

        var urlHash = location.hash.substr(1);
        if (urlHash != '') {
            setTimeout(function() {
                amazonAccountEditTabsJsTabs.tabs.each(function(tab){
                    if (tab.name == urlHash) {
                        amazonAccountEditTabsJsTabs.showTabContent(tab);
                    }
                });
                location.hash = '';
            }, 100);
        }
    });
    //-----------------------------

</script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'The specified Title is already used for other Account. Account Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Account. Account Title must be unique.'),
        'You must choose Marketplace first.' => Mage::helper('M2ePro')->__('You must choose Marketplace first.'),
        'M2E Pro was not able to get access to the Amazon Account. Please, make sure, that you choose correct Option on MWS Authorization Page and enter correct Merchant ID.' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Amazon Account. Please, make sure, that you choose correct Option on MWS Authorization Page and enter correct Merchant ID / MWS Auth Token'),
        'M2E Pro was not able to get access to the Amazon Account. Reason: %error_message%' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Amazon Account. Reason: %error_message%')
    )); ?>);

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_amazon_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or Identifier of Amazon Account for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    <div class="locked_block">

        <div class="locked_wrapper">
            <div><?php echo Mage::helper('M2ePro')->__('Synchronizing Now') ?></div>
        </div>
<?php } ?>

<div class="entry-edit" id="magento_block_amazon_accounts_marketplaces_access" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Access Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">

                        <select id="marketplace_id" name="marketplace_id" <?php if ($isEdit) { ?>disabled="disabled"<?php } ?> onchange="AmazonAccountHandlerObj.changeMarketplace(this.value);" class="required-entry">

                            <?php if (!$isEdit) { ?>
                                <option style="display:none;"></option>
                            <?php } ?>

                            <?php foreach ($this->marketplaces as $marketplaceRow) { ?>
                                <option value="<?php echo $marketplaceRow['id']; ?>" <?php if ($formData['marketplace_id'] == $marketplaceRow['id']) { ?>selected="selected"<?php } ?>>
                                    <?php echo Mage::helper('M2ePro')->__($marketplaceRow['title']); ?>
                                </option>
                            <?php } ?>

                        </select>

                        <?php if ($isEdit) : ?>
                            <input type="hidden" name="marketplace_id" value="<?php echo $formData['marketplace_id']; ?>" />
                            <input type="hidden" name="merchant_id" value="<?php echo $formData['merchant_id']; ?>" />
                            <input type="hidden" name="token" value="<?php echo $formData['token']; ?>" />
                        <?php endif; ?>

                    </td>
                </tr>

                <tr id="marketplaces_application_name_container" style="display:none;">
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Application Name') ?>:</td>
                    <td class="value"><?php echo Mage::helper('M2ePro/Component_Amazon')->getApplicationName(); ?></td>
                </tr>

                <?php foreach ($this->marketplaces as $marketplaceRow) { ?>

                    <tr class="marketplaces_view_element" id="marketplaces_developer_key_container_<?php echo $marketplaceRow['id']; ?>" style="display:none;">
                        <td class="label"><?php echo Mage::helper('M2ePro')->__('Developer Account Number') ?>:</td>
                        <td class="value"><?php echo $marketplaceRow['developer_key'] ?></td>
                    </tr>

                    <tr class="marketplaces_view_element" id="marketplaces_register_url_container_<?php echo $marketplaceRow['id']; ?>" style="display:none;">
                        <td class="label"></td>
                        <td class="value">
                            <a href="<?php echo Mage::helper('M2ePro/Component_Amazon')->getRegisterUrl($marketplaceRow['id']); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get Access Data') ?></a>
                        </td>
                    </tr>

                <?php } ?>

                <tr id="marketplaces_merchant_id_container" <?php if (!$isEdit) echo ' style="display:none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Merchant ID'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="merchant_id" type="text" class="M2ePro-marketplace-merchant input-text" name="merchant_id" <?php if ($isEdit) echo ' value="'.$formData['merchant_id'].'"'; ?> <?php if ($isEdit) echo ' disabled="disabled"'; ?> class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Paste generated Merchant ID from Amazon. (It must look like: A15UFR7CZVW5YA).'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="marketplaces_token_container" <?php if (!$isEdit) echo ' style="display:none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('MWS Auth Token'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="token" type="text" class="M2ePro-marketplace-merchant input-text" name="token" <?php if ($isEdit) echo ' value="'.$formData['token'].'"'; ?> class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Paste generated MWS Auth Token from Amazon. (It must look like: amzn.mws.bna3f75c-a683-49c7-6da0-749y33313dft).'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    </div>
<?php } ?>