<div id="block_notice_amazon_accounts_orders" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php
        $menuSalesPath = Mage::helper('M2ePro/View_Common')->getPageNavigationPath('orders', '', 'amazon');
        $menuSynchronizationPath = Mage::helper('M2ePro/View_Common')->getPageNavigationPath('configuration', 'Synchronization', 'amazon');
        echo Mage::helper('M2ePro')->__('This Tab contains Settings of Amazon Orders, Amazon Customers Import; Magento Orders and Products Creation.<br/><br/>

        If you set <strong>Import Amazon Orders</strong> to <i>Yes</i>, a new Amazon Order will be imported to the System and can be found in (%menu_sales_path%).<br/>
        It is possible to allow auto creation of Magento Orders based on imported Amazon Orders for Products Listed by Other Software.<br/><br/>

        <b>Note:</b> The Product Stock QTY only reduces after Magento Order Creation.<br/>
        These type of Orders can be managed as typical <i class="underline">Magento Orders</i> in (Magento > Sales > Orders).<br/><br/>
        <b>Note:</b> To receive Orders from Amazon, Order Synchronization must be enabled in (%menu_synchronization_path%).<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        $menuSalesPath,
        $menuSynchronizationPath,
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/3oIVAQ')
        );
    ?>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();
    $formData['magento_orders_settings'] = !empty($formData['magento_orders_settings']) ? json_decode($formData['magento_orders_settings'], true) : array();

    $defaults = array(
        'magento_orders_settings' => array(
            'listing' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_YES,
                'store_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_DEFAULT,
                'store_id' => NULL
            ),
            'listing_other' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_YES,
                'product_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IMPORT,
                'product_tax_class_id' => Ess_M2ePro_Model_Magento_Product::TAX_CLASS_ID_NONE,
                'store_id' => NULL,
            ),
            'number' => array(
                'source' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_SOURCE_MAGENTO,
                'prefix' => array(
                    'mode'   => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_NO,
                    'prefix' => '',
                ),
            ),
            'tax' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_MIXED
            ),
            'customer' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_GUEST,
                'id' => NULL,
                'website_id' => NULL,
                'group_id' => NULL,
//                'subscription_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_NEW_SUBSCRIPTION_MODE_NO,
                'notifications' => array(
//                    'customer_created' => false,
                    'invoice_created' => false,
                    'order_created' => false
                ),
                'billing_address_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_BILLING_ADDRESS_MODE_SHIPPING_IF_SAME_CUSTOMER_AND_RECIPIENT
            ),
            'status_mapping' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT,
                'processing' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_PROCESSING,
                'shipped' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_SHIPPED,
            ),
            'qty_reservation' => array(
                'days' => 1
            ),
            'refund_and_cancellation' => array(
                'refund_mode' => 1,
            ),
            'fba' => array(
                'mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_YES,
                'stock_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_STOCK_MODE_NO
            ),
            'invoice_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_INVOICE_MODE_YES,
            'shipment_mode' => Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_SHIPMENT_MODE_YES
        )
    );

    $isEdit = !!$this->getRequest()->getParam('id');

    $isEdit && $defaults['magento_orders_settings']['refund_and_cancellation']['refund_mode'] = 0;

    $formData = Mage::helper('M2ePro')->arrayReplaceRecursive($defaults, $formData);

?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'No Customer entry is found for specified ID.' => Mage::helper('M2ePro')->__('No Customer entry is found for specified ID.'),
        'Prefix length should not be greater than 5 characters.' => Mage::helper('M2ePro')->__('Prefix length should not be greater than 5 characters.')
    )); ?>);

    M2ePro.formData.magento_orders_listings_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing']['mode']); ?>';
    M2ePro.formData.magento_orders_listings_store_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing']['store_mode']); ?>';
    M2ePro.formData.magento_orders_listings_store_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing']['store_id']); ?>';

    M2ePro.formData.magento_orders_listings_other_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing_other']['mode']); ?>';
    M2ePro.formData.magento_orders_listings_other_store_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing_other']['store_id']); ?>';
    M2ePro.formData.magento_orders_listings_other_product_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['listing_other']['product_mode']); ?>';

    M2ePro.formData.magento_orders_customer_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['customer']['mode']); ?>';
    M2ePro.formData.magento_orders_customer_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['customer']['id']); ?>';
    M2ePro.formData.magento_orders_customer_new_website_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['customer']['website_id']); ?>';
    M2ePro.formData.magento_orders_customer_new_group_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['customer']['group_id']); ?>';
<!--    M2ePro.formData.magento_orders_customer_new_newsletter_mode = '--><?php //echo Mage::helper('M2ePro')->escapeJs($formData['magento_orders_settings']['customer']['subscription_mode']); ?><!--';-->

    Event.observe(window, 'load', function() {

        setTimeout(function() {
            $('magento_orders_listings_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersListingsModeChange);
            $('magento_orders_listings_store_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersListingsStoreModeChange);

            $('magento_orders_listings_other_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersListingsOtherModeChange);
            $('magento_orders_listings_other_product_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersListingsOtherProductModeChange);

            $('magento_orders_number_source').observe('change', AmazonAccountHandlerObj.magentoOrdersNumberSourceChange);
            $('magento_orders_number_prefix_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersNumberPrefixModeChange);
            $('magento_orders_number_prefix_prefix').observe('keyup', AmazonAccountHandlerObj.magentoOrdersNumberPrefixPrefixChange);
            AmazonAccountHandlerObj.renderOrderNumberExample();

            $('magento_orders_fba_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersFbaModeChange);

            $('magento_orders_customer_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersCustomerModeChange);
            $('magento_orders_status_mapping_mode').observe('change', AmazonAccountHandlerObj.magentoOrdersStatusMappingModeChange);
        }, 350);
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_listings">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Product Is Listed By M2E Pro'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_listings_mode"><?php echo Mage::helper('M2ePro')->__('Create Order in Magento'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="magento_orders_listings_mode" name="magento_orders_settings[listing][mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO; ?>" <?php if ($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_YES; ?>" <?php if ($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Whether an Order has to be created in Magento if a sold Product belongs to M2E Pro Listings.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_listings_store_mode_container" <?php if($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_listings_store_mode"><?php echo Mage::helper('M2ePro')->__('Store View Source'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="magento_orders_listings_store_mode" name="magento_orders_settings[listing][store_mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_DEFAULT; ?>" <?php if ($formData['magento_orders_settings']['listing']['store_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_DEFAULT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Use Store View from Listing'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_CUSTOM; ?>" <?php if ($formData['magento_orders_settings']['listing']['store_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_CUSTOM) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Choose Store View Manually'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If Store View must be automatically taken from the Listing or manually chosen from available Store View values.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_listings_store_id_container" <?php if($formData['magento_orders_settings']['listing']['store_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_STORE_MODE_DEFAULT) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Store View'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <?php echo $this->getChildHtml('magento_orders_listings_store_id'); ?>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Store in which Orders will be placed.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_listings_other">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Product Is Listed By Any Other Software'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_listings_other_mode"><?php echo Mage::helper('M2ePro')->__('Create Order in Magento'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="magento_orders_listings_other_mode" name="magento_orders_settings[listing_other][mode]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO; ?>" <?php if ($formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_YES; ?>" <?php if ($formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Whether an Order has to be created in Magento if a sold Product does not belong to M2E Pro Listings.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_listings_other_store_id_container" <?php if($formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Store View'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <?php echo $this->getChildHtml('magento_orders_listings_other_store_id'); ?>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Store in which Orders will be placed.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_listings_other_product_mode_container" <?php if($formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_listings_other_product_mode"><?php echo Mage::helper('M2ePro')->__('Product Not Found'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="magento_orders_listings_other_product_mode" name="magento_orders_settings[listing_other][product_mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IGNORE; ?>" <?php if ($formData['magento_orders_settings']['listing_other']['product_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IGNORE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Create Order'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IMPORT; ?>" <?php if ($formData['magento_orders_settings']['listing_other']['product_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IMPORT) echo ' selected="selected"';?>><?php echo Mage::helper('M2ePro')->__('Create Product and Order'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('What has to be done if a Listed Product does not exist in Magento.'); ?></span><br/>
                            <span id="magento_orders_listings_other_product_mode_note" <?php if ($formData['magento_orders_settings']['listing_other']['product_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IGNORE) echo 'style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('<b>Note:</b> Only Simple Products without Variations can be created in Magento. If there is a Product with Variations on Amazon, M2E Pro creates different Simple Products for each Variation.') ?></span>
                        </p>
                    </td>
                </tr>

                <?php $canShowBlock = $formData['magento_orders_settings']['listing_other']['product_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_PRODUCT_MODE_IMPORT; ?>
                <tr id="magento_orders_listings_other_product_tax_class_id_container" <?php if (!$canShowBlock): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="magento_orders_listings_other_product_tax_class_id"><?php echo Mage::helper('M2ePro')->__('Product Tax Class') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="magento_orders_listings_other_product_tax_class_id" name="magento_orders_settings[listing_other][product_tax_class_id]" class="M2ePro-required-when-visible">
                            <?php foreach ($this->productTaxClasses as $taxClass): ?>
                                <option value="<?php echo (int)$taxClass['value'] ?>" <?php if ($formData['magento_orders_settings']['listing_other']['product_tax_class_id'] == $taxClass['value']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($taxClass['label']) ?></option>
                            <?php endforeach; ?>
                        </select>
                        <p class="note">
                            <?php echo Mage::helper('M2ePro')->__('Tax Class which will be used for Products created by M2E Pro.'); ?>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_number" <?php if(($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Magento Order Number'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_amazon_accounts_orders_number" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Number Prefix'); ?>">
                <?php echo Mage::helper('M2ePro')->__('Sets Magento Order number basing on the Settings below'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_number_source"><?php echo Mage::helper('M2ePro')->__('Source'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_number_source" name="magento_orders_settings[number][source]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_SOURCE_MAGENTO; ?>" <?php if ($formData['magento_orders_settings']['number']['source'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_SOURCE_MAGENTO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Magento'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_SOURCE_CHANNEL; ?>" <?php if ($formData['magento_orders_settings']['number']['source'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_SOURCE_CHANNEL) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Amazon'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If source is set to Magento, Magento Order numbers are created basing on your Magento Settings. If source is set to Amazon, Magento Order numbers are the same as Amazon Order numbers.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="magento_orders_number_prefix_mode"><?php echo Mage::helper('M2ePro')->__('Use Prefix'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_number_prefix_mode" name="magento_orders_settings[number][prefix][mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_NO; ?>" <?php if ($formData['magento_orders_settings']['number']['prefix']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_YES; ?>" <?php if ($formData['magento_orders_settings']['number']['prefix']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose to set the prefix before Magento Order number.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_number_prefix_container" <?php if($formData['magento_orders_settings']['number']['prefix']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_NUMBER_PREFIX_MODE_NO) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_customer_id"><?php echo Mage::helper('M2ePro')->__('Prefix'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="magento_orders_number_prefix_prefix" maxlength="5" name="magento_orders_settings[number][prefix][prefix]" value="<?php echo $this->escapeHtml($formData['magento_orders_settings']['number']['prefix']['prefix']); ?>" type="text" class="M2ePro-required-when-visible M2ePro-account-order-number-prefix input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enter the prefix to be set before Magento Order number.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input type="hidden" id="sample_magento_order_id" value="<?php echo Mage::helper('M2ePro/Magento')->getNextMagentoOrderId(); ?>" />
                        <input type="hidden" id="sample_amazon_order_id" value="141-4423723-6495633" />

                        <p class="note note-no-tool-tip">
                            <?php echo Mage::helper('M2ePro')->__('e.g.'); ?> <strong><span id="order_number_example_container"></span></strong>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_rules" <?php if (($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity Reservation'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <div id="block_notice_amazon_accounts_magento_orders_rules" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('QTY Reservation'); ?>">
                <?php echo Mage::helper('M2ePro')->__('Use the Reserve Quantity Option to prevent the Item being sold, before Magento Order created (as the Product Stock QTY only reduces after Magento Order Creation). It removes Items from Magento Stock at once Amazon Order comes from Amazon.
                Reserve QTY will be used when Magento Order is created or released when the term of QTY reservation has expired.
                '); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="magento_orders_qty_reservation_days_container">
                    <td class="label">
                        <label for="magento_orders_qty_reservation_days"><?php echo Mage::helper('M2ePro')->__('Reserve Quantity') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="magento_orders_settings[qty_reservation][days]" id="magento_orders_qty_reservation_days">
                            <?php for ($day = 1; $day <= 14; $day++): ?>
                                <option value="<?php echo (int)$day ?>" <?php if ($formData['magento_orders_settings']['qty_reservation']['days'] == $day): ?>selected="selected"<?php endif; ?>>
                                    <?php if ($day == 1): ?>
                                        <?php echo Mage::helper('M2ePro')->__('For %number% day', $day) ?>
                                    <?php else: ?>
                                        <?php echo Mage::helper('M2ePro')->__('For %amount% days', $day) ?>
                                    <?php endif; ?>
                                </option>
                            <?php endfor; ?>
                        </select>
                            <p class="note">
                                <?php echo Mage::helper('M2ePro')->__('For how many days reserve Quantity has to be kept while Magento Order is not created.') ?>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_refund_and_cancellation" <?php if (($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Refund & Cancellation'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <div id="block_notice_amazon_accounts_magento_orders_refund" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Refund & Cancellation'); ?>">
                <?php echo Mage::helper('M2ePro')->__('
                Enable an option Cancellation & Refund if Credit Memo is Created to run automatic Cancellation of Amazon Orders or automatic Refund of Items associated to Amazon Orders at the moment of Credit Memos creation in Magento Orders that were created by M2E Pro. <br/><br/>

                In case Amazon Order has Status Unshipped and you created a Credit Memo for associated Magento Order which include all bought Items, Amazon Order Cancellation will be run automatically. <br/><br/>

                Automatic Refund of bought Items associated to Amazon Order is available in case Amazon Order has Status Shipped. Refund action will be run only for those Items for which Credit Memos were created.'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="magento_orders_refund_container">
                    <td class="label">
                        <label for="magento_orders_refund"><?php echo Mage::helper('M2ePro')->__('Cancel or Refund if Credit Memo is Created') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="magento_orders_settings[refund_and_cancellation][refund_mode]" id="magento_orders_refund">
                            <option value="0" <?php if (!$formData['magento_orders_settings']['refund_and_cancellation']['refund_mode']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->__('No') ?></option>
                            <option value="1" <?php if ($formData['magento_orders_settings']['refund_and_cancellation']['refund_mode']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes') ?></option>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php $canShowBlock = (($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_YES || $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_YES)); ?>
<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_fba" <?php if (!$canShowBlock): ?>style="display: none;"<?php endif; ?>>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('FBA Orders Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_amazon_accounts_orders_fba" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('FBA Orders Settings'); ?>">
                <?php echo Mage::helper('M2ePro')->__('In this Block you can manage Stock Inventory of Products fulfilled by Amazon  (FBA Orders).<br/>
                <ul class=list>

                <li><b>Yes</b> - after Magento Order Creation of FBA Order, Quantity of Product reduces in Magento.</li>
                <li><b>No</b> - Magento Order Creation of FBA Order does not affect Quantity of Magento Product.</li>
                </ul>'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_fba_mode"><?php echo Mage::helper('M2ePro')->__('Create Order in Magento'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_fba_mode" name="magento_orders_settings[fba][mode]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_NO; ?>" <?php if ($formData['magento_orders_settings']['fba']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_YES; ?>" <?php if ($formData['magento_orders_settings']['fba']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Whether an Order has to be created in Magento if a sold Product is fulfilled by Amazon.'); ?></span>
                        </p>
                    </td>
                </tr>

                <?php $canShowBlock = $formData['magento_orders_settings']['fba']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_MODE_YES; ?>
                <tr id="magento_orders_fba_stock_mode_container" <?php if (!$canShowBlock): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="magento_orders_fba_stock_mode"><?php echo Mage::helper('M2ePro')->__('Manage Stock'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_fba_stock_mode" name="magento_orders_settings[fba][stock_mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_STOCK_MODE_NO; ?>" <?php if ($formData['magento_orders_settings']['fba']['stock_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_STOCK_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_STOCK_MODE_YES; ?>" <?php if ($formData['magento_orders_settings']['fba']['stock_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_FBA_STOCK_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i>, after Magento Order Creation QTY of Magento Product reduces.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_customer" <?php if(($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Customer Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_customer_mode"><?php echo Mage::helper('M2ePro')->__('Customer'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_customer_mode" name="magento_orders_settings[customer][mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_GUEST; ?>" <?php if ($formData['magento_orders_settings']['customer']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_GUEST) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Guest Account'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_PREDEFINED; ?>" <?php if ($formData['magento_orders_settings']['customer']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_PREDEFINED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Predefined Customer'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_NEW; ?>" <?php if ($formData['magento_orders_settings']['customer']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Create New'); ?></option>
                        </select>
                        <p class="note note-no-tool-tip">
                            <span><?php echo Mage::helper('M2ePro')->__('Customer for which Magento Orders will be created.'); ?></span>
                        </p>
                    </td>
                    <td class="value" style="display: none">
                        <p class="note"">
                            <span>
                                <?php echo Mage::helper('M2ePro')->__('There are several ways to specify a Customer for which Magento Orders will be created: <br/><br/>
                                    <b>Guest Account</b> - the System does not require a Customer Account to be created. Default Guest Account will be defined as a Customer. <br/>
                                    <b>Note:</b> The Guest Checkout Option must be enabled in Magento. (<i>Yes</i> must be chosen in the Allow Guest Checkout Option in Magento > System > Configuration > Sales > Checkout Tab). <br/>
                                    <b>Predefined Customer</b> - the System uses one predefined Customer for all Amazon Orders related to this Account. You will be required
                                    to provide an ID of the existing Customer, which you can find in Magento > Customers > Manage Customers Table. <br/>
                                    <b>Create New</b> - a new Customer will be created in Magento, using Amazon Customer data of Amazon Order. <br/>
                                    <b>Note:</b> A unique Customer Identifier is his e-mail address. If the one already exists among Magento Customers e-mails,
                                    the System uses this Customer as owner of Order and links Order to him. A new Customer will not be created. <br/>
                                '); ?>
                            </span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_customer_id_container" <?php if($formData['magento_orders_settings']['customer']['mode'] != Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_PREDEFINED) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_customer_id"><?php echo Mage::helper('M2ePro')->__('Customer ID'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="magento_orders_customer_id" name="magento_orders_settings[customer][id]" value="<?php echo $this->escapeHtml($formData['magento_orders_settings']['customer']['id']); ?>" type="text" class="M2ePro-required-when-visible validate-digits M2ePro-account-customer-id input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enter Magento Customer ID.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_customer_new_website_id_container" <?php if($formData['magento_orders_settings']['customer']['mode'] != Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_NEW) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_customer_new_website_id"><?php echo Mage::helper('M2ePro')->__('Associate to Website'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_customer_new_website_id" name="magento_orders_settings[customer][website_id]" class="M2ePro-required-when-visible">
                            <option value="" <?php if ($formData['magento_orders_settings']['customer']['website_id'] == '') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('-- Please Select --'); ?></option>
                            <?php foreach($this->websites as $website) { ?>
                                <option value="<?php echo $website['website_id']; ?>" <?php if ($formData['magento_orders_settings']['customer']['website_id'] == $website['website_id']) echo ' selected="selected"'; ?>><?php echo $website['name']; ?></option>
                            <?php } ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Website in which a Customer Account will be created.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_customer_new_group_id_container" <?php if($formData['magento_orders_settings']['customer']['mode'] != Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_NEW) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_customer_new_group_id"><?php echo Mage::helper('M2ePro')->__('Customer Group'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_customer_new_group_id" name="magento_orders_settings[customer][group_id]" class="M2ePro-required-when-visible">
                            <option value="" <?php if ($formData['magento_orders_settings']['customer']['group_id'] == '') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('-- Please Select --'); ?></option>
                            <?php foreach($this->groups as $group) { ?>
                                <option value="<?php echo $group['customer_group_id']; ?>" <?php if ($formData['magento_orders_settings']['customer']['group_id'] == $group['customer_group_id']) echo ' selected="selected"'; ?>><?php echo $group['customer_group_code']; ?></option>
                            <?php } ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Customer Group to which a Customer will be assigned.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="magento_orders_customer_new_notifications_container" <?php if($formData['magento_orders_settings']['customer']['mode'] != Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_CUSTOMER_MODE_NEW) echo 'style="display: none;"'; ?>>
                    <td class="label">
                        <label for="magento_orders_customer_new_notifications"><?php echo Mage::helper('M2ePro')->__('Send Emails When The Following Is Created'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_customer_new_notifications" name="magento_orders_settings[customer][notifications][]" multiple="multiple">
<!--                            <option value="customer_created" --><?php //if ($formData['magento_orders_settings']['customer']['notifications']['customer_created']) echo ' selected="selected"'; ?><!-->--><?php //echo Mage::helper('M2ePro')->__('Customer Account'); ?><!--</option>-->
                            <option value="order_created" <?php if ($formData['magento_orders_settings']['customer']['notifications']['order_created']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Magento Order'); ?></option>
                            <option value="invoice_created" <?php if ($formData['magento_orders_settings']['customer']['notifications']['invoice_created']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Invoice'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Necessary emails will be sent according to Magento Settings in Magento > System > Configuration > Sales Emails.<br/>Hold Ctrl Button, to choose more, than one Option.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_customer_billing_address_mode"><?php echo Mage::helper('M2ePro')->__('Billing Address Usage'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_customer_billing_address_mode" name="magento_orders_settings[customer][billing_address_mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_BILLING_ADDRESS_MODE_SHIPPING; ?>" <?php if ($formData['magento_orders_settings']['customer']['billing_address_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_BILLING_ADDRESS_MODE_SHIPPING) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Always'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_BILLING_ADDRESS_MODE_SHIPPING_IF_SAME_CUSTOMER_AND_RECIPIENT; ?>" <?php if ($formData['magento_orders_settings']['customer']['billing_address_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_BILLING_ADDRESS_MODE_SHIPPING_IF_SAME_CUSTOMER_AND_RECIPIENT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Buyer & Recipient have the same name'); ?></option>
                        </select>
                        <p class="note note-no-tool-tip">
                            <span><?php echo Mage::helper('M2ePro')->__('When to use shipping address as billing.'); ?></span>
                        </p>
                    </td>
                    <td class="value"  style="display: none">
                        <p class="note">
                            <span>
                                <?php echo Mage::helper('M2ePro')->__('The Amazon does not supply the complete billing Buyer information, only the Buyer\'s name and email address. The only way to fill in billing address in the Customer\'s invoice is to use information from shipping address.<br/><br/>
                                You should select the appropriate Option how to handle billing address for imported Customer:<br/>
                                <br/>
                                <strong>Always</strong> - the shipping address is always used as billing address. <br/>
                                <strong>Buyer & Recipient have the same name</strong> - the shipping address is used as billing address, only when Buyer\'s name and Recipient\'s name are the same. Otherwise, billing address fields will be empty and next message will appear in the city field: "The Amazon does not supply the complete billing Buyer information". <br/>'); ?>
                            </span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_tax" <?php if (($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Order Tax Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <div id="block_notice_amazon_accounts_magento_orders_tax" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Order Tax Settings'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This Section allows you to choose Tax Settings for Magento Order:
                    <ul class="list">
                        <li><b>Amazon</b> - Magento Order(s) uses Tax Settings from Amazon Listing(s).</li>
                        <li><b>Magento</b> - Magento Order(s) uses Magento Tax Settings.</li>
                        <li><b>Amazon & Magento</b> - if there are Tax Settings in Amazon Order, they are used in Magento Order(s), otherwise, Magento Tax Settings are used.</li>
                        <li><b>None</b> - Amazon and Magento Tax Settings are ignored.</li>
                    </ul>'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_tax_mode"><?php echo Mage::helper('M2ePro')->__('Tax Source'); ?>:</label>
                    </td>

                    <td class="value" style="width: auto;">
                        <select id="magento_orders_tax_mode" name="magento_orders_settings[tax][mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_NONE; ?>"<?php if ($formData['magento_orders_settings']['tax']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_NONE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_CHANNEL; ?>"<?php if ($formData['magento_orders_settings']['tax']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_CHANNEL) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Amazon'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_MAGENTO; ?>"<?php if ($formData['magento_orders_settings']['tax']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_MAGENTO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Magento'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_MIXED; ?>"<?php if ($formData['magento_orders_settings']['tax']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_TAX_MODE_MIXED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Amazon & Magento'); ?></option>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php $statusList = $this->getMagentoOrderStatusList(); ?>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_status_mapping" <?php if (($formData['magento_orders_settings']['listing']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_MODE_NO && $formData['magento_orders_settings']['listing_other']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_LISTINGS_OTHER_MODE_NO)) echo 'style="display: none;"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Order Status Mapping'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_amazon_accounts_orders_status" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Order Status Mapping'); ?>">
                <?php echo Mage::helper('M2ePro')->__('In this Block you can configure Mapping between Amazon Order state and Magento Order Statuses.
                Depending on the state of Amazon Order you can either manually determine certain Statuses for Magento Order and enable automatic Shipment and Invoice
                creation by selecting appropriate check-boxes, or use predefined default Settings. (i.e. Amazon: Order is Shipped -> Magento Order is Complete).<br/>'); ?>
            </div>
            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="magento_orders_status_mapping_mode"><?php echo Mage::helper('M2ePro')->__('Status Mapping'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_status_mapping_mode" name="magento_orders_settings[status_mapping][mode]" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT; ?>" <?php if ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT) echo "selected='selected'"; ?>><?php echo Mage::helper('M2ePro')->__('Default Order Statuses'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_CUSTOM; ?>" <?php if ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_CUSTOM) echo "selected='selected'"; ?>><?php echo Mage::helper('M2ePro')->__('Custom Order Statuses'); ?></option>
                        </select>
                    </td>
                </tr>

                <?php $isDisabledStatusStyle = ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT) ? "disabled='disabled'" : ''; ?>
                <?php
                    if ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT) {
                        $formData['magento_orders_settings']['status_mapping']['processing'] = Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_PROCESSING;
                        $formData['magento_orders_settings']['status_mapping']['shipped'] = Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_SHIPPED;

                        $formData['magento_orders_settings']['invoice_mode'] = Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_INVOICE_MODE_YES;
                        $formData['magento_orders_settings']['shipment_mode'] = Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_SHIPMENT_MODE_YES;
                    }
                ?>

                <tr id="magento_orders_status_mapping_processing_container">
                    <td class="label">
                        <label for="magento_orders_status_mapping_processing"><?php echo Mage::helper('M2ePro')->__('Order Status is Unshipped / Partially Shipped'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_status_mapping_processing" name="magento_orders_settings[status_mapping][processing]" class="M2ePro-required-when-visible" <?php echo $isDisabledStatusStyle; ?>>
                            <?php foreach ($statusList as $statusKey => $statusValue) { ?>
                                <option value="<?php echo $statusKey; ?>" <?php if ($formData['magento_orders_settings']['status_mapping']['processing'] == $statusKey) echo 'selected="selected"'; ?>><?php echo $statusValue; ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    <td class="value">
                        <input id="magento_orders_invoice_mode" name="magento_orders_settings[invoice_mode]" type="checkbox" <?php if ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT || $formData['magento_orders_settings']['invoice_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_INVOICE_MODE_YES) echo 'checked="checked"'; ?> <?php echo $isDisabledStatusStyle; ?>>
                        <label for="magento_orders_invoice_mode"><?php echo Mage::helper('M2ePro')->__('Automatic Invoice Creation'); ?></label>
                    </td>
                </tr>

                <tr id="magento_orders_status_mapping_shipped_container" <?php echo $isDisabledStatusStyle; ?>>
                    <td class="label">
                        <label for="magento_orders_status_mapping_shipped"><?php echo Mage::helper('M2ePro')->__('Order Status is Shipped'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="magento_orders_status_mapping_shipped" name="magento_orders_settings[status_mapping][shipped]" class="M2ePro-required-when-visible" <?php echo $isDisabledStatusStyle; ?>>
                            <?php foreach ($statusList as $statusKey => $statusValue) { ?>
                                <option value="<?php echo $statusKey; ?>" <?php if ($formData['magento_orders_settings']['status_mapping']['shipped'] == $statusKey) echo 'selected="selected"'; ?>><?php echo $statusValue; ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    <td class="value">
                        <input id="magento_orders_shipment_mode" name="magento_orders_settings[shipment_mode]" type="checkbox" <?php if ($formData['magento_orders_settings']['status_mapping']['mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_STATUS_MAPPING_MODE_DEFAULT || $formData['magento_orders_settings']['shipment_mode'] == Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_SHIPMENT_MODE_YES) echo 'checked="checked"'; ?> <?php echo $isDisabledStatusStyle; ?>>
                        <label for="magento_orders_shipment_mode"><?php echo Mage::helper('M2ePro')->__('Automatic Shipment Creation');?></label>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>