<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Template_Help */

?>

<div id="block_notice_amazon_sellingFormat_templates" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        In this Section you can Create, Edit and Delete Selling, Synchronization, Description, Shipping, Product Tax Code Policies.<br/><br/>
        <strong>Selling Policy</strong> is used to work with values related to the formation of your Offers on the Channel, such as
        Price, Quantity and similar parameters.<br/><br/>
        In the <strong>Synchronization Policy</strong> you can set the Rules under which the dynamic data exchange between Channel and Magento will be performed.<br /><br />
        <strong>Description Policy</strong> is used to provide necessary settings for Creating new ASIN/ISBN in Amazon Catalog
        or Update the Product Information of the existing Amazon Item.<br/><br/>
        <strong>Shipping Policy</strong> is used to apply the Amazon Shipping Templates to your Products within M2E Pro Listings.<br /><br />
        <strong>Product Tax Code Policy</strong> allows applying the Amazon Tax Codes to your Products within M2E Pro Listings.

');

    echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'policies'),
        Mage::helper('M2ePro/Component_Amazon')->getTitle()
    ); ?>
</div>
