<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Order_Help */

?>

<div id="block_notice_walmart_orders_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'On this page, you can review Channel Sales imported from Walmart.<br><br>

        In the grid below, filter the records to narrow your search results, then click the Order line to review the details. Use the Action menu to manage each Channel Order individually or update them in bulk.<br><br>

        <strong>Note:</strong> you can enable automatic creation of Magento Orders, Invoices, and Shipments under <i>%navigation%</i>.<br><br>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper('M2ePro/View_Walmart')->getPageNavigationPath('configuration', 'Accounts', 'Edit Account Configuration > Orders'),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, '/x/IuhaAg')
    ); ?>
</div>