<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Help */

?>

<div id="block_notice_walmart_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('M2E Pro Listings'); ?>">

    <?php echo Mage::helper('M2ePro')->__(
        'On this page, you can review M2E Pro Listings that you set up.<br><br>

        In the grid below, click M2E Pro Listing line to manage the Products placed to that Listing. 
        Use the Action menu next to the Listing to manage its Products, Settings or Logs. The Mass Actions allows clearing Logs and or deleting Listings in bulk.<br><br>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "walmart-integration")
    ); ?>

</div>