<style>
    #migration_notification_content {
        margin-left: 20px;
    }

    #migration_notification_content strong {
        font-size: 14px;
    }

    #migration_notification_content .block_notices {
        margin-top: 5px;
        margin-bottom: 10px;
    }
</style>

<!-- Rename accounts notification -->
<?php

    $notificationIndex = 1;
    $migrationModel = Mage::helper('M2ePro/Module_Wizard')->getWizard('migrationToV6');
    $renameAccountsData = $migrationModel->getMigrationData('accounts_rename', 'ebay');

?>

<div style="display: none;" id="migration_notification_notice" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Migration Notifications'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php echo Mage::helper('M2ePro')->__('Below you can find all changes that have been made after migration. Click on the links to check or edit changed options.'); ?>
</div>

<div style="display: none;" id="migration_notification_notice_empty" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php echo Mage::helper('M2ePro')->__('You have no notifications of Migration!'); ?>
</div>

<div id="migration_notification_content">
<?php if (!empty($renameAccountsData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('eBay accounts have been renamed'); ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($renameAccountsData as $id => $row): ?>
            <?php echo $row['old_title'] ?>&nbsp;<span style="color: grey;">to</span>&nbsp;<a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_account/edit', array('id' => $id,'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($renameAccountsData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Rename accounts notification -->

<!-- eBay Conditions notification -->
<?php

    $ebayConditionsData = $migrationModel->getMigrationData('condition_values', 'ebay');

?>

<?php if (!empty($ebayConditionsData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('eBay Condition has been changed in the next Description Templates') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayConditionsData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_template/edit', array('id' => $row['id'], 'nick' => 'description', 'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayConditionsData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End eBay Conditions notification -->

<!-- eBay Variation Ignore notification -->
<?php

    $ebayVariationIgnoreData = $migrationModel->getMigrationData('variation_ignore', 'ebay');

?>

<?php if (!empty($ebayVariationIgnoreData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('Ignore variation option has been moved from eBay General template to the Selling Format policy and set to default \'No\'.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;Below you can find the listings that used \'Yes\' in this option. Please, check their the Selling Format settings to make sure the option has the value you need.
    ') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayVariationIgnoreData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_listing/view', array('id' => $row['id'],'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayVariationIgnoreData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End eBay Variation Ignore notification -->

<!-- Hide products notification -->
<?php

    $hideProductsData = $migrationModel->getMigrationData('hide_products_others_listings', '*');
    $componentTitles = Mage::helper('M2ePro/Component')->getComponentsTitles();

?>

<?php if (!empty($hideProductsData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('\'Products Presented in Other listings\' option has been removed from the listing settings.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;Instead of it you can use Advanced Filter on the Add products page.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;Listings which used \'Do Not Show\' in this option are displayed below
    ') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($hideProductsData as $id => $row): ?>
            <?php
                if (in_array($row['component_mode'], Mage::helper('M2ePro/View_Common_Component')->getComponents())) {
                    $route = '*/adminhtml_common_'.$row['component_mode'].'_listing/view';
                } else {
                    $route = '*/adminhtml_'.$row['component_mode'].'_listing/view';
                }
            ?>
            <a target="_blank" href="<?php echo $this->getUrl($route, array('id' => $id,'wizard' => true)); ?>"><?php echo $row['title'] ?></a><span style="color: grey; font-style: italic;">(<?php echo $componentTitles[$row['component_mode']]; ?>)</span><?php if ($tempIndex < count($hideProductsData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Hide products notification -->

<!-- Ebay synchronization type notification -->
<?php

    $listingSynchTypeData = $migrationModel->getMigrationData('listing_synchronization_type', '*');

?>

<?php if (!empty($listingSynchTypeData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('Activation and Deactivation Synchronization Template options have been removed from the listings settings.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;Synchronization template (policy) settings take effect immediately and will be active during whole its life.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;The listings below used these options') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($listingSynchTypeData as $id => $row): ?>
            <?php
                if (in_array($row['component_mode'], Mage::helper('M2ePro/View_Common_Component')->getComponents())) {
                    $route = '*/adminhtml_common_'.$row['component_mode'].'_listing/view';
                } else {
                    $route = '*/adminhtml_'.$row['component_mode'].'_listing/view';
                }
            ?>
            <a target="_blank" href="<?php echo $this->getUrl($route, array('id' => $id,'wizard' => true)); ?>"><?php echo $row['title'] ?></a><span style="color: grey; font-style: italic;">(<?php echo $componentTitles[$row['component_mode']]; ?>)</span><?php if ($tempIndex < count($listingSynchTypeData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- Ebay synchronization type notification -->

<!-- eBay Schedule List notification -->
<?php

    $ebayScheduleListData = $migrationModel->getMigrationData('schedule_list', 'ebay');

?>

<?php if (!empty($ebayScheduleListData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('Schedule has been updated for eBay Synchronization policy. It now covers both list and relist rules.') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayScheduleListData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_template/edit', array('id' => $row['id'], 'nick' => 'synchronization', 'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayScheduleListData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End eBay Schedule List notification -->

<!-- Ebay schedule delay after end notification -->
<?php

    $ebayScheduleDelayAfterEndData = $migrationModel->getMigrationData('schedule_delay_after_end', 'ebay');

?>

<?php if (!empty($ebayScheduleDelayAfterEndData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('\'Delay After End\' option has been removed from eBay Synchronization template (policy). \'Immediate\' is used instead of it in the listings below.') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayScheduleDelayAfterEndData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_template/edit', array('id' => $row['id'], 'nick' => 'synchronization', 'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayScheduleDelayAfterEndData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Ebay schedule delay after end notification -->

<!-- Common Schedule Relist notification -->
<?php

    $commonRelistScheduleData = $migrationModel->getMigrationData('relist_schedule', '*');

?>

<?php if (!empty($commonRelistScheduleData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('Schedule has been removed from Amazon and Rakuten.com.
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;The Schedule was used in the listings below.
    ') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($commonRelistScheduleData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_common_'.$row['component_mode'].'_template_synchronization/edit', array('id' => $row['id'],'wizard' => true)); ?>"><?php echo $row['title'] ?></a><span style="color: grey; font-style: italic;">(<?php echo $componentTitles[$row['component_mode']]; ?></span><?php if ($tempIndex < count($commonRelistScheduleData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Common Schedule Relist notification -->

<!-- Ebay product details notification -->
<?php

    $ebayProductDetailsData = $migrationModel->getMigrationData('product_details', 'ebay');

?>

<?php if (!empty($ebayProductDetailsData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('Custom value option has been removed from eBay Product Items Details settings (General template > Item Specifics).
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;Please, check the Description policies below') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayProductDetailsData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_template/edit', array('id' => $row['id'], 'nick' => 'description', 'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayProductDetailsData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Ebay product details notification -->

<!-- Ebay unused description templates notification -->
<?php

    $ebayUnusedDescriptionData = $migrationModel->getMigrationData('unused_description_templates', 'ebay');

?>

<?php if (!empty($ebayUnusedDescriptionData)): ?>
    <strong><?php echo $notificationIndex; ?>) <?php echo Mage::helper('M2ePro')->__('During migration M2E has found unused Description templates (policies). Check if you need them.') ?></strong>
    <div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php $tempIndex = 1; ?>
        <?php foreach ($ebayUnusedDescriptionData as $row): ?>
            <a target="_blank" href="<?php echo $this->getUrl('*/adminhtml_ebay_template/edit', array('id' => $row['id'], 'nick' => 'description', 'wizard' => true)); ?>"><?php echo $row['title'] ?></a><?php if ($tempIndex < count($ebayUnusedDescriptionData)): ?><br/><?php endif; ?>
            <?php $tempIndex++; ?>
        <?php endforeach; ?>
    </div>
    <?php $notificationIndex++; ?>
<?php endif; ?>
<!-- End Ebay unused description templates notification -->

</div>

<script type="text/javascript">
    <?php if ($notificationIndex == 1): ?>
        <?php $this->setData('save_migration_notes', false); ?>
        $('migration_notification_notice_empty').show();
    <?php else: ?>
        $('migration_notification_notice').show();
    <?php endif; ?>
</script>