<div id="block_notice_common_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('M2E Pro Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This Page shows the <strong>M2E Pro Listings</strong> you\'ve set up.<br/><br/>
        Click a line in the Table below to manage the Products currently Listed using that M2E Pro Listing.
        Otherwise use the Dropdown Menu in the Actions Column for more Options.<br/>
        To Clear the Logs or Delete more than one M2E Pro Listing at a time, use the Actions Dropdown at the very top of the Table.
    ');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Listings+Overview')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/b4IVAQ'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/g4MVAQ'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>