<p class="switcher">
    <label>
        <input type="checkbox" name="" <?php if ($this->isChecked()): ?>checked="checked"<?php endif; ?> onclick="setLocation('<?php echo $this->getFilterUrl(); ?>');">
        &nbsp;<?php echo Mage::helper('M2ePro')->__('Show Orders without Magento Orders'); ?>
    </label>
    <span>
        <img src="<?php echo $this->getSkinUrl('M2ePro/images/tool-tip-icon.png'); ?>" class="tool-tip-image">
        <span class="tool-tip-message" style="font-size: 12px; display: none;">
        <img src="<?php echo $this->getSkinUrl('M2ePro/images/help.png'); ?>">
            <span>
                <?php echo Mage::helper('M2ePro')->__(
                    'Check this box to filter for Orders that don\'t have a matching Magento Order.<br/>
                    Magento Orders might not be created for Channel Orders for a number of reasons, including incomplete information or
                    further Action being required to complete the Order.<br/><br/>
                    <b>View Order Details</b> for detailed information on individual Orders and the Action needed to create the matching Magento Order.'
                ); ?>
        </span>
    </span>
</p>
