<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Order_NotCreatedFilter */

?>

<p class="switcher">
    <label>
        <input type="checkbox" name="" <?php if ($this->isChecked()): ?>checked="checked"<?php endif; ?> onclick="setLocation('<?php echo $this->getFilterUrl(); ?>');">
        &nbsp;<?php echo Mage::helper('M2ePro')->__('No Magento Order Created'); ?>
    </label>
</p>
