<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_ControlPanel_Tabs_Command_Group $this */

?>

<?php foreach($this->commands as $index => $command) : ?>

    <table>
        <tr>
            <td class="group_number_td"><b><?php echo $index + 1; ?>.</b></td>
            <td style="width: 10px;">|</td>
            <td>
                <?php echo $this->getCommandLauncherHtml($command); ?>
            </td>
        </tr>

        <?php if ($command['new_line']): ?>
            <tr>
                <td colspan="3">
                    <hr style="margin-top: 8px;"/>
                </td>
            </tr>
        <?php endif; ?>

    </table>

<?php endforeach; ?>