<div id="block_notice_buy_template_new_product_template_core" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Description'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        ' Description is used to design your Items\' Description on Rakuten.com. The more information you provide the easier it is for Buyers to make a choice.
        <br/>
        <br/>
        It is possible to choose a Product Description or Product Short Description, which will be taken from Magento. Or you can create a Custom Description by adding necessary information.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/GYwVAQ')
    ); ?>
</div>

<?php

$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();
!empty($formData['category']['features_template']) && $formData['category']['features_template'] = json_decode($formData['category']['features_template'], true);

$default = array(
    'category' => array(
        'title' => '',

        'title_mode' => '',
        'title_template' => '',

        'mfg_name_template' => '',

        'mfg_part_number_mode' => '',
        'mfg_part_number_custom_value' => '',
        'mfg_part_number_custom_attribute' => '',

        'description_mode' => '',
        'description_template' => '',

        'main_image_mode' => '',
        'main_image_attribute' => '',

        'additional_images_mode' => '',
        'additional_images_attribute' => '',
        'additional_images_limit' => '',

        'features_mode' => '',
        'features_template' => array(),

        'keywords_mode' => '',
        'keywords_custom_value' => '',
        'keywords_custom_attribute' => '',

        'weight_mode' => '',
        'weight_custom_value' => '',
        'weight_custom_attribute' => '',
    ),
);

$formData = array_merge($default, $formData);

/** @var Ess_M2ePro_Helper_Magento_Attribute $magentoAttributeHelper */
$magentoAttributeHelper = Mage::helper('M2ePro/Magento_Attribute');

$attributesByInputTypes = array(
    'text' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text')),
    'text_select' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text', 'select')),
    'text_images' => $magentoAttributeHelper->filterByInputTypes(
        $this->attributes,
        array('text', 'image', 'media_image', 'gallery', 'multiline', 'textarea', 'select', 'multiselect')
    ),
    'text_weight' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text', 'weight')),
);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    Event.observe(window, 'load', function() {

        $('title_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.title_mode_change)
                .simulate('change');

        $('mfg_part_number_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.mfg_part_number_mode_change)
                .simulate('change');

        $('description_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.description_mode_change)
                .simulate('change');

        $('main_image_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.main_image_mode_change)
                .simulate('change');

        $('additional_images_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.additional_images_mode_change)
                .simulate('change');

        $('keywords_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.keywords_mode_change)
                .simulate('change');

        $('features_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.features_mode_change)
                .simulate('change');
        $('weight_mode')
                .observe('change', BuyTemplateNewProductHandlerObj.weight_mode_change)
                .simulate('change');

        for (var i=0; i< M2ePro.php.constant('Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_COUNT'); i++) {
            var input = $('features_' + i);
            input.observe('keyup', function(event){
                var emptyVisibleFeaturesExist = $$('.features_tr').any(function(obj) {
                    return $(obj).visible() && $(obj).select('input[name="category[features_template][]"]')[0].value == '';
                });
                var visibleElements= $$('.features_tr').findAll(Element.visible);

                if (this.value == '' || emptyVisibleFeaturesExist ||
                    visibleElements.size() == M2ePro.php.constant('Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_COUNT')) {
                    $('show_features_action').addClassName('action-disabled');
                } else {
                    $('show_features_action').removeClassName('action-disabled');
                }
            })
        }
        BuyTemplateNewProductHandlerObj.renderHelpIcon($('main_image_help'),BuyTemplateNewProductHandlerObj.notes.image);
        BuyTemplateNewProductHandlerObj.renderHelpIcon($('additional_image_help'),BuyTemplateNewProductHandlerObj.notes.image);
   });

</script>

<style type="text/css">

    .input-text-small {
        width: 120px !important;
    }
    .textarea {
        width: 98% !important;
        height: 500px !important;
    }
    select.select-main {
        width: 356px !important;
    }
    .select-wrapper {
        margin-left: 15px;
    }
    a.action-disabled {
        color: gray !important;
        text-decoration: none !important;
    }
    a.action-disabled:hover {
        color: gray !important;
        text-decoration: none !important;
    }
    td.value {
        width: 700px !important;
    }
    #main_image_help,
    #additional_image_help{
        cursor: pointer;
    }
</style>

<div class="entry-edit" id="magento_block_buy_template_description_title">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <!-- title -->
                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Title'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="title_mode" name="category[title_mode]" class="select required-entry">
                            <option style="display: none;"></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::TITLE_MODE_PRODUCT_NAME; ?>" <?php if ($formData['category']['title_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::TITLE_MODE_PRODUCT_NAME): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Name'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::TITLE_MODE_CUSTOM_TEMPLATE; ?>" <?php if ($formData['category']['title_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::TITLE_MODE_CUSTOM_TEMPLATE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Item\'s Title that Buyers will see on Rakuten.com Listing.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="custom_title_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Title Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title_template" name="category[title_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['title_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The name of the brand/manufacturer of your Product.'); ?></span>
                        </p>
                    </td>
                    <td class="value">
                        <span id="select_attributes_for_title_span" class="select-wrapper">
                            <select id="select_attributes_for_title" class="M2ePro-custom-attribute-can-be-created"  style="width: 150px;">
                                <?php foreach($this->attributes as $attribute) : ?>
                                    <option value="<?php echo $attribute['code']; ?>">
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </span>
                        <?php echo $this->getChildHtml('select_attributes_for_title_button'); ?>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;">
                    </td>
                </tr>

                <!-- mfg-name -->

                <tr id="mfg_name_template_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Manufacturer Name'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="manufacturer_template" name="category[mfg_name_template]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['mfg_name_template']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The name of the brand/manufacturer of your Product.'); ?></span>
                        </p>
                        </td>
                    <td class="value">
                        <span id="select_attributes_for_manufacturer_span" class="select-wrapper">
                            <select id="select_attributes_for_manufacturer" class="M2ePro-custom-attribute-can-be-created" style="width: 150px;" apply_to_all_attribute_sets="0">
                                <?php foreach($this->attributes as $attribute) : ?>
                                    <option value="<?php echo $attribute['code']; ?>">
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </span>
                        <?php echo $this->getChildHtml('select_attributes_for_mfg_name_template_button'); ?>
                    </td>
                </tr>

                <!-- mfg-part-number -->
                <tr>
                    <input type="hidden" id="mfg_part_number_custom_attribute" name="category[mfg_part_number_custom_attribute]" value="<?php echo $formData['category']['mfg_part_number_custom_attribute']; ?>"/>

                    <td class="label">
                        <label for="mfg_part_number_mode"><?php echo Mage::helper('M2ePro')->__('Manufacturer Part No.'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="mfg_part_number_mode" name="category[mfg_part_number_mode]" class="select required-entry M2ePro-custom-attribute-can-be-created" apply_to_all_attribute_sets="0">
                            <option style="display: none;"></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::MFG_PART_NUMBER_MODE_CUSTOM_VALUE; ?>" <?php if ($formData['category']['mfg_part_number_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::MFG_PART_NUMBER_MODE_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attributes">
                                <?php foreach($this->attributes as $attribute) : ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::MFG_PART_NUMBER_MODE_CUSTOM_ATTRIBUTE; ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($attribute['code'] == $formData['category']['mfg_part_number_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The unique part number assigned to the Product by the manufacturer.
                                <br/>Use only numbers and letters without spaces.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="mfg_part_number_custom_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Manufacturer Part No Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="mfg_part_number_template" name="category[mfg_part_number_custom_value]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['mfg_part_number_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;">
                    </td>
                </tr>

                <!-- weight-->
                <tr>
                    <input type="hidden" id="weight_custom_attribute" name="category[weight_custom_attribute]" value="<?php echo $formData['category']['weight_custom_attribute']; ?>"/>

                    <td class="label">
                        <label for="weight_mode"><?php echo Mage::helper('M2ePro')->__('Weight'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="weight_mode" style="i" name="category[weight_mode]" class="select required-entry M2ePro-custom-attribute-can-be-created" allowed_attribute_types="text" apply_to_all_attribute_sets="0">
                            <option style="display: none;"></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::WEIGHT_MODE_CUSTOM_VALUE; ?>" <?php if ($formData['category']['weight_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::WEIGHT_MODE_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attribute">
                                <?php foreach($attributesByInputTypes['text_weight'] as $attribute) : ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::WEIGHT_MODE_CUSTOM_ATTRIBUTE; ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($attribute['code'] == $formData['category']['weight_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The shipping weight in pounds for Product(s). Only numeric value.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="weight_custom_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Weight Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="weight_custom_value" name="category[weight_custom_value]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['weight_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-validation-float" />
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_buy_template_description_details">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Images'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <!-- main image -->
                <tr class="requirie-attribute-set">
                    <input type="hidden" id="main_image_attribute" name="category[main_image_attribute]" value="<?php echo $formData['category']['main_image_attribute']; ?>"/>

                    <td class="label">
                        <label for="main_image_mode"><?php echo Mage::helper('M2ePro')->__('Main Image'); ?>: <span class="required">*</span>(<a id="main_image_help" title="Help">?</a>)</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="main_image_mode" name="category[main_image_mode]" class="select required-entry M2ePro-custom-attribute-can-be-created" allowed_attribute_types="text,textarea,select,multiselect" apply_to_all_attribute_sets="0">
                            <option style="display: none;"></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::IMAGE_MAIN_MODE_PRODUCT_BASE; ?>" <?php if ($formData['category']['main_image_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::IMAGE_MAIN_MODE_PRODUCT_BASE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Base Image'); ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attributes">
                                <?php foreach($attributesByInputTypes['text_images'] as $attribute) : ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::IMAGE_MAIN_MODE_CUSTOM_ATTRIBUTE; ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($attribute['code'] == $formData['category']['main_image_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Image you will see on your Rakuten.com Listing.'); ?></span>
                        </p>
                    </td>
                </tr>

                <!-- additional images -->
                <tr id="additional_images_mode_tr">
                    <input type="hidden" id="additional_images_limit" name="category[additional_images_limit]" value="<?php echo $formData['category']['additional_images_limit']; ?>"/>
                    <input type="hidden" id="additional_images_attribute" name="category[additional_images_attribute]" value="<?php echo $formData['category']['additional_images_attribute']; ?>"/>

                    <td class="label">
                        <label for="additional_images_mode"><?php echo Mage::helper('M2ePro')->__('Additional Images'); ?>: (<a id="additional_image_help" title="Help">?</a>)</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="additional_images_mode" class="M2ePro-custom-attribute-can-be-created" allowed_attribute_types="text,textarea,select,multiselect" apply_to_all_attribute_sets="0" name="category[additional_images_mode]">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ADDITIONAL_IMAGES_MODE_NONE; ?>" <?php if ($formData['category']['additional_images_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ADDITIONAL_IMAGES_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>

                            <optgroup label="Product Images Quantity">
                                <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ADDITIONAL_IMAGES_MODE_PRODUCT; ?>" attribute_code="1" <?php if ($formData['category']['additional_images_limit'] == 1): echo ' selected="selected"'; endif; ?>>1</option>
                                <?php for ($i = 2; $i <= 4; $i++): ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ADDITIONAL_IMAGES_MODE_PRODUCT; ?>" attribute_code="<?php echo $i; ?>" <?php if ($formData['category']['additional_images_limit'] == $i): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Up to').' '.$i; ?></option>
                                <?php endfor ?>
                            </optgroup>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attributes">
                                <?php foreach($attributesByInputTypes['text_images'] as $attribute) : ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ADDITIONAL_IMAGES_MODE_CUSTOM_ATTRIBUTE; ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($attribute['code'] == $formData['category']['additional_images_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_buy_template_description_keywords">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Keywords And Features'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <input type="hidden" id="keywords_custom_attribute" name="category[keywords_custom_attribute]" value="<?php echo $formData['category']['keywords_custom_attribute']; ?>"/>

                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Keywords') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="keywords_mode" name="category[keywords_mode]" class="select M2ePro-custom-attribute-can-be-created" apply_to_all_attribute_sets="0">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::KEYWORDS_MODE_NONE; ?>" <?php if ($formData['category']['keywords_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::KEYWORDS_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::KEYWORDS_MODE_CUSTOM_VALUE; ?>" <?php if ($formData['category']['keywords_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::KEYWORDS_MODE_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attributes">
                                <?php foreach($this->attributes as $attribute) : ?>
                                    <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::KEYWORDS_MODE_CUSTOM_ATTRIBUTE; ?>" attribute_code="<?php echo $attribute['code']; ?>" <?php if ($attribute['code'] == $formData['category']['keywords_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Search keywords that will help Customers to find your Product. Separated by comma.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="keywords_custom_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Keywords Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="keywords_custom_value" name="category[keywords_custom_value]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['keywords_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

                <!-- features -->
                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Features') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="features_mode" name="category[features_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_MODE_NONE; ?>" <?php if ($formData['category']['features_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_MODE_CUSTOM_TEMPLATE; ?>" <?php if ($formData['category']['features_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_MODE_CUSTOM_TEMPLATE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Features'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Allows highlighting some of the Product\'s most important qualities.'); ?></span>
                        </p>
                    </td>
                </tr>

                <?php for ($i = 0; $i < Ess_M2ePro_Model_Buy_Template_NewProduct_Core::FEATURES_COUNT; $i++): ?>
                <tr class="features_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Value #%number%', $i + 1); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="features_<?php echo $i; ?>" name="category[features_template][]" type="text" class="input-text M2ePro-required-when-visible" value="<?php echo !empty($formData['category']['features_template'][$i]) ? $formData['category']['features_template'][$i] : ''; ?>">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Max. 250 characters.'); ?></span>
                        </p>
                        </td>
                    <td class="value">
                        <span id="select_attributes_for_features_<?php echo $i; ?>_span" class="select-wrapper">
                            <select id="select_attributes_for_features_<?php echo $i; ?>" class="M2ePro-custom-attribute-can-be-created" style="width: 150px;" apply_to_all_attribute_sets="0">
                                <?php foreach($this->attributes as $attribute) : ?>
                                    <option value="<?php echo $attribute['code']; ?>">
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </span>
                        <?php echo $this->getChildHtml("select_attributes_for_features_{$i}_button"); ?>
                    </td>
                </tr>
                <?php endfor; ?>

                <tr id="features_actions_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value" style="padding-top: 0 !important;">
                        <a id="show_features_action" href="javascript: void(0);" onclick="BuyTemplateNewProductHandlerObj.showFeature()"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        /
                        <a id="hide_features_action" href="javascript: void(0);" onclick="BuyTemplateNewProductHandlerObj.hideFeature();"><?php echo Mage::helper('M2ePro')->__('Remove') ?></a>
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_base_edit_description_weight">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Description'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">

                <!-- Description -->
                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Description'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="description_mode" name="category[description_mode]" class="select required-entry">
                            <option style="display: none;"></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_PRODUCT_FULL; ?>" <?php if ($formData['category']['description_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_PRODUCT_FULL): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Description'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_PRODUCT_SHORT; ?>" <?php if ($formData['category']['description_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_PRODUCT_SHORT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Short Description'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_CUSTOM_TEMPLATE; ?>" <?php if ($formData['category']['description_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::DESCRIPTION_MODE_CUSTOM_TEMPLATE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Should be one block of text or a single paragraph. Do not use special characters and html tags.<br/>
                                                                        Limited to 8\'000 characters.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="c-custom_description_tr" style="display: none;">
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Description Value'); ?>: <span class="required">*</span></td>
                    <td class="value">

                        <script type="text/javascript">
                            wysiwygtext = {
                                isEnabled: function() {
                                    return false;
                                }
                            };
                        </script>

                        <textarea id="description_template" name="category[description_template]" class="textarea M2ePro-required-when-visible"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['category']['description_template']); ?></textarea>

                    </td>
                </tr>

                <tr class="c-custom_description_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">

                        <div class="entry-edit-head" style="background: #D6D6D6;">
                            <h4 class="icon-head head-edit-form fieldset-legend" style="color: #EA7601;"><?php echo Mage::helper('M2ePro')->__('Custom Inserts'); ?></h4>
                        </div>

                        <div class="fieldset">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tr>
                                        <td class="label">
                                            <label for="select_attributes_span"><?php echo Mage::helper('M2ePro')->__('Product Attribute');?>:</label>
                                        </td>
                                        <td class="value">
                                            <span id="select_attributes_span">
                                                 <select id="select_attributes" class="M2ePro-custom-attribute-can-be-created" apply_to_all_attribute_sets="0">
                                                     <?php foreach($this->attributes as $attribute) : ?>
                                                         <option value="<?php echo $attribute['code']; ?>">
                                                             <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                                         </option>
                                                     <?php endforeach; ?>
                                                 </select>
                                            </span>
                                            &nbsp;
                                            <?php echo $this->getChildHtml('add_product_attribute_button'); ?>
                                            <p class="note">
                                                <span><?php echo Mage::helper('M2ePro')->__('Attributes related to the previously chosen Attribute Set.'); ?></span>
                                            </p>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>
