<div id="block_notice_common_logs_orders_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains Orders history information.');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Logs#Logs-OrdersLog')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/foIVAQ#Logs-OrdersLog'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/iIMVAQ#Logs-OrdersLog'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>