<div id="block_notice_ebay_logs_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains all information about Actions, which were done on all M2E Pro Listings and their Items.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/MAAJAQ#Logs.-ListingsLog')
    ); ?>
</div>