<div id="block_notice_walmart_product_manage_variations" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Child Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        On this tab, you can see Walmart Item Variations that were created based on Magento Product Variations.<br><br>

        In your Walmart Seller Center, each Variation from the list below will be displayed as a separate Item. Walmart will organize Item Variations in a Variant Group prior to showing them to buyers.<br><br>

        Please be advised that M2E Pro does not affect Walmart decision on how to organize Item Variations in a Variant Group. Variations that you defined in a single Magento Variational Product not necessarily will be grouped together on Walmart.<br><br>

        To start configuring Walmart Item Variations, switch to the Settings tab and click Set Attributes.<br><br>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/L4taAQ')
    ); ?>
</div>