<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Search_Help */

?>

<div id="block_notice_ebay_listing_search_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows all Products Listed using M2E Pro Listings or added as a Unmanaged Listing.<br/><br/>
        Use the filters to find the Product you want to manage. If an eBay Item ID is available, clicking it will take you to the Listing on eBay.
        Clicking the arrows icon in the Manage Column will take you to the M2E Pro Listing\'s Products Page.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'search-product')
    ); ?>
</div>