<div id="block_notice_buy_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Page shows the Products you\'ve added to the current M2E Pro Listing. <br/><br/>

    Use the filters to find the Product you want to manage. <br/><br/>

    Click the <strong>Add Products</strong> Button to add new Magento Products to the M2E Pro Listing. <br/>

    Click <strong>Edit Settings</strong> to adjust the Settings for this Listing. <br/>

    To Add a new M2E Pro Listing or switch between different M2E Pro Listings, click the Arrow Icon to the right of the M2E Pro Listing Title above. <br/><br/>

    <b>Note:</b> If you need to Search by Magento Product Attributes not shown in the Filters of the Grid, click <strong>Show Advanced Filter</strong> above the Table on the right.<br/><br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/eIsVAQ')); ?>
</div>