<div id="block_notice_walmart_accounts" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Accounts'); ?>">

    <?php echo Mage::helper('M2ePro')->__('
        In this section, you can create, edit and delete Accounts for Walmart integration.<br/><br/>
        Please be advised that Account is created per Marketplace. For example, to connect M2E Pro with your US Walmart Account, use the Private Key and Consumer 
        ID obtained in the Seller Center on Walmart.com.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/L4taAQ")
    ); ?>

</div>