<div id="block_notice_walmart_accounts" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Accounts'); ?>">

    <?php echo Mage::helper('M2ePro')->__('
        In this section, you can create, edit and delete Accounts for Walmart integration.<br/><br/>
        Please be advised that Account is created per Marketplace using the relevant API credentials.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/io1aAQ")
    ); ?>

</div>