<div id="block_notice_ebay_product_manage_variations" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Manage Product Variations'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    In this Section you can find all Item Variations with possibility to search, filter, sort etc.<br/><br/>

    You can add eBay Catalog Identifiers for each Variation separately. In case the Value of eBay Catalog Identifier
    is provided here it will be used in priority over eBay Catalog Identifiers Settings of Description Policy.<br/><br/>

    For Bundle Products and Simple Products with Custom Options Settings for eBay Catalog Identifiers can be
    provided only for each Variation separately here, as Description Policy Settings cannot be applied for them.<br/><br/>

    <strong>Note:</strong> markers <strong>"will be added"</strong> and <strong>"will be deleted"</strong> mean that
    Variation will be Added/Removed during the next Revise Action.
    '); ?>
</div>