<div id="block_notice_ebay_configuration_category_edit_primary" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Primary Category'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Many eBay Categories allow you set Item specifics which let you provide details about the Item you\'re selling, such as brand, size type, size, color, and style.
        M2E Pro allows you to add Item specifics for M2E Pro Listings so that Products are Listed on eBay with the Item specifics you choose.<br/>
        If you change an eBay Category, you will need to re-set the Item specifics details.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/DQAJAQ')
    ); ?>
</div>