<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Configuration_Category_Edit_Primary_Tabs_Specific */

?>

<script type="text/javascript">

    Event.observe(window, 'load', function() {
        <?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
            EbayConfigurationCategoryHandlerObj.setTemplates('<?php echo json_encode($this->templates); ?>');
        <?php endif; ?>
    });

</script>

<div id="primary_category_specifics">
    <?php foreach ($this->specificsBlocks as $block): ?>

        <div class="entry-edit" id="magento_block_ebay_category_specific_item_specifics<?php echo $block['unique_id']; ?>">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Created at') . ' ' . $block['create_date']; ?></h4>
            </div>

            <input class="template-info" type="hidden" template_id="<?php echo $block['template_id']; ?>" obj_name="<?php echo 'EbayListingCategorySpecificHandler'.$block['unique_id'].'Obj'; ?>" create_date="<?php echo $block['create_date']; ?>">

            <div class="fieldset">
                <div class="hor-scroll">
                    <?php echo $block['block']->toHtml(); ?>
                </div>
            </div>

        </div>

    <?php endforeach; ?>
</div>