<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Account_PickupStore_Edit_Tabs_StockSettings */

$formData = $this->getFormData();

/** @var Ess_M2ePro_Helper_Magento_Attribute $magentoAttributeHelper */
$magentoAttributeHelper = Mage::helper('M2ePro/Magento_Attribute');

$attributesByInputTypes = array(
    'text' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text')),
);

?>

<script>
    M2ePro.formData.qty_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_mode']); ?>';
    M2ePro.formData.qty_modification_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_modification_mode']); ?>';
</script>

<div id="block_notice_ebay_accounts_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Quantity Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        You should select the Quantity source for the Products in this Store. There are 2 Options to
        choose from:<br/>
        <ul class="list">
            <li><strong>Selling Policy</strong> — uses the quantity settings provided in the Selling Policy for the Product;</li>
            <li><strong>Custom Settings</strong> — allows you to select the Quantity source as well as specify the Percentage and the Conditional Quantity Options.</li>
        </ul>
        Note: in case Custom Settings are used and there are a lot of Stores with multiple Products, it can affect the Performace of your Magento system.
    '); ?>
</div>

<div class="entry-edit" id="magento_block_ebay_account_pickup_store_form_data_quantity_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="default_mode"><?php echo Mage::helper('M2ePro')->__('Use From'); ?>:</label>
                    </td>
                    <td class="value">
                        <select name="default_mode" id="default_mode">
                            <option value="0" <?php echo $formData['qty_mode'] == Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_SELLING_FORMAT_TEMPLATE ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('M2ePro')->__('Selling Policy'); ?></option>
                            <option value="1" <?php echo $formData['qty_mode'] != Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_SELLING_FORMAT_TEMPLATE ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('M2ePro')->__('Custom Settings'); ?></option>
                        </select>
                    </td>
                    <td class="value">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('
                                Select the Quantity source for the Products in this Store. If you select the
                                Custom Settings with different Quantity sources and there are a lot of Products in
                                your Store, the Performance of your Magento can be affected.
                            '); ?></span>
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_account_pickup_store_form_data_quantity_custom_settings">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Custom Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="messages">
                <ul class="messages">
                    <li class="error-msg"><ul><li><span>
                        <?php echo Mage::helper('M2ePro')->__('
                            Application of Custom Settings can have negative impact on the Performance of your Magento
                            if there are a lot of Stores and Products in these Stores.<br/>
                            Please, be <strong>very attentive</strong> when selecting Settings in this Block. If you
                            select the different Quantity sources and there are a lot of Products in your Store,
                            the <strong>Performance</strong> of your Magento <strong>can be affected</strong>.
                        '); ?>
                    </span></li></ul></li>
                </ul>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="qty_mode_tr">
                    <td class="label">
                        <label for="qty_mode"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_mode" class="M2ePro-custom-attribute-can-be-created" allowed_attribute_types="text" name="qty_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_PRODUCT; ?>" <?php echo $formData['qty_mode'] == Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_PRODUCT ? 'selected="selected"' : '';?>><?php echo Mage::helper('M2ePro')->__('Product Quantity'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_NUMBER; ?>" <?php echo $formData['qty_mode'] == Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_NUMBER ? 'selected="selected"' : '';?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>

                            <optgroup class="M2ePro-custom-attribute-optgroup" label="Magento Attribute" new_option_value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_ATTRIBUTE; ?>">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_PRODUCT_FIXED; ?>" <?php if (Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_PRODUCT_FIXED == $formData['qty_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('QTY'); ?></option>
                                <?php if ($formData['qty_mode'] == Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_ATTRIBUTE && !$magentoAttributeHelper->isExistInAttributesArray($formData['qty_custom_attribute'], $this->attributes) && $formData['qty_custom_attribute'] != ''): ?>
                                    <option attribute_code="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['qty_custom_attribute']) ?>" selected="selected" value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_ATTRIBUTE; ?>">
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($magentoAttributeHelper->getAttributeLabel($formData['qty_custom_attribute'])) ?>
                                    </option>
                                <?php endif; ?>
                                <?php foreach($attributesByInputTypes['text'] as $attribute) : ?>
                                    <option attribute_code="<?php echo $attribute['code']; ?>" value="<?php echo Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_ATTRIBUTE; ?>" <?php if ($formData['qty_mode'] == Ess_M2ePro_Model_Ebay_Account_PickupStore::QTY_MODE_ATTRIBUTE && $attribute['code'] == $formData['qty_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>

                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__(
                                        'The number of Items you want to sell on eBay.<br/><br/>
                                    <b>Product Quantity:</b> the number of Items on eBay will be the same as in Magento.<br/>
                                    <b>Single Item:</b> only one Item will be available on eBay.<br/>
                                    <b>Custom Value:</b> set a Quantity in the Policy here.<br/>
                                    <b>Magento Attribute:</b> takes the number from the Attribute you specify.'
                                    ); ?></span>
                        </p>

                        <input type="hidden" name="qty_custom_attribute" id="qty_custom_attribute" />

                    </td>
                </tr>

                <tr id="qty_mode_cv_tr" style="display: none;">
                    <td class="label">
                        <label for="qty_custom_value"><?php echo Mage::helper('M2ePro')->__('Quantity Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="qty_custom_value" name="qty_custom_value" value="<?php echo $formData['qty_custom_value']; ?>" type="text" class="input-text M2ePro-required-when-visible validate-digits" />
                    </td>
                </tr>

                <tr id="qty_percentage_tr">
                    <td class="label">
                        <label for="qty_percentage"><?php echo Mage::helper('M2ePro')->__('Quantity Percentage'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_percentage" name="qty_percentage" class="required-entry">
                            <?php for ($i = 100; $i >= 5; $i -= 5) : ?>
                                <option value="<?php echo $i; ?>" <?php echo ($formData['qty_percentage'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?> %</option>
                            <?php endfor; ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Sets the percentage for calculation of Items number to be Listed on eBay basing on Product Quantity or Magento Attribute. E.g., if Quantity Percentage is set to 10% and Product Quantity is 100, the Quantity to be Listed on eBay will be calculated as <br/>100 *10%  = 10.<br/>'); ?></span>
                        </p>
                    </td>
                </tr>

                <!-- Max Posted QTY-->
                <tr id="qty_modification_mode_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Conditional Quantity'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_modification_mode" name="qty_modification_mode" class="required-entry">
                            <option value="0" <?php echo ($formData['qty_modification_mode'] == '0') ? 'selected="selected"' : ''?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="1" <?php echo ($formData['qty_modification_mode'] == '1') ? 'selected="selected"' : ''?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__(
                                        'Choose whether to limit the amount of Stock you list on eBay, eg because you want to set some Stock aside for sales off eBay.<br/><br/>
                                    If this Setting is <b>Enabled</b> you can specify the maximum Quantity to be Listed.
                                    If this Setting is <b>Disabled</b> all Stock for the Product will be Listed as available on eBay.'
                                    ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="qty_min_posted_value_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Minimum Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="qty_min_posted_value_td" class="value" style="width: auto;">
                        <input id="qty_min_posted_value" name="qty_min_posted_value" value="<?php echo $formData['qty_min_posted_value']; ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If you have 2 pieces in Stock but set a Minimum Quantity to Be Listed of 5, Item will not be Listed on eBay.<br/>
Otherwise, the Item will be Listed with Quantity according to the Settings in the Selling Policy'); ?>
                            </span>
                        </p>
                    </td>
                </tr>

                <tr id="qty_max_posted_value_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Maximum Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="qty_max_posted_value_td" class="value" style="width: auto;">
                        <input id="qty_max_posted_value" name="qty_max_posted_value" value="<?php echo $formData['qty_max_posted_value']; ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Set a maximum number to sell on eBay, e.g. if you have 10 Items in Stock but want to keep 2 Items back, set a Maximum Quantity of 8.'); ?>
                            </span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>