<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Log_Order_Help */

?>

<div id="block_notice_ebay_logs_orders_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains information about Order processing.<br/><br/>
        Find detailed info in <a href="%url%" target="_blank">the article</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'logs-and-events#c8ae2adfb70142f8b4dece6f5e614e84')
    ); ?>
</div>