<div id="pop_up_content" style="padding-bottom: 10px;">
    <div class="hor-scroll" style="padding-top: 15px; ">

        <div id="messages">
            <ul class="messages">
                <li class="warning-msg">
                    <ul>
                        <li>
                            <span>
                                <?php echo Mage::helper('M2ePro')->__(
                                    'Products below will not be added into the chosen Listing.<br/>
                                    <div style="font-weight: normal;">
                                        <span style="text-decoration: underline">Reason:</span> <br/>
                                        Products with the same Magento Product IDs already exist in the Listing.<br/>
                                    </div>'
                                ); ?>
                            </span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <div style="float: left; padding-top: 10px">

        </div>
        <div style="float: left; padding-top: 10px; margin-left: 15px">

        </div>
        <div class="clear"></div>

        <div id="help_grid" style="margin: 0 auto; padding-top: 10px;">
            <?php echo $this->getChildHtml('failedProducts_grid') ?>
        </div>

        <div style="float: right; margin-top: 20px">
            <?php echo $this->getChildHtml('confirm_button'); ?>
        </div>

    </div>
</div>

<script type="text/javascript">

    $('confirm_button_failed_products')
        .stopObserving('click')
        .observe('click', EbayListingTransferringHandlerObj.confirmFailedProducts);

</script>