<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Transferring_General */

?>

<div id="data_container_progress" style="margin-top: 20px; display:none;"></div>

<div id="data_container" >

    <?php echo $this->getChildHtml('breadcrumb') ?>

    <div id="data_container_step_tutorial" style="padding-bottom: 10px;display: none;">
        <?php echo $this->getChildHtml('tutorial') ?>
    </div>

    <div id="data_container_step_destination" style="padding-bottom: 10px;display: none;">
        <?php echo $this->getChildHtml('destination') ?>
    </div>

    <div id="data_container_step_policy" style="padding-bottom: 10px;display: none;">
        <?php echo $this->getChildHtml('policy') ?>
    </div>

    <div id="data_container_step_translation" style="padding-bottom: 10px;display: none;">
        <?php echo $this->getChildHtml('translation') ?>
    </div>

</div>

<script type="text/javascript">
    <?php if ($this->isShownTutorial()) { ?>
        EbayListingTransferringHandlerObj.renderStepDestination();
    <?php } else { ?>
        EbayListingTransferringHandlerObj.renderStepTutorial();
    <?php } ?>
</script>
