<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Order_Item_Edit */

?>

<style type="text/css">

    .gray {
        color: gray;
    }

</style>

<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_order')) ?>);
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_ebay_log')) ?>);
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_amazon_log')) ?>);
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_walmart_log')) ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Please enter correct Product ID or SKU.' => Mage::helper('M2ePro')->__('Please enter correct Product ID or SKU.'),
        'Please enter correct Product ID.' => Mage::helper('M2ePro')->__('Please enter correct Product ID.')
    )); ?>);

    Event.observe(window, 'load', function() {

        OrderEditItemObj = new OrderEditItem();

    });

</script>