<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Template_Category_Chooser_Tabs_Attribute */

?>

<div id="chooser_attributes">
    <table id="chooser_attributes_table" width="100%">
        <thead>
            <tr>
                <td width="225px"></td>
                <td width="115px"></td>
                <td width="225px"></td>
                <td width="105px"></td>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
