<?php if ($this->isAllowedStep()) : ?>

    <style type="text/css">
        p.want-setup {font-weight: bolder;font-size:1.25em}
    </style>

    <div class="content-header" style="border: none;">
        <table cellspacing="0">
            <tr>
                <td><h3>eBay Categories Settings</h3></td>
            </tr>
        </table>
    </div>
    <div style="padding-bottom: 20px;">
        <div>
            <p><?php echo Mage::helper('M2ePro')->__('You have to assign eBay Category with Item Specifics to each Product you are going to list. Click  <a href=\'%url%\' target="_blank">here</a> to find out more.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/BQAJAQ#SellonanothereBaySite-Step4"Categories"')
            ); ?></p>
        </div>

        <div><p class="want-setup"><?php echo Mage::helper('M2ePro')->__('Do you want to set them now?'); ?><p></div>
    </div>

    <div class="clear"></div>

    <div class="content-footer">
        <div style="height: 25px;"></div>
        <div style="position: absolute; text-align: right; bottom: 0; padding: 10px 0 10px 0; background: #ffffff; width: 785px;">
            <span style="padding-left: 10px;"><?php echo $this->getChildHtml('back_button'); ?></span>
            <div style="display: inline-block;"></div>
            <span style="padding-left: 10px;"><?php echo $this->getChildHtml('no_button'); ?></span>
            <div style="display: inline-block;"></div>
            <span style="padding-left: 10px;"><?php echo $this->getChildHtml('yes_button'); ?></span>
        </div>
    </div>

<?php endif; ?>