<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Transferring_Step_Tutorial */

?>

<?php if ($this->isAllowedStep()) : ?>
    <script type="text/javascript">

        VideoTutorialObj = new VideoTutorial(
            'video_tutorial_pop_up',
            '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Sell on Another Marketplace')); ?>',
            function() {}
        );

    </script>

    <div class="content-header" style="border: none; margin-bottom: 0">
        <table cellspacing="0">
            <tr>
                <td><h3><?php echo Mage::helper('M2ePro')->__('Sell on Another Marketplace'); ?></h3></td>
            </tr>
        </table>
    </div>

    <div style="padding-bottom: 10px;">
        <table>
            <tr>
                <td style="padding: 10px 0 0 30px">
                    <p><?php echo Mage::helper('M2ePro')->__('You are going to sell the selected product(s) on another Marketplace. Press <strong>Confirm</strong> to proceed.<br/><br/>
                   More details about the feature can be found  <a href="%url%" target="_blank">here</a>.',
                        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'x/BQAJAQ')
                    ); ?></p>
                </td>
            </tr>
        </table>
    </div>

    <div class="content-footer">
        <div style="height: 25px;"></div>
        <div style="position: absolute; text-align: right; bottom: 0; padding: 10px 0 10px 0; width: 780px; margin-bottom: 12px">
            <span style="padding-left: 10px;"><?php echo $this->getChildHtml('confirm_button'); ?></span>
        </div>
    </div>

    <div id="video_tutorial_pop_up" style="display: none;">
        <div class="player_container" style="margin: 20px 5px; ">
            <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/tFgFpm3O5NU?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/tFgFpm3O5NU?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
        </div>
    </div>
<?php endif; ?>