<div id="block_notice_ebay_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('In-Store Pickup Management'); ?>">
    <p>
        <?php echo Mage::helper('M2ePro')->__('
            In this section, you can <strong>review</strong> Store and Product details as well as Product Quantity
            and Logs.<br/>
            Press <strong>Assign Products to Stores</strong> button to add new Products to the selected Store for
            In-Store Pickup Service.<br/>
            If you want to <strong>unassign</strong> the Product from the Store you can use a <strong>Unassign Option</strong>
            from the Actions bulk at the top of the Grid.
        '); ?>
    </p>

</div>