<div id="block_notice_buy_accounts_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    On this Page you have to fill in General information on your Rakuten.com Account and provide all necessary accesses for the further work.<br/><br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/ooMVAQ')
    ); ?>
</div>

<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

if (isset($formData['other_listings_mapping_settings'])) {
    $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
}

$defaults = array(
    'title' => '',
    'web_login' => '',
    'ftp_login' => '',
    'ftp_inventory_access' => 0,
    'ftp_new_sku_access' => 0,
    'ftp_orders_access' => 0
);

$formData = array_merge($defaults, $formData);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Buy_Account'); ?>,
        'Ess_M2ePro_Model_Buy_Account'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Buy'); ?>,
        'Ess_M2ePro_Helper_Component_Buy'
    );

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_common_buy_account')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_common_buy_account/save', array('id' => $this->getRequest()->getParam('id'))),
        'deleteAction' => $this->getUrl('M2ePro/adminhtml_common_buy_account/delete', array('id' => $this->getRequest()->getParam('id')))
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.' => Mage::helper('M2ePro')->__('Be attentive! By Deleting Account you delete all information on it from M2E Pro Server. This will cause inappropriate work of all Accounts\' copies.'),
        'Invalid format of Seller ID field. It must be numeric.' => Mage::helper('M2ePro')->__('Invalid format of Seller ID field. It must be numeric.')
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        BuyAccountHandlerObj = new CommonBuyAccountHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        <?php if ($isEdit) : ?>
            $('web_login').observe('change', function(){BuyAccountHandlerObj.update_password('web');});
            $('ftp_login').observe('change', function(){BuyAccountHandlerObj.update_password('ftp');});
        <?php endif; ?>
    });
    //-----------------------------

</script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'The specified Title is already used for other Account. Account Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Account. Account Title must be unique.'),
        'You must enable Marketplace first.' => Mage::helper('M2ePro')->__('You must enable Marketplace first.'),
        'M2E Pro was not able to get access to the Rakuten.com Account. Please, make sure, that you enter correct Rakuten.com Seller Tools login and password.' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Rakuten.com Account. Please, make sure, that you enter correct Rakuten.com Seller Tools login and password.'),
        'M2E Pro was not able to get access to the Rakuten.com Account. Please, make sure, that you enter correct Rakuten.com FTP login and password.' => Mage::helper('M2ePro')->__('M2E Pro was not able to get access to the Rakuten.com Account. Please, make sure, that you enter correct Rakuten.com FTP login and password.')
    )); ?>);

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_buy_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or Identifier of Rakuten.com Account for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if (!empty($formData['seller_id'])) : ?>
<div class="entry-edit" id="magento_block_buy_accounts_access_details">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Access Details'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr id="buy_account_access_details">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Seller ID'); ?>: </label>
                    </td>
                    <td class="value">
                        <input id="seller_id" type="text" name="seller_id" disabled="disabled" value="<?php echo $formData['seller_id'];?>" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>
            </table>

        </div>
    </div>

</div>
<?php endif; ?>

<?php if (!$this->marketplace) { ?>
<div class="entry-edit" id="magento_block_buy_accounts_general_none_marketplace">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Marketplace is disabled'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <div id="block_notice_buy_accounts_general_marketplaces_access_none" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Disable Marketplace'); ?>" collapseable="no" always_show="yes" hideblock="no">
                <?php echo Mage::helper('M2ePro')->__('You must select and Update Rakuten.com Marketplace to get access to this Section.'); ?>
            </div>
            <input type="hidden" class="M2ePro-marketplace-disabled" value="" />
        </div>
    </div>

</div>
<?php } else { ?>

<div class="entry-edit" id="magento_block_buy_accounts_general_web_access">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Web Access'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="web_login"><?php echo Mage::helper('M2ePro')->__('Login'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="web_login" name="web_login" type="text" value="<?php echo $formData['web_login'] ?>" class="input-text required-entry M2ePro-web-access" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Login to your Rakuten.com Account.'); ?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="web_password"><?php echo Mage::helper('M2ePro')->__('Password'); ?>: <span id="web_password_required" class="required" <?php if ($isEdit) echo 'style="display: none;"' ?>>*</span></label>
                    </td>
                    <td class="value" id="web_password_button"  <?php if (!$isEdit) echo 'style="display: none;"' ?>>
                        <?php echo $this->getChildHtml('buy_update_web_password') ?>
                    </td>
                    <td class="value" id="web_password_input"  <?php if ($isEdit) echo 'style="display: none;"' ?>>
                        <input id="web_password" name="web_password" type="password" class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Password to your Rakuten.com Account.'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_accounts_general_ftp_access">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('FTP Access'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_buy_accounts_general_ftp_access" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('FTP Access'); ?>">
                <?php
 echo Mage::helper('M2ePro')->__('To get FTP credentials, email the Rakuten.com merchant integration team at
 <a href="mailto:mp-integration@mail.rakuten.com">mp-integration@mail.rakuten.com</a> with your Seller ID and Rakuten.com login email address.'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="ftp_login"><?php echo Mage::helper('M2ePro')->__('Login'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="ftp_login" name="ftp_login" type="text" value="<?php echo $formData['ftp_login'] ?>" class="input-text required-entry M2ePro-ftp-access" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Login to your FTP panel.'); ?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="ftp_password"><?php echo Mage::helper('M2ePro')->__('Password'); ?>: <span id="ftp_password_required" class="required" <?php if ($isEdit) echo 'style="display: none;"' ?>>*</span></label>
                    </td>
                    <td class="value" id="ftp_password_button"  <?php if (!$isEdit) echo 'style="display: none;"' ?>>
                        <?php echo $this->getChildHtml('buy_update_ftp_password') ?>
                    </td>
                    <td class="value" id="ftp_password_input"  <?php if ($isEdit) echo 'style="display: none;"' ?>>
                        <input id="ftp_password" name="ftp_password" type="password" class="input-text M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Password to your FTP panel.'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_accounts_general_ftp_accesses">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Inventory, Orders And New SKU FTP Accesses'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <div id="block_notice_buy_accounts_general_ftp_accesses" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('FTP Accesses'); ?>">
                <?php echo Mage::helper('M2ePro')->__('All these Actions must be allowed to your Rakuten.com Account by Rakuten first.'); ?>
            </div>
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="ftp_inventory_access"><?php echo Mage::helper('M2ePro')->__('FTP Inventory Access'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="ftp_inventory_access" name="ftp_inventory_access">
                            <option value="0" <?php if ($formData['ftp_inventory_access'] == 0) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['ftp_inventory_access'] == 1) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Set <i>Yes</i>, if you have enabled Inventory Generation Option on your FTP.'); ?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="ftp_orders_access"><?php echo Mage::helper('M2ePro')->__('FTP Orders Access'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="ftp_orders_access" name="ftp_orders_access">
                            <option value="0" <?php if ($formData['ftp_orders_access'] == 0) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['ftp_orders_access'] == 1) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Set <i>Yes</i>, if you have enabled Orders Generation Option on your FTP.'); ?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="ftp_new_sku_access"><?php echo Mage::helper('M2ePro')->__('FTP New SKU Access'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="ftp_new_sku_access" name="ftp_new_sku_access">
                            <option value="0" <?php if ($formData['ftp_new_sku_access'] == 0) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['ftp_new_sku_access'] == 1) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Set <i>Yes</i>, if you have enabled new SKU Creation Option on your FTP.
                            <br/><b>Note:</b> The access of getting new SKU must be taken from Rakuten.com'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<?php } ?>
