<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Template_Category_Main */

?>

<div id="templateCategory_pop_up_content">
    <div style="padding: 5px 0;">

        <div id="block_notice_walmart_new_asin_category_policy_popup_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Assign Category Policy'); ?>">
            <?php echo Mage::helper('M2ePro')->__(
                'From the list below, select the relevant Category Policy for your Products.<br>
                Press Add New Category Policy, to create a new Category Policy template.<br><br>

                The detailed information can be found <a href="%url%" target="_blank">here</a>.',

                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'walmart-integration')
            ); ?>
        </div>

        <div id="template_category_grid" style="margin: 10px auto; height: 375px !important; overflow-y: auto; overflow-x: hidden;">
        </div>

    </div>
</div>