<?php

$startWizardLink = $this->getUrl("*/adminhtml_wizard_ebayProductDetails");

?>

<div class="wizard-note">

    <div>
        <?php

            echo Mage::helper('M2ePro')->__(
                'Please <a href="%url_1%">resynchronize</a> eBay Sites Data to work with extension. It should be updated because eBay seriously changed the policy of using eBay Catalog Identifiers.',
                $startWizardLink
            );

        ?>
    </div>

</div>