<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Wizard_EbayProductDetails_Notification $this */

$startWizardLink = $this->getUrl("*/adminhtml_wizard_ebayProductDetails");

?>

<div class="wizard-note">

    <div>
        <?php

            echo Mage::helper('M2ePro')->__(
                'Please <a href="%url_1%">resynchronize</a> eBay Sites Data to work with extension. It should be updated because eBay seriously changed the policy of using eBay Catalog Identifiers.',
                $startWizardLink
            );

        ?>
    </div>

</div>