<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Search_Help */

?>

<div id="block_notice_walmart_listing_search_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Items'); ?>">

    <?php echo Mage::helper('M2ePro')->__('
        On this page, you can review the Items from both M2E Pro and Unmanaged Listings.<br/>
        Filter the records by the Listing Type, Account or Marketplace. Click the Arrow Icon next to the Item to go to the related Listing.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "walmart-integration")
    ); ?>

</div>