<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Account_Edit_Tabs_VCSUploadInvoices */

?>

<div id="block_notice_amazon_accounts_vat_calculation_service" class="block_notices_module"
     title="<?php echo Mage::helper('M2ePro')->__('VCS / Upload Invoices'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        '<strong>Upload Magento Invoices</strong> - M2E Pro will automatically send Magento Invoices/Credit Memos to 
Amazon once they are created in Magento Order.<br /><br/>
<strong>Use VAT Calculation Service</strong> - Amazon will automatically generate and send Invoices to the buyers. 
Switch <i>Disable Magento Invoice Creation</i> option to “Yes” to prevent Invoice duplicates.<br/><br/>
<strong>Note:</strong> You have to be enrolled in Amazon VAT Calculation Service.'
    ); ?>
</div>

<?php
    /** @var Ess_M2ePro_Model_Account $account */
    $account = Mage::helper('M2ePro/Data_Global')->getValue('model_account');

    $formData = $account ? $account->toArray() : array();

    $defaults = Mage::getModel('M2ePro/Amazon_Account_Builder')->getDefaultData();

    $formData = array_merge($defaults, $formData);
    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">
    Event.observe(window, 'load', function() {
        $('auto_invoicing')
            .observe('change', AmazonAccountObj.autoInvoicingModeChange)
            .simulate('change');
    });
</script>

<div class="entry-edit" id="magento_block_amazon_accounts_vat_calculation_service_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="auto_invoicing"><?php echo Mage::helper('M2ePro')->__('Auto-Invoicing');
                        ?>:</label>
                    </td>
                    <td class="value">
                        <select id="auto_invoicing" name="auto_invoicing">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_DISABLED; ?>"
                                <?php if ($formData['auto_invoicing'] ==
                                Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_DISABLED)
                                echo ' selected="selected" '; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <?php if ($account->getChildObject()->getMarketplace()->getChildObject()->isUploadInvoicesAvailable()) { ?>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_UPLOAD_MAGENTO_INVOICES; ?>"
                                    <?php if($formData['auto_invoicing'] ==
                                        Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_UPLOAD_MAGENTO_INVOICES)
                                        echo ' selected="selected" '; ?>><?php echo Mage::helper('M2ePro')->__('Upload Magento Invoices'); ?></option>
                            <?php } ?>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_VAT_CALCULATION_SERVICE; ?>"
                                <?php if($formData['auto_invoicing'] ==
                                Ess_M2ePro_Model_Amazon_Account::MAGENTO_ORDERS_AUTO_INVOICING_VAT_CALCULATION_SERVICE)
                                echo ' selected="selected" '; ?>><?php echo Mage::helper('M2ePro')->__('Use VAT Calculation Service');
                                ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="is_magento_invoice_creation_disabled_tr">
                    <td class="label">
                        <label for="is_magento_invoice_creation_disabled"><?php echo Mage::helper('M2ePro')->__('Disable Magento Invoice Creation'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="is_magento_invoice_creation_disabled" name="is_magento_invoice_creation_disabled">
                            <option value="0" <?php if($formData['is_magento_invoice_creation_disabled'] == 0) echo ' selected="selected" '; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if($formData['is_magento_invoice_creation_disabled'] == 1) echo ' selected="selected" '; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('
                                Set <strong>Yes</strong> to disable Magento Invoice creation for your Amazon Orders.<br />
                                It will prevent the issue of duplicate invoices when VAT Calculation Service is enabled in your Seller Central Account.
                            '); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>
