<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Category_Chooser_Wrapper */

?>

<div id="chooser_main_container" style="padding-top: 15px">
    <?php echo $this->getChildHtml('chooser'); ?>
</div>

<div style="clear: both; padding: 10px"></div>

<div style="position: absolute; bottom: 0; right: 0; margin: 10px 25px;">
    <a id="cancel_button" href="javascript:void(0);"><?php echo Mage::helper('M2ePro')->__('Cancel'); ?></a>
    &nbsp;
    &nbsp;
    &nbsp;
    <?php echo $this->getChildHtml('done'); ?>
</div>

<div style="clear: both"></div>