<!-- ########################################################################################### -->

<div class="box-left">

    <div class="entry-edit" id="magento_block_development_info_module">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Module'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('module') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_location">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Location'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('location') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_license_information">

       <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('License'); ?></h4>
       </div>

       <div class="fieldset">
           <div class="hor-scroll">

               <?php echo $this->getChildHtml('license_information') ?>

           </div>
       </div>

    </div>

    <?php foreach ($this->components as $component => $title) : ?>
        <div class="entry-edit" id="magento_block_development_info_license_component_<?php echo $component; ?>">

            <div class="development_head_container">
                <h4><?php echo Mage::helper('M2ePro')->__($title . ' Access'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <?php echo $this->getChildHtml('license_component_' . $component) ?>

                </div>
            </div>

        </div>
    <?php endforeach; ?>

</div>

<!-- ########################################################################################### -->

<div class="box-right">

    <div class="entry-edit" id="magento_block_development_info_magento">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('Magento'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('magento') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_system">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('System'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('system') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_php">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('PHP'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('php') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_mysql_info">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('MySQL'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('mysql_info') ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_development_info_mysql_summary">

        <div class="development_head_container">
            <h4><?php echo Mage::helper('M2ePro')->__('MySQL Summary'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <?php echo $this->getChildHtml('mysql_summary') ?>

            </div>
        </div>

    </div>

</div>

<!-- ########################################################################################### -->