<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Development_Tabs_Cron */

?>

<div class="entry-edit group_container" id="magento_block_development_cron_system">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('System Tasks'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_cron_system'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_cron_amazon">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Amazon Tasks'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_cron_amazon'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_cron_ebay">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('eBay Tasks'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_cron_ebay'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_cron_walmart">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Walmart Tasks'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_cron_walmart'); ?>
    </div>

</div>