<div class="entry-edit group_container" id="magento_block_development_module_module">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Module'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_module'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_module_synchronization">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Synchronization'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_synchronization'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_module_integration">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_integration'); ?>
    </div>

</div>