<div class="entry-edit group_container" id="magento_block_development_module_integration">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_integration'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_module_integration_ebay">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration [eBay]'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_integration_ebay'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_module_integration_amazon">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Integration [Amazon]'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_module_integration_amazon'); ?>
    </div>

</div>