<div class="entry-edit group_container" id="magento_block_development_tools_m2epro_general">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('M2E Pro (General)'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_tools_m2epro_general'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_tools_m2epro_install">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('M2E Pro (Install / Upgrade)'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_tools_m2epro_install'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_tools_magento">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Magento'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_tools_magento'); ?>
    </div>

</div>

<div class="entry-edit group_container" id="magento_block_development_tools_additional">

    <div class="development_head_container">
        <h4><?php echo Mage::helper('M2ePro')->__('Additional'); ?></h4>
    </div>

    <div class="fieldset">
        <?php echo $this->getChildHtml('development_tools_additional'); ?>
    </div>

</div>