<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_ControlPanel_Inspection_OtherIssues $this */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <?php if ($this->isGdLibraryUnAvailable()) : ?>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('PHP GD Library'); ?>: </label>
            </td>
            <td class="value">
                <span style="color: red"><b>Not Installed</b></span>
            </td>
        </tr>
    <?php endif; ?>

    <?php if ($this->isZendOpcacheAvailable()) : ?>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Zend Opcache'); ?>: </label>
            </td>
            <td class="value">
                <span style="color: red"><b>Enabled</b></span>
            </td>
        </tr>
    <?php endif; ?>

    <?php if ($this->isSystemLogNotEmpty()) : ?>
            <tr>
                <td class="label">
                    <label><?php echo Mage::helper('M2ePro')->__('System Log'); ?>: </label>
                </td>
                <td class="value">
                    <a style="margin-left: 10px;" href="<?php echo $this->getUrl('*/adminhtml_controlPanel_database/manageTable', array('table' => 'm2epro_system_log')); ?>">Show</a>
                </td>
            </tr>
        <?php endif; ?>

</table>