<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Inspection_Requirements */

/** @var Ess_M2ePro_Model_Requirements_Manager $manager */
$manager = Mage::getModel('M2ePro/Requirements_Manager');

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr style="height: 37px;">
        <td class="label" style="width:200px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Properties'); ?></strong>
        </td>
        <td class="value" style="width:250px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Minimum / Recommended Value'); ?></strong>
        </td>
        <td class="value" style="width:150px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Configuration Value'); ?></strong>
        </td>
        <td class="value" style="width:150px;">
        </td>
    </tr>

    <?php foreach($manager->getChecks() as $check) { ?>
        <?php if ($check->getRenderer()->getHideIfMeet() && $check->isMeet()) : continue; endif; ?>

        <tr>
            <td class="label">
                <label><?php echo $check->getRenderer()->getTitle(); ?></label>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getMin(); ?>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getReal(); ?>
            </td>
            <td class="value">
                <?php echo $check->getRenderer()->getAdditional(); ?>
            </td>
        </tr>
    <?php } ?>

</table>