<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Synchronization_Log_Help */

?>

<div id="block_notice_amazon_logs_synchronizations_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Log contains information about Synchronization task performing.<br><br>

        <strong>Note:</strong> Only errors and warnings are logged.<br><br>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/foIVAQ")
    ); ?>

</div>