<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Product_SourceCategories_Summary_Help */

?>

<div id="ebay_listing_product_sourceCategories_summary_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Magento Categories'); ?>">
    <?php echo Mage::helper('M2ePro')->__('The Quantity of chosen Products in each Category is shown in brackets.
<br/>
If the Product belongs to several Categories, it is shown in each Category. And if you remove the Category with such Product it will be subtracted from
 each Category.'); ?>
</div>