<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Account_PickupStore_Help */

?>

<div id="block_notice_ebay_template" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('My Stores'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        In order to provide In-Store Pickup Shipping Service, first, you need to <strong>add the information</strong>
        about the Stores. Then, you will be able to <strong>specify Products availability</strong> for each of the
        created Stores. The Buyers will see the Item marked as available for In-Store Pickup depending on the
        distance to their location.<br/><br/>

        This Service is available for 3 marketplaces — Australia, United Stated and United Kingdom.
    '); ?>
</div>