<div id="block_notice_wizard_installation_step_settings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Settings Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
    <div>
        <div class="step_container_description" style="float: none;">
            <?php echo Mage::helper('M2ePro')->__('In this Section you can choose the Walmart Settings, on which you are going to sell your Items.  <br/><br/>'); ?>
        </div>
        <div id="settings_container" style="margin-bottom: 10px;">
            <?php echo $this->getChildHtml('wizard_settings_form');?>
        </div>
        <div class="step_container_description" style="float: none;">
            <?php echo Mage::helper('M2ePro')->__('<b>Please Note:</b> you can always enable/disable Settings or resynchronize their data in %settings_path%.', Mage::helper('M2ePro/View_Walmart')->getPageNavigationPath('configuration', 'General')); ?>
        </div>
        <div class="step_container_completed">
            <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
        </div>
        <div class="step_container_incomplete">
            <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Incomplete'); ?></span>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="step_container_buttons">
        <span class="step_skip" style="display:none;"></span>
        <span class="step_process" style="display:none;"><?php echo $this->getChildHtml('process_settings_button'); ?></span>
    </div>
</div>

<script type="text/javascript">

    WizardHandlerObj.addStep('settings', 'block_notice_wizard_installation_step_settings');

</script>