<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Account_Edit_Tabs_Order_ExcludedStates */

?>

<div class="entry-edit" id="magento_block_amazon_accounts_magento_orders_listings" style="margin-top: 10px;" collapseable="no">

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <?php foreach ($this->getStatesList() as $column) : ?>
                        <td class="value">
                            <?php foreach ($column as $code => $name) : ?>
                                <div class="checkbox_container excluded_states" style="display: block; margin: 5px;">
                                    <input class="excluded_state_checkbox" type="checkbox" value="<?php echo $code; ?>" <?php if (in_array($code, $this->getSelectedStates())): ?>checked="checked"<?php endif; ?>/>
                                    <label><?php echo $name; ?></label>
                                </div>
                            <?php endforeach; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </table>
        </div>
    </div>
</div>

<div style="float: right; margin-top: 5px; margin-bottom: 20px;">
    <?php echo $this->getChildHtml('excluded_states_close_btn'); ?>
</div>