<?php $url = $this->isEditMode() ? Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(Ess_M2ePro_Helper_View_Ebay::NICK, 'Edit+Synchronization+Listing+Settings') :
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, 'pages/viewpage.action?pageId=17367081');
?>
<div id="ebay_template_edit_synchronization_help" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Synchronization Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('Sync your eBay Accounts and Magento Inventory so you are always in control of your Stock  and Inventory.'); ?></p>
    <?php echo Mage::helper('M2ePro')->__(
        'There are 4 sets of synchronisation Rules:<br/>
        <ul class="list">
            <li style="list-style: decimal !important;">List Rules - define which Items to list on eBay</li>
            <li style="list-style: decimal !important;">Revise Rules - define when eBay Listings should be Revised</li>
            <li style="list-style: decimal !important;">Relist Rules - define when eBay Listings should be Relisted</li>
            <li style="list-style: decimal !important;">Stop Rules - define when eBay Listings should be Stopped</li>
        </ul>
        <b>Note:</b> Settings made here only take effect if <b>Inventory Synchronization</b> is enabled in Configuration > Synchronization.</br></br>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.', $url
    ); ?>
</div>