<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Wizard_RemovedEbay3rdParty_Notification $this */

$completeLink = $this->getUrl("*/adminhtml_wizard_removedEbay3rdParty/complete");

?>

<div class="wizard-note">

    <a class="wizard-close" href="javascript:void(0);" onclick="WizardHandlerObj.complete('<?php echo $completeLink; ?>');" title="<?php echo Mage::helper('M2ePro')->__('Close') ?>">&times;</a>

    <div>
        <?php echo Mage::helper('M2ePro')->__('
            M2E Pro does not update the Channel Items imported into the 3rd Party Listings. The ability to synchronize Magento Product changes for the 3rd Party Listings is not available.<br/><br/>
            Only after the 3rd party Listings are Mapped to Magento Products and Moved to M2E Pro Listing, the Extension will start synchronizing the Product changes to the Channel automatically.<br/><br/>

            <a href="javascript:void(0);" onclick="WizardHandlerObj.complete(\'%url_1%\');">Hide message.</a>
        ', $completeLink
        );?>
    </div>

</div>