<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<?php if ($this->getPaymentMethod()) { ?>
<?php echo $this->getPaymentMethod(); ?>{{pdf_row_separator}}
<?php } ?>

<?php if ($this->getChannelOrderId()) { ?>
<?php echo Mage::helper('M2ePro')->__('Order ID') . ': ' . $this->getChannelOrderId() ?>{{pdf_row_separator}}
<?php } ?>