<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Listing_Product_Help */

?>

<div id="block_notice_amazon_listings_add_products" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Displayed Products have the same Attribute Set as the Listing you are going to add them to.<br/><br/>
    <b>Note:</b> A Product can be added to the Listing only once. If a Product was added to the Listing earlier, it will not be displayed. '); ?>
</div>