<div id="block_notice_common_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    This Section allows you to set preferences for automatic update of Products on Channel.<br/><br/>

    You have to <strong>Enable/Disable</strong> automatic Synchronization Tasks for List/Relist/Revise/Stop Rules of Synchronization Policy used for Products.<br/><br/>

    <strong>Note:</strong> You can start the Synchronization manually by clicking Synchronize Button.
');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Synchronization')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/k4cVAQ'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/m4cVAQ'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>