<div id="block_notice_wizard_installation_description" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

    <?php echo Mage::helper('M2ePro')->__('
        <strong>You have successfully installed M2E Pro v. %version%.</strong><br/><br/>
        M2E Pro Magento Extension allows to connect your Magento Store to the biggest e-commerce platforms such as Amazon, eBay and Rakuten.com. <br/>
        You will be now taken through the Wizard, which will help you to fulfill Primary Initialization of M2E Pro.',
        Mage::helper('M2ePro/Module')->getVersion());
    ?>

</div>