<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<div id="next_step_warning_popup_content" style="margin-bottom: 20px;">

    <div style="margin: 10px;">
        <?php echo Mage::helper('M2ePro')->__(
            'You have not assigned Description Policy to <span class="failed_count"></span> of <span class="total_count"></span> Product(s).<br/><br/>

            To set Description Policy to <span class="failed_count"></span> Product(s) now, click <strong>Cancel</strong> and complete the configurations.
            Otherwise, click <strong>Continue</strong>.<br/>
            You will be able to assign Description Policy to these Products later in the Settings View Mode of M2E Pro Listing.'
        ); ?>
    </div>

    <div style="text-align: right">
        <a href="javascript:"
            onclick="nextStepWarningPopup.close();"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>

</div>