<div id="block_notice_ebay_logs_other_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains all information about Actions, which were done on 3rd Party Listings.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/MAAJAQ#Logs.-3rdPartyListingsLog(advancedmodeonly)')
    ); ?>
</div>