<div id="next_step_warning_popup_content" style="display: none">

    <div style="margin: 10px; height: 155px">
        <?php echo Mage::helper('M2ePro')->__(
            '<b>Warning:</b> There are <span id="failed_count"></span> Product(s) of <span id="total_count"></span> which have no Primary eBay Category specified.<br/><br/>
            To add Primary eBay Categories now, click <b>Cancel</b> then choose the Edit Category Action for the Products which need them.<br/><br/>
            If you\'re not ready to add Primary eBay Categories yet or are not sure which Category to choose, click <b>Continue</b>.
            You will have a chance to add Categories later in the M2E Pro Listing Settings.'
        ); ?>
    </div>

    <div style="text-align: right">
        <a href="javascript:"
            onclick="EbayListingCategoryProductGridHandlerObj.nextStepWarningPopup.hide();"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>

</div>