<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Marketplace_Help */

?>

<div id="block_notice_walmart_marketplaces_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Marketplaces'); ?>">

    <?php echo Mage::helper('M2ePro')->__('
        In this section, you can set up Walmart Marketplaces you will work with. Enable the required Marketplaces and press <i>Save</i>. The Marketplace data will be downloaded and synchronized with your M2E Pro installation.<br/><br/>

        It is recommended to update Marketplaces when any related changes are announced by Walmart. To do this, press <i>Update All Now</i>.<br/><br/>
        
        <b>Note:</b> installation and update processes might be a time-consuming depending on the number of enabled Marketplaces and your Server Environment.<br/><br/>
        
        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "walmart-integration")
    ); ?>

</div>