<div id="common_listing_product_sourceCategories_summary_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Magento Categories'); ?>">
    <?php echo Mage::helper('M2ePro')->__('The Quantity of chosen Products in each Category is shown in brackets.  <br/>
    If the Product belongs to several Categories, it is shown in each Category. And if you remove the Category with such Product it will be subtracted from each Category.'); ?>
</div>