<div id="block_notice_ebay_template" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows the Policies you\'re currently using in your M2E Pro Listings.<br/><br/>
        Click the line of the Policy in the Table below to <b>Edit</b> the Policy. You can <b>Delete</b> Policy only if it\'s not already being used for an M2E Pro Listing.<br/><br/>
        To add a new Policy, click the <b>Add Policy</b> Button.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/DwAJAQ')
    ); ?>
</div>