<div id="block_notice_common_listing_search_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This Page shows all <strong>Products</strong> of M2E Pro Listings and 3rd Party Listing.<br/><br/>
        Use the Filters to find the Product you want to manage. Clicking the Arrows Icon in the Manage Column will take you to the M2E Pro Listing\'s Products Page.'
        );

        $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
        if (count($components) == 1) : ?>
            <?php echo Mage::helper('M2ePro')->__('
                <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Search+Products')
            ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
                <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
                <a target="_blank" href="%url2%">%buy%</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/l4gVAQ'),
                Mage::helper('M2ePro/Component_Amazon')->getTitle(),
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/84sVAQ'),
                Mage::helper('M2ePro/Component_Buy')->getTitle()
            ); ?>
        <?php endif; ?>
</div>