<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Log_Grid_Summary */

?>

<span style="float:right;">
    <a title="<?php echo $this->getTip(); ?>"
       id="grid_help_icon_open_<?php echo $this->getEntityId(); ?>"
       href="javascript:void(0);"
       onclick="<?php echo $this->getViewHelpHandler(); ?>('<?php echo $this->getEntityId(); ?>', '<?php echo $this->getEncodedRows(); ?>', <?php echo $this->getHideViewLogLink(); ?>)">
        <img src="<?php echo $this->getIconSrc(); ?>" alt="<?php echo $this->getTip(); ?>" />
    </a>
    <a title="<?php echo $this->getTip(); ?>"
       id="grid_help_icon_close_<?php echo $this->getEntityId(); ?>"
       style="display: none;"
       href="javascript:void(0);"
       onclick="<?php echo $this->getCloseHelpHandler(); ?>('<?php echo $this->getEntityId(); ?>')">
        <img src="<?php echo $this->getIconSrc(); ?>" alt="<?php echo $this->getTip(); ?>" />
    </a>
</span>