<style type="text/css">
    #magento_block_ebay_category_specific_item_specifics table td, #magento_block_ebay_category_specific_item_specifics table th {
        padding: 5px;
    }

    #magento_block_ebay_category_specific_item_specifics td.label, #magento_block_ebay_category_specific_item_specifics td.label {
        width: 100px;
    }
</style>

<div id="specific_main_container" style="padding-top: 15px">
    <?php echo $this->getChildHtml('specific'); ?>
</div>

<div style="clear: both; padding: 10px"></div>

<div style="float: right; margin-bottom: 10px;">
    <a id="cancel_button" href="javascript: void(0);"><?php echo Mage::helper('M2ePro')->__('Cancel'); ?></a>
    &nbsp;
    &nbsp;
    &nbsp;
    <?php echo $this->getChildHtml('done'); ?>
</div>

<div style="clear: both"></div>