<div id="block_notice_ebay_listing_settings_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Set Products Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('Keep the existing M2E Pro Listing Settings or customise these Settings for the Products shown below.'); ?></p>
    <p><?php echo Mage::helper('M2ePro')->__('You can edit Settings for a single Product by choosing necessary edit Action on appropriate line of the Grid<br/>
        or edit and set the same Settings for several Products Items: select Items and choose necessary Action from the Actions Dropdown Menu.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/RwAJAQ')
        ); ?></p>
</div>