<div id="block_notice_common_orders_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php
    echo Mage::helper('M2ePro')->__('This Page contains all Orders.<br/><br/>
    Use Accounts Dropdown to filter Orders by Accounts.
    If Magento Order, Invoice or / and Shipment was not created automatically,
    you can create them manually by using appropriate Options in the <strong>Action</strong> Dropdown.<br/><br/>
    <b>Note:</b> Automatic creation of Magento Orders, Invoices, and Shipments executes according to <i class="underline">Accounts Settings</i> in (%menu_path%).',
        Mage::helper('M2ePro/View_Common')->getPageNavigationPath('configuration', 'Accounts', '', '[Needed Account] > Orders Tab')
    );

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
        <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Sales+and+Orders+Overview')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/cYIVAQ'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/hYMVAQ'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>