<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Listing_Product_Add_SearchAsin_NotCompleted */

?>

<div id="asin_search_not_completed_popup" style="display: none">
    <div style="margin: 10px; height: 160px">
        <p><?php echo Mage::helper('M2ePro')->__("
                You didn't finish adding Products to the Listing.<br/><br/>
                To add selected Products to the Listing, you need to specify the required information first.
                Once you're done, click <strong>Continue</strong>.<br/><br/>
                If you don't want to add selected Products to the Listing, click <strong>Back</strong> to return
                to the previous step. Or <strong>Cancel</strong> the adding process to return to the Listing.
            ") ?></p>
    </div>

    <div class="clear"></div>
    <div class="right">
        <?php echo $this->getChildHtml('closeBtn'); ?>
    </div>
    <div class="clear"></div>
</div>