<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Template_Edit_General_Help */

?>

<?php $url = $this->isEditMode() ? Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'policy-set-up') :
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'step-2-policies');
?>
<div id="ebay_template_edit_general_help" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Payment and Shipping Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__(
        'Choose the Payment, Domestic and International Shipping Options you want to use for Products Listed on eBay using this M2E Pro Listing.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.', $url
    ); ?></p>
</div>