<script>
    M2ePro.translator.add(<?php echo json_encode(array(
        'Migration Information' => Mage::helper('M2ePro')->__('Migration Information')
    )); ?>);

    Event.observe(window, 'load', function() {
        AdvancedHandlerObj = new ConfigurationAdvancedHandler();
    });
</script>

<?php
if (Mage::helper('M2ePro/Module')->isDisabled()) {
    $confirmContent = 'Are you sure ?';
    $buttonText = 'Enable Module and Automatic Synchronization';
} else {
    $confirmContent = <<<HTML
<p>In case you confirm the Module disabling, the M2E Pro dynamic tasks run by
    Cron will be stopped and the M2E Pro Interface will be blocked.</p>

<p><b>Note</b>: You can re-enable it anytime you would like by clicking on the <strong>Proceed</strong>
    button for <strong>Enable Module and Automatic Synchronization</strong> option.</p>
HTML;
    $buttonText = 'Stop Module and Automatic Synchronization';
}
?>

<div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Disable/Enable Module'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                <tr>
                    <td class="label" style="width: auto">
                        <label style="width: auto"><?php echo Mage::helper('M2ePro')->__($buttonText); ?>: </label>
                    </td>

                    <td class="value">
                        <?php echo $this->getChildHtml('proceed_module_mode_button'); ?>
                    </td>
                </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>

<script type="M2ePro/template" id="module_mode_information_content">

    <div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

        <div style="margin-top: 10px">
            <p>
                <?php echo Mage::helper('M2ePro')->__($confirmContent); ?>
            </p>
        </div>

        <div style="float: right; margin: 0 0 1em;">
            <a href="#" onclick="moduleModePopup.close();">Close</a>
            &nbsp;
            &nbsp;
            &nbsp;
            <?php echo $this->getChildHtml('confirm_module_mode_button');?>
        </div>

    </div>

</script>

<div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Migration to Magento v2.x'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                <tr>
                    <td class="label" style="width: auto">
                        <label style="width: auto"><?php echo Mage::helper('M2ePro')->__('Stop Module and prepare for migration'); ?>: </label>
                    </td>

                    <td class="value">
                        <?php echo $this->getChildHtml('proceed_button'); ?>
                    </td>
                </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>

<script type="M2ePro/template" id="information_content">

    <div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

        <div style="margin-top: 10px">
            <p>
                <?php echo Mage::helper('M2ePro')->__('
                    You are going to run the migration of M2E Pro data from Magento v1.x to Magento v2.x.<br>
                    Before you proceed, please read the <a href="%url%" target="_blank">Migration Guide</a>.
                    <br><br>
                    If you are ready to start, please click <strong>Confirm</strong>. It will stop the dynamic Cron tasks,
                    put M2E Pro under maintenance and prepare its database for the migration.
                    Please wait for at least 15 minutes until the process is fully completed.
                    <br><br>
                    <strong>Note:</strong> Once you confirm the migration running, the process cannot be rolled back.
                ', Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/EgA9AQ')); ?>
            </p>
        </div>

        <div style="float: right; margin: 0 0 1em;">
            <a href="#" onclick="adnvancedPopup.close();">Close</a>
            &nbsp;
            &nbsp;
            &nbsp;
            <?php echo $this->getChildHtml('confirm_button');?>
        </div>

    </div>

</script>