<?php
    $urlComponents = Mage::helper('M2ePro/Component')->getActiveComponents();
    $componentForUrl = count($urlComponents) == 1 ? array_shift($urlComponents) : Ess_M2ePro_Helper_Component_Ebay::NICK;
?>
<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Amazon'); ?>,'Ess_M2ePro_Helper_Component_Amazon');

    M2ePro.translator.add(<?php echo json_encode(array(
        'Default Component should be enabled.' => Mage::helper('M2ePro')->__('Default Component should be enabled.')
    )); ?>);

    Event.observe(window, 'load', function() {
        ComponentsHandlerObj = new ConfigurationComponentsHandler();

        ControlPanelHandlerObj = new DevelopmentControlPanelHandler();

        ComponentsHandlerObj.componentsTitles = <?php echo $this->getComponentsTitles(); ?>
    });
    //-----------------------------

</script>

<style>
    .columns .form-list td.value {
        width: 280px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div id="magento_block_configuration_ebay_channel">

        <div id="block_notice_configuration_ebay_channel" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Channels'); ?>">
            <p><?php echo Mage::helper('M2ePro')->__('
                <b>Enable</b> the Channels you want to sell on, then click <b>Save Config</b>.<br/><br/>
                More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/CwAJAQ#GlobalSettings-Channels')
                ); ?></p>
        </div>

        <div class="entry-edit" id="magento_block_configuration_channel_status">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Channel'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>

                        <tbody>

                        <?php if ($this->component_ebay_allowed) { ?>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('M2ePro')->__('Status'); ?>: </label>
                                </td>
                                <td class="value">
                                    <select id="component_ebay_mode" name="component_ebay_mode">
                                        <option value="0" <?php if (!$this->component_ebay_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                        <option value="1" <?php if ($this->component_ebay_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('eBay Channel Status.') ?></span>
                                    </p>
                                </td>
                            </tr>

                        <?php } ?>

                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_configuration_settings_other">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Amazon Channel'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                    <?php if ($this->component_amazon_allowed) { ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Status'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="component_amazon_mode" name="component_amazon_mode" class="M2ePro-component-other">
                                    <option value="0" <?php if (!$this->component_amazon_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                    <option value="1" <?php if ($this->component_amazon_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Amazon Channel Status.') ?></span>
                                </p>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_configuration_walmart_channel">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Walmart Channel'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                    <?php if ($this->component_walmart_allowed) { ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Status'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="component_walmart_mode" name="component_walmart_mode" class="M2ePro-component-other">
                                    <option value="0" <?php if (!$this->component_walmart_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                    <option value="1" <?php if ($this->component_walmart_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Walmart Channel Status.') ?></span>
                                </p>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

</form>