<div id="block_notice_configuration_license" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('License'); ?>">
    <?php
    $activeComponents = Mage::helper('M2ePro/Component')->getActiveComponents();
    $componentForUrl = count($activeComponents) == 1 ? array_shift($activeComponents) : Ess_M2ePro_Helper_Component_Ebay::NICK;

    $tempString = Mage::helper('M2ePro')->__('M2E Pro Extension requires activation for its work.<br/><br/>
    To get the License Key click the <span style="text-decoration: underline;">Manage License</span> link and follow the instructions.<br/>
    When you receive your License Key, press the Enter Button, enter your License Key in appeared text field and press Confirm.
    <br/><br/>
    <b>Note:</b> If you have not received the License Key, please contact us <a href="mailto:support@m2epro.com">support@m2epro.com</a>.<br/><br/>
    More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
    Mage::helper('M2ePro/Module_Support')->getDocumentationUrl($componentForUrl, 'Global+Settings#GlobalSettings-License'));
    echo $tempString;
    ?>
</div>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_configuration_license')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_configuration_license/confirmKey')
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'You must get valid License Key.' => Mage::helper('M2ePro')->__('You must get valid License Key.')
    )); ?>);

    Event.observe(window, 'load', function() {
        LicenseHandlerObj = new ConfigurationLicenseHandler();
        ControlPanelHandlerObj = new DevelopmentControlPanelHandler();

        configEditForm = new varienForm('config_edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style>
    .columns .form-list td.value {
        width: 280px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <?php if ($this->key != '' && ($this->licenseData['domain'] == '' || $this->licenseData['ip'] == '' || $this->licenseData['directory'] == '')) : ?>
        <ul style="margin-top: 5px;" class="messages">
            <li class="error-msg">
                <ul>
                    <li>
                        <?php echo Mage::helper('M2ePro')->__('You are trying to use the unknown License Key.'); ?>
                    </li>
                </ul>
            </li>
        </ul>
    <?php endif; ?>

    <div class="entry-edit" id="magento_block_configuration_license_data" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Data'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('License Key'); ?>: </label>
                            </td>
                            <td id="license_text_key_container" class="value">
                                <?php echo $this->key; ?>
                                <?php if ($this->key == '') { echo $this->getChildHtml('enter_key'); } ?>
                                &nbsp;&nbsp;
                            </td>
                            <td id="license_input_key_container" class="value" style="display: none;">
                                <input id="key" name="key" value="<?php echo $this->escapeHtml($this->key); ?>" type="text" class="input-text required-entry" />
                                &nbsp;&nbsp;
                            </td>
                            <td id="change_license_key_container" class="value" <?php if($this->key == '') { ?>style="display: none;"<?php } ?>>
                                <?php echo $this->getChildHtml('change_key'); ?>
                                &nbsp;
                                <?php echo $this->getChildHtml('refresh_status'); ?>
                            </td>
                            <td id="confirm_license_key_container" class="value" style="display: none;">
                                <?php echo $this->getChildHtml('confirm_key'); ?>
                            </td>
                        </tr>

                        <?php if ($this->licenseData['info']['email'] != '') { ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Associated Email'); ?>: </label>
                            </td>
                            <td class="value">
                                <span><?php echo $this->licenseData['info']['email']; ?></span>
                                <p class="note">
                                    <span>
                                        <?php echo Mage::helper('M2ePro')->__('This e-mail address associated to your License. <br/>
                                        Also you can use this e-mail to enter a <a href="%url%">clients portal</a>',
                                        Mage::helper('M2ePro/Module_Support')->getClientsPortalBaseUrl()); ?>
                                    </span>
                                </p>
                            </td>
                        </tr>
                        <?php } ?>

                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <a href="<?php echo Mage::helper('M2ePro/Module_Support')->getClientsPortalBaseUrl();?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Manage License'); ?></a>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <?php if ($this->licenseData['domain'] != '' || $this->licenseData['ip'] != '' || $this->licenseData['directory'] != '') { ?>

        <div class="entry-edit" id="magento_block_configuration_license_valid" collapseable="no">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Validation'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>

                        <tbody>

                            <?php if ($this->licenseData['domain'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Domain'); ?>: </label>
                                    </td>
                                    <td class="value">

                                        <span <?php echo $this->licenseData['valid']['domain'] ? '' : 'style="color: red;"'?>>
                                            <?php echo $this->licenseData['domain']; ?>
                                        </span>

                                        <?php if (!$this->licenseData['valid']['domain'] &&
                                                  !is_null($this->licenseData['connection']['domain'])): ?>
                                            <span> (<?php echo Mage::helper('M2ePro')->__('Your Domain') . ': ' . Mage::helper('M2ePro')->escapeHtml($this->licenseData['connection']['domain']);?>)</span>
                                        <?php endif;?>
                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->licenseData['ip'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('IP'); ?>: </label>
                                    </td>
                                    <td class="value">

                                        <span <?php echo $this->licenseData['valid']['ip'] ? '' : 'style="color: red;"'?>>
                                            <?php echo $this->licenseData['ip']; ?>
                                        </span>

                                        <?php if (!$this->licenseData['valid']['ip'] &&
                                            !is_null($this->licenseData['connection']['ip'])): ?>
                                            <span> (<?php echo Mage::helper('M2ePro')->__('Your IP') . ': ' . Mage::helper('M2ePro')->escapeHtml($this->licenseData['connection']['ip']);?>)</span>
                                        <?php endif;?>

                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->licenseData['directory'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Directory'); ?>: </label>
                                    </td>
                                    <td class="value">

                                        <span <?php echo $this->licenseData['valid']['directory'] ? '' : 'style="color: red;"'?>>
                                            <?php echo $this->licenseData['directory']; ?>
                                        </span>

                                        <?php if (!$this->licenseData['valid']['directory'] &&
                                            !is_null($this->licenseData['connection']['directory'])): ?>
                                            <span> (<?php echo Mage::helper('M2ePro')->__('Your Directory') . ': ' . Mage::helper('M2ePro')->escapeHtml($this->licenseData['connection']['directory']);?>)</span>
                                        <?php endif;?>

                                    </td>
                                </tr>

                            <?php } ?>

                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    <?php } ?>

</form>