<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Configuration_Linker */

?>

<style type="text/css">
    .global_node {
        padding-bottom: 10px;
    }
</style>

<?php if ($this->getData('show_header')) { ?>

    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td><?php echo $this->getHeaderHtml() ?></td>
                <td class="form-buttons">
                    <?php echo $this->getButtonsHtml() ?>
                </td>
            </tr>
        </table>
    </div>

<?php } ?>

<div id="block_notice_ebay_configuration_global" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Global Settings'); ?>">

    <?php echo Mage::helper('M2ePro')->__('Settings are split into four Categories. Descriptions for each Category are below.');

    if (Mage::helper('M2ePro/View')->isCurrentViewEbay()) : ?>

        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'global-settings')
        ); ?>

    <?php elseif (Mage::helper('M2ePro/View')->isCurrentViewAmazon()) : ?>

        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url%">%amazon%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'global-settings'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle()
        ); ?>

    <?php elseif (Mage::helper('M2ePro/View')->isCurrentViewWalmart()) : ?>

        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>The detailed information can be found <a target="_blank" href="%url%">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'walmart-integration')
        ); ?>

    <?php endif; ?>
</div>

<div class="entry-edit" id="magento_block_ebay_configuration_global">

    <div class="fieldset">
        <div class="hor-scroll">

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getComponentsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Channels');?></a>
                <p>
                    <?php echo Mage::helper('M2ePro')->__('Channel setup.');?>
                </p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getSettingsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('General');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Interface and Synchronization preferences.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLogsClearingUrl(); ?>"
                   target="_blank"><?php echo Mage::helper('M2ePro')->__('Logs &amp; Notifications');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Preferences for Logs history clearing.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLicenseUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Billing Info');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('M2E Pro activation.');?></p>
            </div>

        </div>
    </div>

</div>
