<style type="text/css">
    .global_node {
        padding-bottom: 10px;
    }
</style>

<?php if ($this->getData('show_header')) { ?>

    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td><?php echo $this->getHeaderHtml() ?></td>
                <td class="form-buttons">
                    <?php echo $this->getButtonsHtml() ?>
                </td>
            </tr>
        </table>
    </div>

<?php } ?>

<div id="block_notice_ebay_configuration_global" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Global Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Settings are split into four Categories. Descriptions for each Category are below.');

    if (Mage::helper('M2ePro/View')->isCurrentViewEbay()) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/CwAJAQ')
        ); ?>
    <?php else :

        $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
        if (count($components) == 1) : ?>
            <?php echo Mage::helper('M2ePro')->__('
                <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Global+Settings')
            ); ?>
        <?php else : ?>
            <?php echo Mage::helper('M2ePro')->__('
                <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
                <a target="_blank" href="%url2%">%buy%</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/NYMVAQ'),
                Mage::helper('M2ePro/Component_Amazon')->getTitle(),
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/C4QVAQ'),
                Mage::helper('M2ePro/Component_Buy')->getTitle()
            ); ?>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div class="entry-edit" id="magento_block_ebay_configuration_global">

    <div class="fieldset">
        <div class="hor-scroll">

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getComponentsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Channels');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('%ebay%, %amazon%, %rakuten% Channels activation.',
                    Mage::helper('M2ePro/Component_Ebay')->getTitle(),
                    Mage::helper('M2ePro/Component_Amazon')->getTitle(),
                    Mage::helper('M2ePro/Component_Buy')->getTitle()
                    );?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getSettingsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('General');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Interface and Synchronization preferences.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLogsClearingUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Logs Clearing');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Preferences for Logs history clearing.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLicenseUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('License');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('M2E Pro activation.');?></p>
            </div>

        </div>
    </div>

</div>