<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_PickupStore_Variation_Product_View */

?>

<div id="ebayPickupStoreVariationsGrid" style="height: 450px; margin-top: 10px;">
    <?php
    $url = $this->getUrl('*/adminhtml_ebay_listing_pickupStore_variation_product_show/variationsGrid',
        array(
            'product_id' => $this->getListingProductId(),
            'pickup_store_id' => $this->getPickupStoreId(),
            'filter' => $this->getRequest()->getParam('filter')
        )
    );
    ?>
    <input type="hidden" id="ebayPickupStoreVariationsGridIframeUrl" value="<?php echo $url ?>">
</div>
