<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel */

?>

<style>

    /*  ############################################  */

    .controlPanel_head_container {
        background: #6f8992;
        padding: 2px 10px;
    }

    .controlPanel_head_container h4 {
        padding: 0;
        background: none;
        margin: 0;
        color: #fff;
        font-size: 1em;
        line-height: 18px;
    }

    /*  ############################################  */

    .group_number_td {
        width: 20px !important;
    }

    .group_container .fieldset,
    .group_container {
        #min-height: 250px;
    }

    .group_container {
        float: left;
        min-width: 300px;
        padding: 0;
        margin-right: 15px;
        display: inline-block;
    }

    .group_container table {
        min-width: 220px;
        margin: 5px 8px;
        font-size: 14px;
        line-height: 14px;
    }

    table td a {
        text-decoration: none !important;
    }

    /*  ############################################  */

    .simple_commands_list {
        font-size: 14px;
    }

    .simple_commands_list p {
        padding-left: 10px;
        color: #c0c0c0;
    }

    /*  ############################################  */

</style>

<script type="text/javascript">

    function SetupManagementActionHandler() {

        this.askAdditionalParametersForAction = function(promptString, url, placeHolder)
        {
            var result = prompt(promptString);

            if (result == null) {
                return false;
            }

            url = url.replace(encodeURIComponent('#') + placeHolder + encodeURIComponent('#'), result);
            document.location = url;
        }
    }

    window.setupManagementActionHandler = new SetupManagementActionHandler();

</script>

<div id="controlPanel_container">
    <?php echo $this->getChildHtml('tabs_controlPanel'); ?>
    <div id="controlPanel_tab_container"></div>
</div>