<style>

    /*  ############################################  */

    .development_head_container {
        background: #6f8992;
        padding: 2px 10px;
    }

    .development_head_container h4 {
        padding: 0;
        background: none;
        margin: 0;
        color: #fff;
        font-size: 1em;
        line-height: 18px;
    }

    button.button_development {
        background-color: #FFFFFF !important;
        background-image: url("<?php echo $this->getSkinUrl('images/btn_back_bg.gif')?>") !important;
        border-color: #CCCCCC #AAAAAA #AAAAAA #CCCCCC !important;
        color: #F77812 !important;
    }

    /*  ############################################  */

    .group_number_td {
        width: 20px !important;
    }

    .group_container .fieldset,
    .group_container {
        height: 350px;
    }

    .group_container {
        float: left;
        min-width: 250px;
        padding: 0;
        margin-right: 15px;
    }

    .group_container table {
        min-width: 220px;
        margin: 5px 8px;
        font-size: 14px;
        line-height: 20px;
    }

    /*  ############################################  */

    .simple_commands_list {
        font-size: 14px;
    }

    .simple_commands_list p {
        padding-left: 10px;
        color: #c0c0c0;
    }

    /*  ############################################  */

</style>

<div id="development_container">
    <?php echo $this->getChildHtml('tabs_development'); ?>
    <div id="development_tab_container"></div>
</div>