<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_General */
?>

<script type="text/javascript">

    var BLOCK_NOTICES_SHOW = <?php echo $this->block_notices_show ? 'true' : 'false'; ?>;

    var IS_VIEW_EBAY = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewEbay()); ?>;
    var IS_VIEW_AMAZON = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewAmazon()); ?>;
    var IS_VIEW_WALMART = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewWalmart()); ?>;

    var IS_VIEW_INTEGRATION = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewIntegration()); ?>;
    var IS_VIEW_WIZARD = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewWizard()); ?>;
    var IS_VIEW_CONFIGURATION = <?php echo json_encode(Mage::helper('M2ePro/View')->isCurrentViewConfiguration()); ?>;

    <?php echo $this->getJs()->render(); ?>
    <?php echo $this->getJsPhp()->render(); ?>
    <?php echo $this->getJsTranslator()->render(); ?>
    <?php echo $this->getJsUrls()->render(); ?>

    if (typeof setPageHelpLink != 'undefined') {
        setPageHelpLink('<?php echo $this->getPageHelpLink(); ?>');
    }

</script>

<style type="text/css">
    <?php echo $this->getCss()->render(); ?>
</style>