<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>">
                <h3>M2E Pro is under maintenance</h3>
            </td>
            <td class="form-buttons"></td>
        </tr>
    </table>
</div>

<?php if ($this->getData('is_prepared_for_migration') === true): ?>

    <p>Inventory and Order synchronization is not running. The Module interface is unavailable.</p>
    <p>M2E Pro can be put under maintenance automatically due to the following reasons:</p>

    <ul style="margin-left: 30px;">
        <li style="list-style-type: disc">
            <p>M2E Pro data is being prepared for the migration to Magento v2.x.</p>
        </li>
    </ul>

    Please proceed with the Migration Wizard instructions in your Magento v2.x installation.

<?php else: ?>

    <p>The Module interface is unavailable and the background tasks stop running. Service can be put under maintenance
        automatically due to the following reasons:</p>

    <ul style="margin-left: 30px;">
        <li style="list-style-type: disc">
            <p>Module installation failed, e.g. due to the incorrect installation via Magento Component Manager,
                incompatibility of Magento and its Modules, or other technical issues.</p>
        </li>
        <li style="list-style-type: disc">
            <p>Module upgrade failed, e.g. due to the improper M2E Pro tables updating.</p>
        </li>
    </ul>

    <p>Please contact Support at <a href="mailto:support@m2epro.com" title="support@m2epro.com">support@m2epro.com</a> to
        resolve the issue.</p>

<?php endif; ?>