<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_support')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_support/save')
    )); ?>);

    Event.observe(window, 'load', function() {
        SupportHandlerObj = new SupportHandler();

        ControlPanelHandlerObj = new DevelopmentControlPanelHandler();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
        $('query').focus();

        <?php if ($this->isFromError): ?>
            $('support_results').hide();
        <?php endif; ?>
    });

</script>

<style type="text/css">

    div#support_input_query_container {
        width: 100%;
        text-align: center;
        border: 1px solid grey;
        border-radius: 4px;
        padding: 20px 0;
        margin-bottom: 15px;
    }

    div#support_input_query_container input {
        width: 400px;
        height: 25px;
        border: 1px solid grey;
        border-radius: 3px;
        padding-left: 2px;
    }

    div#support_input_query_container button {
        height: 25px;
        margin-left: 10px;
    }

</style>

<div class="box-left">
    <div id="support_system_requirements_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Requirements'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('system_requirements'); ?>
            </div>
        </div>
    </div>
</div>

<div class="box-right">
    <div id="support_cron_info_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Cron Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('cron_info'); ?>
            </div>
        </div>

    </div>
</div>

<div style="clear: both;"></div>

<div id="block_notice_support" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search the M2E Pro Knowledgebase'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'For immediate help with something on M2E Pro, search the Knowledgebase and Documentation to see if the answer to your query has already been answered.
        If you still can\'t find the help you need after searching, get in touch with our Customer Support Team using the <b>Contact Support</b> form.'
    ); ?>
</div>

<div id="support_input_query_container">
    <input onkeypress="SupportHandlerObj.keyPressQuery(event)" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter keywords to search'); ?>" name="query" id="query">
    <?php echo $this->getChildHtml('user_voice_search'); ?>
    <?php if (Mage::helper('M2ePro/Module_Support')->isTypePremium()) : ?>
        <span style="font-weight: bold; padding-left: 10px;"><?php echo Mage::helper('M2ePro')->__('or'); ?></span>
        <?php echo $this->getChildHtml('force_show_contact_support_button'); ?>
    <?php endif; ?>
</div>

<div id="support_other_container" <?php if (!$this->isFromError): echo 'style="display: none;"'; endif; ?>>
    <?php echo $this->getChildHtml('tabs'); ?>
    <div id="support_tab_container"></div>
</div>