<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Support */

?>

<!-- Initialize FreshworksWidget -->
<script>
    window.fwSettings={
        'widget_id':9000000228
    };
    !function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}();

    FreshworksWidget('prefill', 'ticketForm', {
        custom_fields: {
            cf_summary_info: <?php echo json_encode(Mage::helper('M2ePro/Module_Support')->getSummaryInfo()); ?>,
        }
    });

    FreshworksWidget('hide', 'ticketForm', ['custom_fields.cf_summary_info', 'custom_fields.cf_version']);
</script>
<script type='text/javascript' src='https://widget.freshworks.com/widgets/9000000228.js' async defer></script>
<!--------------------------------->

<div class="box-left">
    <div id="support_system_requirements_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Requirements'); ?></h4>
            <span class="notice-tool-tip-icon" onclick="window.open('<?php echo Mage::helper('M2ePro/Module_Support')->getKnowledgeBaseUrl('1535371'); ?>', '_blank'); Event.stop(event)" style="cursor: pointer;"></span>
        </div>

        <div class="fieldset">
            <div class="hor-scroll" style="min-height: 116px;">
                <?php echo $this->getChildHtml('system_requirements'); ?>
            </div>
        </div>
    </div>
</div>

<div class="box-right">
    <div id="support_version_info_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Version Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('version_info'); ?>
            </div>
        </div>

    </div>

    <div id="support_cron_info_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Cron Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('cron_info'); ?>
            </div>
        </div>

    </div>
</div>