<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Support */

?>

<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_support')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_support/save', array(
            'referrer' => $this->getRequest()->getParam('referrer', NULl)
        ))
    )); ?>);

    Event.observe(window, 'load', function() {
        SupportObj = new Support();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
        $('query').focus();

        <?php if ($this->isFromError): ?>
            $('support_results').hide();
        <?php endif; ?>
    });

</script>

<style type="text/css">

    div#support_input_query_container {
        width: 100%;
        text-align: center;
        border: 1px solid grey;
        border-radius: 4px;
        padding: 20px 0;
        margin-bottom: 15px;
    }

    div#support_input_query_container input {
        width: 400px;
        height: 25px;
        border: 1px solid grey;
        border-radius: 3px;
        padding-left: 2px;
    }

    div#support_input_query_container button {
        height: 25px;
        margin-left: 10px;
    }

</style>

<div class="box-left">
    <div id="support_system_requirements_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Requirements'); ?></h4>
            <span class="notice-tool-tip-icon" onclick="window.open('<?php echo Mage::helper('M2ePro/Module_Support')->getKnowledgeBaseUrl('1535371'); ?>', '_blank'); Event.stop(event)" style="cursor: pointer;"></span>
        </div>

        <div class="fieldset">
            <div class="hor-scroll" style="min-height: 116px;">
                <?php echo $this->getChildHtml('system_requirements'); ?>
            </div>
        </div>
    </div>
</div>

<div class="box-right">
    <div id="support_version_info_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Version Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('version_info'); ?>
            </div>
        </div>

    </div>

    <div id="support_cron_info_container" class="entry-edit">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Cron Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <?php echo $this->getChildHtml('cron_info'); ?>
            </div>
        </div>

    </div>
</div>

<div style="clear: both;"></div>

<div id="block_notice_support" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Get Help'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Find the answers by searching through our Knowledge Base.<br>If you need assistance, submit your request to our Support via the contact form.'
    ); ?>
</div>

<div id="support_input_query_container">
    <input onkeypress="SupportObj.keyPressQuery(event)" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter keywords to search'); ?>" name="query" id="query">
    <?php echo $this->getChildHtml('user_voice_search'); ?>
</div>

<div id="support_other_container" <?php if (!$this->isFromError): echo 'style="display: none;"'; endif; ?>>
    <?php echo $this->getChildHtml('tabs'); ?>
    <div id="support_tab_container"></div>
</div>