<div id="block_notice_common_marketplaces_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Marketplaces'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Section allows you to set up the Marketplaces you will work with.<br/><br/>

    Enable certain Marketplaces and press the <i class="underline">Save</i> Button in the top right corner, all necessary Marketplace data will be downloaded and synchronized with M2E Pro Settings.<br/>
    It is recommended to Update Marketplaces when any Marketplace changes are announced by clicking <i class="underline">Update All Now</i> Button. <br/><br/>
    <b>Note:</b> Installation and Update Processes might be time-consuming, depending on the number of enabled Marketplaces and your Server Environment.
    ');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Marketplaces')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/6YIVAQ'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/1IMVAQ'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>