<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Development_Info_Mysql_Info */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Version'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlVersion; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Server API'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlApi; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Database Name'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlDatabaseName; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Tables Prefix'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlPrefix != '' ? $this->mySqlPrefix : Mage::helper('M2ePro')->__('Disabled'); ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Connection Timeout'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlSettings['connect_timeout']; ?> <?php echo Mage::helper('M2ePro')->__('sec'); ?>.
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Wait Timeout'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlSettings['wait_timeout']; ?> <?php echo Mage::helper('M2ePro')->__('sec'); ?>.
        </td>
    </tr>

</table>