<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Development_Info_Mysql_Summary */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Total Tables'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['magento_tables']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Total Module Tables'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['module_tables']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Total Module Records'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlTotal['module_records']; ?>
        </td>
    </tr>

</table>