<div id="block_notice_common_logs_other_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains all information about Actions, which were done on 3rd Party Listings.');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(array_shift($components), 'Logs#Logs-3rdPartyListingsLog')
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
                <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
                <a target="_blank" href="%url2%">%buy%</a>.',
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/foIVAQ#Logs-3rdPartyListingsLog'),
                Mage::helper('M2ePro/Component_Amazon')->getTitle(),
                Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/iIMVAQ#Logs-3rdPartyListingsLog'),
                Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>