<div id="block_notice_ebay_marketplace" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Sites'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page lists the eBay international Sites that allow you to sell on Marketplaces around the world.<br/><br/>
        <b>Enable</b> the Sites you want to sell on and click <b>Save</b>.
        Please be patient when enabling Sites as this can take some time, depending on how many Sites you are enabling and the speed of your own Server.<br/>
        Click <b>Update Now</b> to update Sites with the most up-to-date information, such as Category structure.<br/><br/>
        If a Site has been <b>Used in Listing(s)</b> you cannot disable it.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/DgAJAQ')
    ); ?>
</div>