<div id="dialog_confirm_container">
    <div class="dialog_confirm_content"></div>
    <div class="dialog_confirm_buttons" style="position: absolute; bottom: 0; right: 0; padding: 10px;">
        <a href="javascript:void(0);" onclick="Dialog.cancelCallback()"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $this->getChildHtml('ok_button') ?>
    </div>
</div>