<?php

    /** @var Ess_M2ePro_Block_Adminhtml_Ebay_Motor_Add $this */

    $compatibleAttribute = Mage::helper('M2ePro/Component_Ebay_Motor_Compatibility')->getAttribute($this->getCompatibilityType());

    $translations = array();
    // M2ePro_TRANSLATIONS
    // Please specify eBay Motors compatibility Attribute in %menu_label% <a target="_blank" href="%url%">General</a>
    $text = 'Please specify eBay Motors compatibility Attribute in %menu_label% <a target="_blank" href="%url%">General</a>';
    $translations[$text] = Mage::helper('M2ePro')->__(
        $text,
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration'),
        $this->getUrl('*/adminhtml_ebay_configuration')
    );

    $translations['Set Note'] = Mage::helper('M2ePro')->__('Set Note');
    $translations['Add Custom Compatible Vehicle'] = Mage::helper('M2ePro')->__('Add Custom Compatible Vehicle');

    // ->__('Please edit Categories Settings for selected Products and select the compatibility attribute.')
    $text = 'Please edit Categories Settings for selected Products and select the compatibility Attribute.';
    $translations[$text] = Mage::helper('M2ePro')->__($text);

    $translations = json_encode($translations);
?>

<style type="text/css">
    #compatibility_grid_container table td, #compatibility_grid_container table th {
        padding: 5px;
    }

    #generate_attribute_content_container td.label {
        width: 100px;
    }

    #generate_attribute_content_container label {
        width: 100px;
    }

    a.remove-custom-created-record-link {
        display: inline-block;
        width: 8px;
        height: 9px;
        margin-left: 3px;
        background-position: center;
        background-repeat: no-repeat;
        background-image: url("<?php echo $this->getSkinUrl('M2ePro/images/delete.png')?>");
    }

</style>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Template_Category'); ?>, 'Ess_M2ePro_Model_Ebay_Template_Category');
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Ebay_Motor_Compatibility'); ?>, 'Ess_M2ePro_Helper_Component_Ebay_Motor_Compatibility');

    M2ePro.url.add(<?php echo json_encode(array(
        'adminhtml_ebay_listing/motorSpecificGrid' => $this->getUrl('*/adminhtml_ebay_listing/motorSpecificGrid'),
        'adminhtml_ebay_listing/motorKtypeGrid' => $this->getUrl('*/adminhtml_ebay_listing/motorKtypeGrid'),
        'adminhtml_ebay_listing/updateMotorsCompatibilityAttributes' => $this->getUrl('*/adminhtml_ebay_listing/updateMotorsCompatibilityAttributes'),
    )) ?>);

    M2ePro.translator.add(<?php echo $translations ?>);

    var init = function() {

        EbayMotorCompatibilityHandlerObj = new EbayMotorCompatibilityHandler(
            <?php echo (int)$this->getRequest()->getParam('id') ?>,
            '<?php echo Mage::helper('M2ePro')->escapeJs($this->getCompatibilityType()) ?>',
            '<?php echo Mage::helper('M2ePro')->escapeJs($this->getCompatibilityGridId()) ?>',
            '<?php echo Mage::helper('M2ePro')->escapeJs($this->getProductGridId()) ?>',
            <?php echo json_encode(empty($compatibleAttribute)); ?>
        );

        EbayMotorCompatibilityHandlerObj.initPopUp('<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Add Compatible Vehicles')); ?>', 'pop_up_content');

        addCustomCompatibilyRecordForm = new varienForm('add_custom_compatibility_record_form', '<?php echo $this->getValidationUrl(); ?>');
    };

    <?php if ($this->getRequest()->isXmlHttpRequest()): ?>
        init();
    <?php else: ?>
        Event.observe(window, 'load', init);
    <?php endif; ?>

</script>

<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
<div id="pop_up_content" style="display: none;">

    <div class="content-header skip-header">
        <table cellspacing="0">
            <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-ebay-template-general-motor-compatibility">
                        <?php echo Mage::helper('M2ePro')->__('Add Compatible Vehicles') ?>
                    </h3>
                </td>
                <td class="form-buttons"></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div id="block_notice_motors_compatibility_generate_attribute_value" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Compatible Vehicles'); ?>" style="margin-top: 15px;">

        <?php
            $idTitle = $this->isCompatibilityTypeEpid() ? 'ePIDs' : 'kTypes';
        ?>

        <?php echo Mage::helper('M2ePro')->__('
        Select Items, compatible with your part and choose appropriate option in the Actions Dropdown:
        <ul class="list">
        <li><strong>Overwrite ePIDs in Compatibility Attribute</strong> - replaces Items ePIDs in the Compatibility Attribute chosen in
        %general_path% with selected ones.</li>
        <li><strong>Add ePIDs to Compatibility Attribute</strong> - adds selected Items ePIDs to existing ones in Compatibility Attribute
        chosen in the General Settings.</li>
        </ul>
        If you have not found the Compatible Vehicle you need, but you are sure that it is existing and it can be used -
        you can always add it to a database in two ways:
        <ul class="list">
        <li>1. using <strong>Add Custom Compatibility Vehicle</strong> Button at the end of this page to add one value;</li>
        <li>2. using <strong>Import Tool</strong> in %general_path% to add several values.</li>
        </ul>',
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration', 'General')
        ); ?>

    </div>

    <div id="generate_attribute_content_container" class="<?php echo Mage::helper('M2ePro/Magento')->isGoEdition() ? '' : 'switcher'; ?>" style="display: none; margin-top: 15px;">

        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Selected %identifier_title%', $idTitle) ?>:</label>
                    </td>
                    <td class="value" style="width: 100%; padding-right: 10px;">
                        <input class="left-col-block input-text" style="width: 100%;" name="attribute_content" id="attribute_content" readonly>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>

    <div class="hor-scroll">

        <div id="compatibility">
            <div id="compatibility_grid_container"></div>
        </div>

    </div>

    <div style="float: right; margin-top: 3px; margin-bottom: 8px;">
        <?php echo $this->getChildHtml('add_custom_compatibility_record_button'); ?>
    </div>

</div>
<?php endif; ?>

<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
<div id="add_custom_compatibility_record_pop_up_content" style="display: none;">

    <div style="padding-top: 15px;">
        <form id="add_custom_compatibility_record_form" action="<?php echo $this->getUrl('*/*/addCustomCompatibilityRecord'); ?>" method="post" style="min-height: 265px; display: block;">

            <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
            <input name="compatibility_type" value="<?php echo $this->getCompatibilityType(); ?>" type="hidden" />

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <?php foreach($this->getRecordColumns() as $column) : ?>

                            <tr id="tr_column_id_<?php echo $column['title']; ?>">
                                <td style="min-width: 120px; height: 23px;">
                                    <?php echo $column['title']; ?>:
                                    <?php if ($column['is_required']) : echo '<span class="required">*</span>'; endif; ?>
                                </td>
                                <td>
                                    <?php if (isset($column['options'])) { ?>
                                        <select id="<?php echo $column['name']; ?>" name="row[<?php echo $column['name']; ?>]" style="width: 314px;" class="popup-validate-entry <?php if ($column['is_required']) : echo 'required-entry'; endif; ?>" >
                                            <option style="display: none;"></option>
                                            <?php foreach ($column['options'] as $optionValue => $optionName) : ?>
                                                <option value="<?php echo $optionValue; ?>"><?php echo Mage::helper('M2ePro')->__($optionName) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    <?php } else { ?>
                                        <input id="<?php echo $column['name']; ?>" name="row[<?php echo $column['name']; ?>]" type="text" style="width: 310px;" class="popup-validate-entry input-text
                                                                                                                                                             <?php if ($column['is_required']) : echo ' required-entry '; endif; ?>
                                                                                                                                                             <?php if (isset($column['type']) && $column['type'] == 'numeric') : echo ' validate-digits '; endif; ?>" />
                                    <?php } ?>
                                </td>
                            </tr>

                        <?php endforeach; ?>

                    </table>

                </div>
            </div>

        </form>

        <div style="text-align: right; margin-top: 10px; margin-bottom: 10px;">
            <a href="javascript:void(0)" onclick="Windows.getFocusedWindow().close();">
                <?php echo Mage::helper('M2ePro')->__('Cancel'); ?>
            </a>&nbsp;&nbsp;&nbsp;&nbsp;
            <button onclick="Dialog.okCallback()"><?php echo Mage::helper('M2ePro')->__('Confirm') ?></button>
        </div>

    </div>

</div>
<?php endif; ?>