<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Edit_Form $this */
$formData = $this->getFormData();
?>

<style type="text/css">
    td.value {
        vertical-align: middle !important;
    }

</style>

<div id="block_notice_walmart_listing_add_general_settings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'On this page, you can assign the Policy Templates to the current Listing. M2E Pro will manage the Listing Products based on the selected Policy settings.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'x/L4taAQ')
    ); ?>
</div>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_walmart_listing/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.add(<?php echo json_encode(array(
        'adminhtml_walmart_account/edit' => $this->getUrl('M2ePro/adminhtml_walmart_account/edit/')
    )); ?>);
    //-----------------------------

    M2ePro.text.condition_note_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be not more than 2000 characters long.')); ?>';
    M2ePro.text.sku_modification_custom_value_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('%value% placeholder should be specified')); ?>';

    M2ePro.text.sku_modification_custom_value_max_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The SKU length must be less than %value%.',
        Ess_M2ePro_Helper_Component_Walmart::SKU_MAX_LENGTH)); ?>';

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component'
    );

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Listing'); ?>,
        'Ess_M2ePro_Model_Walmart_Listing'
    );

    M2ePro.url.templateCheckMessages = '<?php echo $this->getUrl('*/adminhtml_template/checkMessages', array('component_mode' => Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

    M2ePro.url.addNewSellingFormatTemplate = '<?php echo $this->getUrl(
        '*/adminhtml_walmart_template_sellingFormat/new', array('close_on_save' => 1)
    ); ?>';
    M2ePro.url.editSellingFormatTemplate = '<?php echo $this->getUrl(
        '*/adminhtml_walmart_template_sellingFormat/edit', array('close_on_save' => 1)
    ); ?>';
    M2ePro.url.getSellingFormatTemplates = '<?php echo $this->getUrl(
        '*/adminhtml_general/modelGetAll',
        array(
            'model' => 'Template_SellingFormat',
            'id_field' => 'id',
            'data_field' => 'title',
            'sort_field' => 'title',
            'sort_dir' => 'ASC',
            'component_mode' => Ess_M2ePro_Helper_Component_Walmart::NICK,
            'marketplace_id' => isset($formData['marketplace_id']) ? $formData['marketplace_id'] : ''
        )
    ); ?>';

    M2ePro.url.addNewDescriptionTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_description/new', array('close_on_save' => 1)); ?>';
    M2ePro.url.editDescriptionTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_description/edit', array('close_on_save' => 1)); ?>';
    M2ePro.url.getDescriptionTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'Template_Description','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

    M2ePro.url.addNewSynchronizationTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_synchronization/new', array('close_on_save' => 1)); ?>';
    M2ePro.url.editSynchronizationTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_synchronization/edit', array('close_on_save' => 1)); ?>';
    M2ePro.url.getSynchronizationTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'Template_Synchronization','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

</script>

<script type="text/javascript">

    //-----------------------------
    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component'
    );

    Event.observe(window, 'load', function() {

        TemplateManagerObj = new TemplateManager();

        WalmartListingSettingsObj = new WalmartListingSettings();
        WalmartListingSettingsObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Listing'); ?>');

        $('template_selling_format_id').observe('change', function() {
            if ($('template_selling_format_id').value) {
                $('edit_selling_format_template_link').show();
            } else {
                $('edit_selling_format_template_link').hide();
            }
        });
        $('template_selling_format_id').simulate('change');

        $('template_description_id').observe('change', function() {
            if ($('template_description_id').value) {
                $('edit_description_template_link').show();
            } else {
                $('edit_description_template_link').hide();
            }
        });
        $('template_description_id').simulate('change');

        $('template_synchronization_id').observe('change', function() {
            if ($('template_synchronization_id').value) {
                $('edit_synchronization_template_link').show();
            } else {
                $('edit_synchronization_template_link').hide();
            }
        });
        $('template_synchronization_id').simulate('change');

        $('template_selling_format_id').observe('change', WalmartListingSettingsObj.selling_format_template_id_change);
        if ($('template_selling_format_id').value) {
            $('template_selling_format_id').simulate('change');
        }

        $('template_description_id').observe('change', WalmartListingSettingsObj.description_template_id_change);
        if ($('template_description_id').value) {
            $('template_description_id').simulate('change');
        }

        $('template_synchronization_id').observe('change', WalmartListingSettingsObj.synchronization_template_id_change);
        if ($('template_synchronization_id').value) {
            $('template_synchronization_id').simulate('change');
        }

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>
<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
    <input type="hidden" id="store_id" value="<?php echo isset($formData['store_id']) ? $formData['store_id'] : ''?>">
    <input type="hidden" id="marketplace_id" value="<?php echo isset($formData['marketplace_id']) ? $formData['marketplace_id'] : ''?>">

    <div class="entry-edit" id="magento_block_walmart_listing_add_templates">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Policies Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="template_selling_format_id"><?php echo Mage::helper('M2ePro')->__('Selling Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="template_selling_format_cell" class="value">
                            <select id="template_selling_format_id" name="template_selling_format_id" <?php if (!count($this->sellingFormatTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                <?php if (!$formData['template_selling_format_id']): ?>
                                    <option class="empty"></option>
                                <?php endif ?>
                                <?php foreach ($this->sellingFormatTemplates as $item) { ?>
                                    <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $formData['template_selling_format_id']) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                <?php } ?>
                            </select>
                            <span id="template_selling_format_label" <?php if (count($this->sellingFormatTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                        </td>
                        <td class="value">
                        <span id="edit_selling_format_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.editTemplate(M2ePro.url.editSellingFormatTemplate, $('template_selling_format_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.addNewTemplate(M2ePro.url.addNewSellingFormatTemplate, WalmartListingSettingsObj.newSellingFormatTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                    <tr>
                        <td id="template_selling_format_messages" colspan="3"></td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_description_id"><?php echo Mage::helper('M2ePro')->__('Description Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="template_description_id" name="template_description_id" <?php if (!count($this->descriptionsTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                <?php if (!$formData['template_description_id']): ?>
                                    <option class="empty"></option>
                                <?php endif ?>
                                <?php foreach ($this->descriptionsTemplates as $item){ ?>
                                    <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $formData['template_description_id']) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                <?php } ?>
                            </select>
                            <span id="template_description_label" <?php if (count($this->descriptionsTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                        </td>
                        <td class="value">
                        <span id="edit_description_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.editTemplate(M2ePro.url.editDescriptionTemplate, $('template_description_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.addNewTemplate(M2ePro.url.addNewDescriptionTemplate, WalmartListingSettingsObj.newDescriptionTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_synchronization_id"><?php echo Mage::helper('M2ePro')->__('Synchronization Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="template_synchronization_id" name="template_synchronization_id" <?php if (!count($this->synchronizationsTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                <?php if (!$formData['template_synchronization_id']): ?>
                                    <option class="empty"></option>
                                <?php endif ?>
                                <?php foreach ($this->synchronizationsTemplates as $item){ ?>
                                    <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $formData['template_synchronization_id']) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                <?php } ?>
                            </select>
                            <span id="template_synchronization_label" <?php if (count($this->synchronizationsTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                        </td>
                        <td class="value">
                        <span id="edit_synchronization_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.editTemplate(M2ePro.url.editSynchronizationTemplate, $('template_synchronization_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsObj.addNewTemplate(M2ePro.url.addNewSynchronizationTemplate, WalmartListingSettingsObj.newSynchronizationTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                </table>

            </div>
        </div>
    </div>
</form>