<?php

/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var Ess_M2ePro_Block_Adminhtml_Amazon_Listing_Other_Help $this */

?>

<div
    id="block_notice_amazon_other_listings_grid" class="block_notices_module"
    title="<?php echo Mage::helper('M2ePro')->__('Unmanaged Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        <<<HTML
On this page, you can review the <strong>Unmanaged Listings</strong> imported by M2E Pro from your Channel Account associated with particular Marketplace.<br/><br/>

In the grid below, click the Unmanaged Listing line to manage the Items. You can Link the Unmanaged Items to the related Magento Products and Move them to the selected M2E Pro Listing.<br>
Manage each Item individually or use the Mass Actions to update the Items in bulk.<br><br>

<strong>Note:</strong> To import the Unmanaged Listings, enable the related option in your Account configuration under the <i>%navigation%</i>.<br/><br/>

The detailed information can be found <a href="%url%" target="_blank">here</a>.
HTML
        ,
        Mage::helper('M2ePro/View_Amazon')->getPageNavigationPath(
            'configuration',
            'Accounts',
            '[Needed Account] > Unmanaged Listings Tab'
        ),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, "unmanaged-listing")
    ); ?>
</div>
