<div id="block_notice_amazon_other_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        On this page, you can review the <strong>3rd Party Listings</strong> imported by M2E Pro from your Channel Account associated with particular Marketplace.<br/><br/>

        In the grid below, click the 3rd Party Listing line to manage the Items. You can Map the 3rd Party Items to the related Magento Products and Move them to the selected M2E Pro Listing.<br>
        Manage each Item individually or use the Mass Actions to update the Items in bulk.<br><br>

        <strong>Note:</strong> To import the 3rd Party Listings, enable the related option in your Account configuration under the <i>%navigation</i>.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper('M2ePro/View_Amazon')->getPageNavigationPath('configuration', 'Accounts', '[Needed Account] > 3rd Party Listings Tab'),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(Ess_M2ePro_Helper_Component_Amazon::NICK, '3rd+Party+Listings')
    ); ?>
</div>