<script type="text/javascript" src="<?php echo $this->getJsUrl('M2ePro/VideoTutorialHandler.js'); ?>"></script>

<script type="text/javascript">

    VideoTutorialHandlerObj = new VideoTutorialHandler(
        'video_tutorial_pop_up',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('eBay/Magento Integration: Listing')); ?>',
        function() {}
    );

</script>

<div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <table>

        <tr>
            <td>
                <a id="tutorial_image_container" style="display: block;" href="javascript:" onclick="VideoTutorialHandlerObj.openPopUp()">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/ebay-video-thumbnail.png'); ?>" alt="">
                </a>
            </td>

            <td style="padding: 10px  0 0 30px">

                <h3>
                    <?php echo Mage::helper('M2ePro')->__('Creating a new Listing in one of your first jobs. Don\'t worry. It\'s easy to do.'); ?>
                </h3>
                <br/>

                <p><?php echo Mage::helper('M2ePro')->__('Think of an M2E Pro Listing as a set of Policies that will determine the type of Items you wish to sell. You can create as many M2E Pro Listings as you need.'); ?></p>
                <p><?php echo Mage::helper('M2ePro')->__('Creating an M2E Pro Listing with certain characteristics means you won\'t need to input these characteristics again and again every time you wish to sell an Item.'); ?></p>

                <?php

                $countOfStages = 3;
                $modeName = 'Simple';

                if (Mage::helper('M2ePro/View_Ebay')->isAdvancedMode()) {
                    $countOfStages = 4;
                    $modeName = 'Advanced';
                } ?>

                <p><?php echo Mage::helper('M2ePro')->__('There are %amount% stages to complete to create a successful M2E Pro Listing in %mode_name% Mode:',$countOfStages,$modeName); ?></p>

                <ul style="list-style: decimal; padding-left: 40px;">
                    <li><?php echo Mage::helper('M2ePro')->__('<b>General Settings</b> – information about which eBay Site you wish to list on, your eBay User ID and which Magento Store Settings you wish to use'); ?></li>
                    <li><?php echo Mage::helper('M2ePro')->__('<b>Payment and Shipping Settings</b> – what are your shipping charges, your Returns Policy and how do you wish to get paid'); ?></li>
                    <li><?php echo Mage::helper('M2ePro')->__('<b>Selling Settings</b> – more detailed information about the type of eBay Listing and how long your Item will be on sale'); ?></li>
                    <?php if (Mage::helper('M2ePro/View_Ebay')->isAdvancedMode()) { ?>
                        <li><?php echo Mage::helper('M2ePro')->__('<b>Synchronization Setting</b> – how your Items are synchronized on eBay'); ?></li>
                    <?php } ?>
                </ul>

                <br/>
                <div><?php echo $this->getChildHtml('continue_button'); ?></div>
            </td>

        </tr>

    </table>
</div>

<div id="video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
        <?php if (Mage::helper('M2ePro/View_Ebay')->isSimpleMode()) { ?>
            <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/CvjQSRx-od0?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/CvjQSRx-od0?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
        <?php } else { ?>
            <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/IvXP-tA64KE?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/IvXP-tA64KE?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
        <?php } ?>
    </div>
</div>