<script type="text/javascript" src="<?php echo $this->getJsUrl('M2ePro/VideoTutorialHandler.js'); ?>"></script>

<script type="text/javascript">

    VideoTutorialHandlerObj = new VideoTutorialHandler(
        'video_tutorial_pop_up',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Wizard (Video Tutorial)')); ?>',
        function() {}
    );

</script>

<div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <table>

        <tr>
            <td>
                <a id="tutorial_image_container" style="display: block;" href="javascript:" onclick="VideoTutorialHandlerObj.openPopUp()">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/ebay-video-thumbnail.png'); ?>" alt="">
                </a>
            </td>

            <td style="padding: 10px 0 0 30px">

                <h3>
                    <?php echo Mage::helper('M2ePro')->__('Combine Magento - the best-selling ecommerce web application and eBay – the world\'s favourite marketplace'); ?>
                </h3>
                <br/>

                <p><?php echo Mage::helper('M2ePro')->__('M2E Pro is a Magento Extension that enables you to sell your Products on eBay and manage your sales from your Magento Store.'); ?></p>
                <p><?php echo Mage::helper('M2ePro')->__('Using M2E Pro is an easy way to display your Products in front of millions of Buyers on eBay. It\'s quick and simple to set up. You choose which Products to sell, the Quantity and Price. Using eBay means your Items are automatically optimized for mobile – the biggest retail growth area.'); ?></p>
                <p><?php echo Mage::helper('M2ePro')->__('The first step is to link Magento to your eBay account.'); ?></p>
                <p><?php echo Mage::helper('M2ePro')->__('If you already have an eBay account, check that you are registered as an eBay business Seller. If you don\'t yet have an eBay account it\'s easy to create one.'); ?></p>

                <br/>
                <div><?php echo $this->getChildHtml('start_wizard_button'); ?></div>
            </td>

        </tr>

    </table>
</div>

<div id="video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
        <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/tFgFpm3O5NU?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/tFgFpm3O5NU?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>