<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Listing_Variation_Product_Manage_Tabs_Variations_Help */

?>

<div id="block_notice_amazon_product_manage_variations" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Child Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        On this Tab you can see all Amazon Child Products that were created based on Magento Product Variations.<br/><br/>

        In case not all of the Variations of Magento Product exist as Amazon Child Products,
        you can always create new Amazon Child Products based on available Variations of Magento Product by clicking <strong>Add New Child Product</strong> button.
    '); ?>
</div>