<?php
    /** @var Ess_M2ePro_Block_Adminhtml_Development_Tabs_Command_Group $this */
?>

<?php foreach($this->commands as $index => $command) : ?>

    <?php
        $components = array();
        if ($command['components']) {
            $components = $command['components'] === true ? $this->enabledComponents : $command['components'];
        }
    ?>

    <table>
        <tr <?php if ($command['non_production'] && Mage::helper('M2ePro/Module')->isProductionEnvironment()) : echo 'style="display: none;"'; endif; ?>>
            <td class="group_number_td"><b><?php echo $index + 1; ?>.</b></td>
            <td style="width: 10px;">|</td>
            <td>
                <?php echo $this->getCommandLauncherHtml($command); ?>

                <?php if (count($components) > 1): ?>
                <?php foreach ($this->enabledComponents as $key => $component): ?>

<?php echo $key == 0 ? '(' : ''; ?>
<?php echo $this->getCommandLauncherHtml($command, $component); ?>
<?php echo isset($this->enabledComponents[$key + 1]) ? ', ' : ')'; ?>

                <?php endforeach; ?>
                <?php endif; ?>
            </td>
        </tr>

        <?php if ($command['new_line']): ?>
            <tr>
                <td colspan="3">
                    <hr style="margin-top: 8px;"/>
                </td>
            </tr>
        <?php endif; ?>

    </table>

<?php endforeach; ?>