<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Configuration_General_Form */
$businessMode = Mage::helper('M2ePro/Component_Amazon_Business')->isEnabled();

?>

<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_amazon_general/save'),
    )); ?>);

    Event.observe(window, 'load', function() {
        editForm = new varienForm('<?php echo $this->getForm()->getId(); ?>', '<?php echo $this->getValidationUrl(); ?>');
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_amazon_configuration_general_business" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Business (B2B)'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Price, QTY Discounts'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="business_mode" name="business_mode">
                                    <option value="0" <?php if (0 == $businessMode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                                    <option value="1" <?php if (1 == $businessMode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('
                                        After you <strong>Enable</strong> this option, you can provide the settings for <strong>Business Price</strong> and <strong >Quantity Discounts</strong> within M2E Pro Selling Policy.<br />
                                        <strong>Note:</strong> your Business Account must be approved by Amazon.'
                                    ); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

</form>
