<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Configuration_General_Help */

?>

<div id="block_notice_amazon_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
                In this section, you can configure the general settings for the interaction between M2E Pro and
                Amazon Marketplaces.<br/><br/>

                Specify Product Identifier values for your Amazon items at a global level.<br/>
                If you prefer to set product IDs per listing, please navigate
                to Listings > Items > Edit Settings > Product Identifiers.<br/><br/>

                Enable <a href="%url%" target="_blank">Amazon Business (B2B)</a> to apply the
                Business Price and QTY Discounts to your offers on the selected marketplaces.
    ', Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'help/m2/amazon-integration/amazon-business')); ?>
</div>