<div id="block_notice_amazon_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This section allows you to configure the general settings for interaction between M2E Pro and Amazon marketplaces.<br />
        You can enable Amazon Business (B2B) to apply the Business Price and QTY Discounts to your Offers.<br /><br />
        <strong>Note:</strong> Amazon Business is available for the US, UK, DE, FR marketplaces only.
    '); ?>
</div>