<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Configuration_General_Help */

?>

<div id="block_notice_amazon_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This section allows you to set up interaction between M2E Pro and Amazon marketplaces.<br />
        Enable <a href="%url%" target="_blank">Amazon Business (B2B)</a> to apply the Business Price and QTY Discounts to your offers on selected marketplaces.
    ', Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'amazon-business')); ?>
</div>