<div id="block_notice_ebay_synchronizations_log_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains information on processes, which were done in Synchronization Tasks.<br/><br/>
    <b>Note:</b> Logs of Default, Inventory, Orders and 3rd Party Listings Synchronizations are only recorded when Error(s) or Warning(s) appears.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/MAAJAQ#Logs.-SynchronizationLog')
    ); ?>
</div>