<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Order_Log_Help */

?>

<div id="block_notice_walmart_logs_orders_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">

    <?php echo Mage::helper('M2ePro')->__(
        'This Log contains information about the Order processing.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "x/L4taAQ")
    ); ?>

</div>