<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Template_Description_Preview_Body */

?>

<?php if (($title = $this->getData('title'))) { ?>

    <div class="entry-edit" id="magento_block_ebay_template_description_preview" style="padding: 5px;">
        <h2 style="color: maroon; margin-bottom: 5px;"><?php echo Mage::helper('M2ePro')->escapeHtml($title); ?></h2>
        <hr /><?php echo $this->getData('description'); ?>
    </div>

<?php } ?>