<div id="productSearch_pop_up_content" style="display: none;">
    <div class="hor-scroll" style="padding-top: 15px; margin-bottom: 0;">

        <div id="productSearch_error_block" class="error-msg" style="display:none; margin-bottom: 10px;">
            <div style="margin: 10px 0 10px 35px">
                <div id="productSearch_error_message" style="font-weight:bold"></div>
            </div>
        </div>

        <div id="productSearch_form" style="float:none; padding: 10px; margin-bottom:10px; border: 1px solid #CDDDDD !important; background: none repeat scroll 0 0 #E7EFEF !important" >
            <label for="query"><?php echo Mage::helper('M2ePro')->__('Enter Product Title, ASIN, ISBN, UPC, EAN or Keywords'); ?></label>
            <input id="query" type="text" name="query" class="input-text" style="margin: 0 10px 0 10px; width: 150px" />

            <?php echo $this->getChildHtml('productSearch_submit_button'); ?>&nbsp;&nbsp;
            <a href="javascript:void(0)" id="productSearch_reset_button"><?php echo Mage::helper('M2ePro')->__('Reset'); ?></a>
        </div>
        <div id="suggested_asin_grid_help_block" style="display: none">
            <div id="block_notice_amazon_suggested_asin_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Automatic ASIN/ISBN Search Results'); ?>">
                <?php echo Mage::helper('M2ePro')->__('Automatic ASIN/ISBN Search was performed according to the Listing Search Settings.
        The results of the Search are displayed in the Grid below. You can Assign appropriate ASIN/ISBN to the selected Magento Product or "Clear Search Results".'); ?>
            </div>
        </div>

        <div id="productSearch_grid" style="margin: 0 auto 10px auto; height: 350px !important; overflow-y: auto; overflow-x: hidden;">
        </div>

        <div class="clear"></div>

        <div id="productSearch_buttons" style="right:23px; display:none; text-align: right; margin: 10px 0;">
            <?php echo $this->getChildHtml('productSearch_cleanSuggest_button'); ?>
            <?php echo $this->getChildHtml('productSearch_back_button'); ?>&nbsp;&nbsp;
            <?php echo $this->getChildHtml('productSearch_cancel_button'); ?>
        </div>

    </div>
</div>