<?php
/** @var $this Ess_M2ePro_Block_Adminhtml_Common_Amazon_Listing_ProductSearch_Menu */
?>
<div id="productSearchMenu_pop_up_content">
    <div class="hor-scroll" style="padding-top: 15px; margin-bottom: 0">

        <div id="productSearchMenu_error_block" class="error-msg" style="display:none">
            <div style="margin: 6px 0 6px 35px">
                <strong><?php echo Mage::helper('M2ePro')->__('There was an error during previous Automatic ASIN/ISBN Search:'); ?></strong><br/>
                <div id="productSearchMenu_error_message"></div>
            </div>
        </div>

        <div style="text-align:center; margin: 20px auto;">
            <div>
                <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchManualPrompt();"><?php echo Mage::helper('M2ePro')->__('Assign ASIN/ISBN Manually'); ?></a>
                <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo Mage::helper('M2ePro')->__('Search ASIN/ISBN by data that will be specified on the next step.'); ?></div>
            </div>
            <div>
                <?php if (!$this->isIndividualFromBundleOrSimpleWithCustome()) { ?>

                    <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchGeneralIdAutoPrompt();">
                        <?php echo Mage::helper('M2ePro')->__('Assign ASIN/ISBN Automatically'); ?>
                    </a>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo Mage::helper('M2ePro')->__('Search ASIN/ISBN by data that have already been specified in Listing Search Settings.'); ?></div>

                <?php } else { ?>
                    <span style="color:#666; font-size:140%"><?php echo Mage::helper('M2ePro')->__('Assign ASIN/ISBN Automatically'); ?></span>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;">
                        <?php echo Mage::helper('M2ePro')->__('This Option is not available for Simple with Custom Options and Bundle Magento Products. Please use "Assign ASIN/ISBN Manually" functionality.'); ?>
                    </div>
                <?php } ?>
            </div>

            <div>
                <?php if (!$this->isIndividualFromBundleOrSimpleWithCustome() &&
                          !$this->isParentFromBundleOrSimpleWithCustome()) { ?>

                    <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.addNewGeneralId();">
                        <?php echo Mage::helper('M2ePro')->__('Assign Settings for New ASIN/ISBN'); ?>
                    </a>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo Mage::helper('M2ePro')->__('Define Settings for New Amazon Product Creation. ASIN/ISBN will be assigned by Amazon.'); ?></div>

                <?php } else { ?>
                    <span style="color:#666; font-size:140%"><?php echo Mage::helper('M2ePro')->__('Assign Settings for New ASIN/ISBN'); ?></span>
                    <div style="color:#666; height:50px; margin:5px auto 10px auto;">
                        <?php echo Mage::helper('M2ePro')->__('This Option is not available for Simple with Custom Options and Bundle Magento Products.'); ?>
                    </div>
                <?php } ?>
            </div>

        </div>

        <div id="productSearchMenu_buttons" style="text-align: right; margin: 10px 0;">
            <?php echo $this->getChildHtml('productSearchMenu_cancel_button') ?>
        </div>

    </div>
</div>