<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Bids_Help */

?>

<div id="block_notice_ebay_listing_product_bids" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Bids History'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    In this section you can see the list of all Bids for your Product sorted by
    descending. You can see the eBay User ID, User email, the Price and a Date of Bid Creation.
'); ?>
</div>
