<div id="block_notice_walmart_logs_other_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">

    <?php echo Mage::helper('M2ePro')->__(
        'This Log contains information about the actions applied to 3rd Party Listings and related Items<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/L4taAQ")
    ); ?>

</div>