<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Order_Help */

?>

<div id="block_notice_amazon_orders_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php
    echo Mage::helper('M2ePro')->__('This Page contains all Orders.<br/><br/>
    Use Accounts Dropdown to filter Orders by Accounts.
    If Magento Order, Invoice or / and Shipment was not created automatically,
    you can create them manually by using appropriate Options in the <strong>Action</strong> Dropdown.<br/><br/>
    <b>Note:</b> Automatic creation of Magento Orders, Invoices, and Shipments executes according to <i class="underline">Accounts Settings</i> in (%menu_path%).',
        Mage::helper('M2ePro/View_Amazon')->getPageNavigationPath('configuration', 'Accounts', 'Edit Account Configuration > Orders')
    );

    $url = Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "sales-orders");

    echo Mage::helper('M2ePro')->__('
        <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        $url
    );
?>
</div>