<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Walmart_Template_Help */

?>

<div id="block_notice_walmart_sellingFormat_templates" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        <strong>Category Policy</strong> includes the Walmart Category/Subcategory and Specifics that best describe your Item.<br/><br/>
        
        <strong>Description Policy</strong> highlights the most essential Product details, e.g. Title, Brand, Images, etc.<br/><br/>
        
        <strong>Selling Policy</strong> contains conditions based on which you are going to sell your Item on the Channel, e.g. Item Price, Quantity, Shipping and Product Tax Code settings, etc.<br /><br />
        
        <strong>Synchronization Policy</strong> defines the Rules based on which your Walmart Items will be dynamically updated with Magento data.
    ');

    echo Mage::helper('M2ePro')->__('
        <br/><br/>
        The detailed information can be found <a target="_blank" href="%url1%">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'walmart-integration')
    ); ?>
</div>