<div id="block_notice_amazon_suggested_asin_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Automatic ASIN/ISBN Search Results'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Automatic ASIN/ISBN Search was performed according to the Listing Search Settings.
    The results of the Search are displayed in the Grid below. You can Assign appropriate ASIN/ISBN to the selected Magento Product or "Clear Search Results".'); ?>
</div>