<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Amazon_Order_Help */

?>

<div id="block_notice_amazon_logs_orders_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains Orders history information.');

    $url = Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(null, null, "x/foIVAQ#Logs-OrdersLog");

    echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        $url
    );
?>
</div>