<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Info_Actual */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Magento'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->magentoInfo ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Module [Public]'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->publicVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Module [Setup]'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->setupVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Module Environment'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->moduleEnvironment ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Core Resource'); ?>: </label>
        </td>
        <td class="value">
            <span <?php if ($this->setupVersion != $this->coreResourceVersion || $this->setupVersion != $this->coreResourceDataVersion) : echo ' style="color: red;" '; endif; ?>>
                <?php echo ($this->coreResourceVersion ? $this->coreResourceVersion : 'N/A') .' / '.
                           ($this->coreResourceDataVersion ? $this->coreResourceDataVersion : 'N/A') ?>
            </span>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('PHP'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->phpVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Server API'); ?>: </label>
        </td>
        <td class="value">
            <?php echo$this->phpApi ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Memory Limit'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->memoryLimit . ' Mb'?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Max Execution Time'); ?>: </label>
        </td>
        <td class="value">
             <?php echo $this->maxExecutionTime == 0 ? Mage::helper('M2ePro')->__('Unlimited') : $this->maxExecutionTime . ' sec'; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('MySQL'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Database'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->mySqlDatabaseName ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Cron'); ?> (<?php echo $this->cronCurrentRunner; ?>): </label>
        </td>
        <?php
            $style = '';
            if ($this->cronIsNotWorking) {
                $style = ' style="color: red"';
            }
        ?>
        <td class="value">
            <span<?php echo $style; ?>><?php echo $this->cronLastRunTime; ?></span>
            <?php
            if ($this->cronIsNotWorking) {
                echo ' (' . Mage::helper('M2ePro')->__('not working') . ')';
            }
            ?>
        </td>
    </tr>
</table>