<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Info_License */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Extension Key'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->licenseData['key']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Domain [valid | real]'); ?>: </label>
        </td>
        <td class="value">
            <span <?php echo $this->licenseData['valid']['domain'] ? '' : 'style="color:red;"' ?>>
                <?php echo "{$this->licenseData['domain']} | {$this->locationData['domain']}"; ?>
            </span>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('IP [valid | real]'); ?>: </label>
        </td>
        <td class="value">
            <span <?php echo $this->licenseData['valid']['ip'] ? '' : 'style="color:red;"' ?>>
                <?php echo "{$this->licenseData['ip']} | {$this->locationData['ip']}"; ?>
            </span>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Directory'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->locationData['directory']; ?>
        </td>
    </tr>

</table>