<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Info_Module */

?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Version (revision)'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->moduleVersion; ?>.r<?php echo $this->moduleRevision; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Environment'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->moduleEnvironment; ?>
        </td>
    </tr>

</table>