<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_ControlPanel_Info_MysqlTables */

?>

<style type="text/css">
    .category {
        font-size: 14px;
        color: #ea7601;
    }
    td.edit-database a {
        padding-left: 10px !important;
    }
</style>

<table class="form-list" cellspacing="0" cellpadding="0">

    <?php foreach ($this->getTablesInfo() as $category=>$tables) : ?>
        <tr>
            <td class="label category" colspan="3">
                <label"><?php echo $category; ?>: </label>
            </td>
        </tr>

        <?php foreach ($tables as $table=>$data) : ?>
            <tr>
                <td class="label">
                    <?php echo $table; ?>
                </td>
                <td class="value">
                    <?php echo $data['count']; ?>
                </td>
                <td class="value edit-database">
                    <a href="<?php echo $data['url']?>">Edit</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>

</table>