<?php
/** @var Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Add_Form $this */
?>

<style type="text/css">

    .switcher {
        margin: 0 !important;
    }
    td.value {
        vertical-align: middle !important;
    }

</style>

<div id="block_notice_walmart_listing_add_general_settings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'On this page, you can configure the basic Listing settings. Specify the meaningful Listing Title for your internal use.<br>
        Select Account under which you want to manage this Listing. Assign the Policy Templates and Magento Store View.<br/><br/>

        The detailed information can be found <a href="%url%" target="_blank">here</a>.',

        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/L4taAQ')
    ); ?>
</div>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_walmart_listing/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.add(<?php echo json_encode(array(
        'adminhtml_walmart_account/edit' => $this->getUrl('M2ePro/adminhtml_walmart_account/edit/')
    )); ?>);
    //-----------------------------

    M2ePro.text.condition_note_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be not more than 2000 characters long.')); ?>';
    M2ePro.text.sku_modification_custom_value_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('%value% placeholder should be specified')); ?>';

    M2ePro.text.sku_modification_custom_value_max_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The SKU length must be less than %value%.',
        Ess_M2ePro_Helper_Component_Walmart::SKU_MAX_LENGTH)); ?>';

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component'
    );

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Listing'); ?>,
        'Ess_M2ePro_Model_Walmart_Listing'
    );

    M2ePro.url.templateCheckMessages = '<?php echo $this->getUrl('*/adminhtml_template/checkMessages', array('component_mode' => Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

    M2ePro.url.addNewSellingFormatTemplate = '<?php echo $this->getUrl(
        '*/adminhtml_walmart_template_sellingFormat/new'
    ); ?>' + 'marketplace_id/';
    M2ePro.url.editSellingFormatTemplate = '<?php echo $this->getUrl(
        '*/adminhtml_walmart_template_sellingFormat/edit'
    ); ?>' + 'id/';
    M2ePro.url.getSellingFormatTemplates = '<?php echo $this->getUrl(
        '*/adminhtml_general/modelGetAll',
        array(
            'model' => 'Template_SellingFormat',
            'id_field' => 'id',
            'data_field' => 'title',
            'sort_field' => 'title',
            'sort_dir' => 'ASC',
            'component_mode' => Ess_M2ePro_Helper_Component_Walmart::NICK
        )
    ); ?>';

    M2ePro.url.addNewDescriptionTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_description/new'); ?>';
    M2ePro.url.editDescriptionTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_description/edit'); ?>' + 'id/';
    M2ePro.url.getDescriptionTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'Template_Description','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

    M2ePro.url.addNewSynchronizationTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_synchronization/new'); ?>';
    M2ePro.url.editSynchronizationTemplate = '<?php echo $this->getUrl('*/adminhtml_walmart_template_synchronization/edit'); ?>' + 'id/';
    M2ePro.url.getSynchronizationTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'Template_Synchronization','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>';

    M2ePro.autoCompleteData = {
        url : {}
    };
    M2ePro.autoCompleteData.flags = {
        sellingFormatTemplatesDropDown    : <?php echo $this->sellingFormatTemplatesDropDown    ? 'true' : 'false'; ?>,
        descriptionsTemplatesDropDown : <?php echo $this->descriptionsTemplatesDropDown ? 'true' : 'false'; ?>,
        synchronizationsTemplatesDropDown : <?php echo $this->synchronizationsTemplatesDropDown ? 'true' : 'false'; ?>
    };
    M2ePro.autoCompleteData.url.getSellingFormatTemplates = '<?php echo $this->getUrl(
        '*/adminhtml_general/searchAutocomplete',
        array(
            'model' => 'Template_SellingFormat',
            'component' => Ess_M2ePro_Helper_Component_Walmart::NICK
        )
    ); ?>';

    M2ePro.autoCompleteData.url.getDescriptionTemplates = '<?php echo $this->getUrl(
        '*/adminhtml_general/searchAutocomplete',
        array(
            'model' => 'Template_Description',
            'component' => Ess_M2ePro_Helper_Component_Walmart::NICK
        )
    ); ?>';

    M2ePro.autoCompleteData.url.getSynchronizationTemplates = '<?php echo $this->getUrl(
        '*/adminhtml_general/searchAutocomplete',
        array(
            'model' => 'Template_Synchronization',
            'component' => Ess_M2ePro_Helper_Component_Walmart::NICK
        )
    ); ?>';

</script>

<script type="text/javascript">

    //-----------------------------
    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($this->getData('title'))); ?>';

    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified Title is already used for other Listing. Listing Title must be unique.')); ?>';

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Walmart'); ?>,
        'Ess_M2ePro_Helper_Component'
    );

    Event.observe(window, 'load', function() {
        WalmartListingSettingsHandlerObj = new WalmartListingSettingsHandler();
        WalmartListingSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Listing'); ?>');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        TemplateHandlerObj = new TemplateHandler();

        WalmartListingSettingsHandlerObj = new WalmartListingSettingsHandler();
        WalmartListingSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Listing'); ?>');

        WalmartListingChannelSettingsHandlerObj = new WalmartListingChannelSettingsHandler();
        WalmartListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Walmart_Listing'); ?>');

        $('marketplace_id')
            .observe('change', WalmartListingSettingsHandlerObj.marketplaceIdOnChange);

        $('template_selling_format_id').observe('change', function() {
            if ($('template_selling_format_id').value) {
                $('edit_selling_format_template_link').show();
            } else {
                $('edit_selling_format_template_link').hide();
            }
        });
        $('template_selling_format_id').simulate('change');

        $('template_description_id').observe('change', function() {
            if ($('template_description_id').value) {
                $('edit_description_template_link').show();
            } else {
                $('edit_description_template_link').hide();
            }
        });
        $('template_description_id').simulate('change');

        $('template_synchronization_id').observe('change', function() {
            if ($('template_synchronization_id').value) {
                $('edit_synchronization_template_link').show();
            } else {
                $('edit_synchronization_template_link').hide();
            }
        });
        $('template_synchronization_id').simulate('change');

        AutoCompleteHandler = new AutoComplete();

        if (M2ePro.autoCompleteData.flags.sellingFormatTemplatesDropDown) {
            $('template_selling_format_id').observe('change', WalmartListingSettingsHandlerObj.selling_format_template_id_change)
            if ($('template_selling_format_id').value) {
                $('template_selling_format_id').simulate('change');
            }
        } else {
            var sellingFormatHandler = AutoCompleteHandler.bind('template_selling_format_autocomplete',
                M2ePro.autoCompleteData.url.getSellingFormatTemplates,
                M2ePro.formData.template_selling_format_id > 0 ? M2ePro.formData.template_selling_format_id : '',
                M2ePro.formData.template_selling_format_title,
                function (id) {
                    $('template_selling_format_id').value = id;
                    $('template_selling_format_id').simulate('change');
                }
            );
            sellingFormatHandler.options.dynamicQueryParamsCallback = function() {
                return { marketplace_id: $('marketplace_id').value };
            };
            $('template_selling_format_id').value = $('template_selling_format_autocomplete').readAttribute('selected_id');
            M2ePro.formData.template_selling_format_id > 0 && $('template_selling_format_autocomplete').setStyle({color: 'initial'});
        }

        if (M2ePro.autoCompleteData.flags.descriptionsTemplatesDropDown) {
            $('template_description_id').observe('change', WalmartListingSettingsHandlerObj.description_template_id_change)
            if ($('template_description_id').value) {
                $('template_description_id').simulate('change');
            }
        } else {
            AutoCompleteHandler.bind('template_description_autocomplete',
                M2ePro.autoCompleteData.url.getDescriptionTemplates,
                M2ePro.formData.template_description_id > 0 ? M2ePro.formData.template_description_id : '',
                M2ePro.formData.template_description_title,
                function (id) { $('template_description_id').value = id; $('template_description_id').simulate('change'); }
            );
            $('template_description_id').value = $('template_description_autocomplete').readAttribute('selected_id');
            M2ePro.formData.template_description_id > 0 && $('template_description_autocomplete').setStyle({color: 'initial'});
        }

        if (M2ePro.autoCompleteData.flags.synchronizationsTemplatesDropDown) {
            $('template_synchronization_id').observe('change', WalmartListingSettingsHandlerObj.synchronization_template_id_change)
            if ($('template_synchronization_id').value) {
                $('template_synchronization_id').simulate('change');
            }
        } else {
            AutoCompleteHandler.bind('template_synchronization_autocomplete',
                M2ePro.autoCompleteData.url.getSynchronizationTemplates,
                M2ePro.formData.template_synchronization_id > 0 ? M2ePro.formData.template_synchronization_id : '',
                M2ePro.formData.template_synchronization_title,
                function (id) { $('template_synchronization_id').value = id; $('template_synchronization_id').simulate('change'); }
            );
            $('template_synchronization_id').value = $('template_synchronization_autocomplete').readAttribute('selected_id');
            M2ePro.formData.template_synchronization_id > 0 && $('template_synchronization_autocomplete').setStyle({color: 'initial'});
        }
    });
    //-----------------------------

</script>
<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
    <div class="entry-edit" id="magento_block_walmart_listing_add_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="title" name="title" value="<?php echo Mage::helper('M2ePro')->escapeHtml($this->getData('title')); ?>" type="text" class="input-text required-entry M2ePro-listing-title" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Listing Title for your internal use.'); ?></span>
                            </p>
                        </td>
                    </tr>
                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_walmart_listing_walmart_settings">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Walmart Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Account'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="min-width: 280px;">
                            <span id="account_label"></span>
                            <?php
                            $accountSelectionDisabled = true;
                            $accountId = $this->getRequest()->getParam('account_id');
                            if($accountId) {
                                echo '<input type="hidden" name="account_id" value="'.$accountId.'" />';
                            } else {
                                $accountId = $this->getData('account_id');
                                $accountSelectionDisabled = false;
                            }
                            ?>
                            <select <?php if($accountSelectionDisabled) echo 'disabled="disabled"' ?> id="account_id" name="account_id" class="required-entry" style="display: none"></select>
                            <p id="account_note" class="note" style="width: 0; height: 0; overflow: hidden">
                                <span><?php echo Mage::helper('M2ePro')->__('Select Account under which you want to manage this Listing.'); ?></span>
                            </p>
                        </td>
                        <td class="value" <?php if($accountSelectionDisabled) echo 'style="visibility: hidden;"'?>>
                            <?php echo $this->getChildHtml('add_account_button'); ?>
                        </td>
                    </tr>

                    <tr id="marketplace_info" >
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>:</label>
                        </td>

                        <td class="value">
                            <input id="marketplace_id" type="hidden" value="" />
                            <span id="marketplace_title"></span>
                            <p class="note" id="marketplace_url"></p>

                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit m2epro-marketplace-depended-block" id="magento_block_walmart_listing_add_templates" style="display: none;">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Policies Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="template_selling_format_id"><?php echo Mage::helper('M2ePro')->__('Selling Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="template_selling_format_cell" class="value">
                            <?php if ($this->sellingFormatTemplatesDropDown): ?>
                                <select id="template_selling_format_id" name="template_selling_format_id" <?php if (!count($this->sellingFormatTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                    <?php if (!$this->getData('template_selling_format_id')): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->sellingFormatTemplates as $item) { ?>
                                        <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $this->getData('template_selling_format_id')) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                    <?php } ?>
                                </select>
                                <span id="template_selling_format_label" <?php if (count($this->sellingFormatTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                            <?php else: ?>
                                <input type="text" id="template_selling_format_autocomplete" class="input-text"
                                       selected_id="<?php echo $this->getData('template_selling_format_id'); ?>" style="width: 275px;"
                                       placeholder="<?php echo Mage::helper('M2ePro')->__('Type Policy Name Here...'); ?>"
                                       value="<?php echo $this->getSellingFormatTemplateTitleById($this->getData('template_selling_format_id')); ?>"
                                >
                                <input type="hidden" name="template_selling_format_id" id="template_selling_format_id" class="required-entry" value="<?php echo $this->getData('template_selling_format_id'); ?>" />
                            <?php endif; ?>
                        </td>
                        <td class="value" style="vertical-align: top !important;">
                        <span id="edit_selling_format_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.openWindow(M2ePro.url.editSellingFormatTemplate + $('template_selling_format_id').value + '/marketplace_id/' + $('marketplace_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.addNewTemplate(M2ePro.url.addNewSellingFormatTemplate+$('marketplace_id').value, WalmartListingSettingsHandlerObj.newSellingFormatTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                    <tr>
                        <td id="template_selling_format_messages" colspan="3"></td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_description_id"><?php echo Mage::helper('M2ePro')->__('Description Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if ($this->descriptionsTemplatesDropDown): ?>
                                <select id="template_description_id" name="template_description_id" <?php if (!count($this->descriptionsTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                    <?php if (!$this->getData('template_description_id')): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->descriptionsTemplates as $item){ ?>
                                        <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $this->getData('template_description_id')) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                    <?php } ?>
                                </select>
                                <span id="template_description_label" <?php if (count($this->descriptionsTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                            <?php else:?>
                                <input type="text" id="template_description_autocomplete" class="input-text" selected_id="<?php echo $this->getData('template_description_id'); ?>" style="width: 275px;"
                                       placeholder="<?php echo Mage::helper('M2ePro')->__('Type Policy Name Here...'); ?>"
                                       value="<?php echo $this->getDescriptionTemplateTitleById($this->getData('template_description_id')); ?>"
                                >
                                <input type="hidden" name="template_description_id" id="template_description_id" class="required-entry" value="<?php echo $this->getData('template_description_id'); ?>" />
                            <?php endif; ?>
                        </td>
                        <td class="value" style="vertical-align: top !important;">
                        <span id="edit_description_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.openWindow(M2ePro.url.editDescriptionTemplate+$('template_description_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.addNewTemplate(M2ePro.url.addNewDescriptionTemplate, WalmartListingSettingsHandlerObj.newDescriptionTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_synchronization_id"><?php echo Mage::helper('M2ePro')->__('Synchronization Policy'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if ($this->synchronizationsTemplatesDropDown): ?>
                                <select id="template_synchronization_id" name="template_synchronization_id" <?php if (!count($this->synchronizationsTemplates)) echo 'style="display: none;"';?> class="required-entry">
                                    <?php if (!$this->getData('template_synchronization_id')): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->synchronizationsTemplates as $item){ ?>
                                        <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $this->getData('template_synchronization_id')) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                    <?php } ?>
                                </select>
                                <span id="template_synchronization_label" <?php if (count($this->synchronizationsTemplates)) echo 'style="display: none;"';?>><?php echo Mage::helper('M2ePro')->__('No Policies available.'); ?></span>
                            <?php else:?>
                                <input type="text" id="template_synchronization_autocomplete" class="input-text" selected_id="<?php echo $this->getData('template_synchronization_id'); ?>" style="width: 275px;"
                                       placeholder="<?php echo Mage::helper('M2ePro')->__('Type Policy Name Here...'); ?>"
                                       value="<?php echo $this->getSynchronizationTemplateTitleById($this->getData('template_synchronization_id')); ?>"
                                >
                                <input type="hidden" name="template_synchronization_id" id="template_synchronization_id" class="required-entry" value="<?php echo $this->getData('template_synchronization_id'); ?>" />
                            <?php endif; ?>
                        </td>
                        <td class="value" style="vertical-align: top !important;">
                        <span id="edit_synchronization_template_link">
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.openWindow(M2ePro.url.editSynchronizationTemplate+$('template_synchronization_id').value);"><?php echo Mage::helper('M2ePro')->__('View') ?>&nbsp;/&nbsp;<?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
                            <?php echo Mage::helper('M2ePro')->__('or') ?>
                        </span>
                            <a href="javascript: void(0);" onclick="WalmartListingSettingsHandlerObj.addNewTemplate(M2ePro.url.addNewSynchronizationTemplate, WalmartListingSettingsHandlerObj.newSynchronizationTemplateCallback);"><?php echo Mage::helper('M2ePro')->__('Add New') ?></a>
                        </td>
                    </tr>

                </table>

            </div>
        </div>
    </div>

    <div class="entry-edit m2epro-marketplace-depended-block" id="magento_block_magento_settings" style="display: none;">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Magento Settings'); ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table class="form-list" cellspacing="0" cellpadding="0">
                    <tbody>

                    <tr>
                        <td class="label" style="vertical-align: middle">
                            <label for="store_id"><?php echo Mage::helper('M2ePro')->__('Magento Store View'); ?>: <span class="required">*</span></label>
                        </td>

                        <td class="value" style="vertical-align: middle">
                            <?php echo $this->getChildHtml('store_switcher'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Select Magento Store View you want to use for this Listing.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">

    var accountsList;
    var initAccount = function() {

        var renderAccounts = function (callback) {

            var account_add_btn = $('add_account_button');
            var account_label_el = $('account_label');
            var account_select_el = $('account_id');
            var account_note = $('account_note');
            var marketplace_info = $('marketplace_info');

            new Ajax.Request('<?php echo $this->getUrl('*/adminhtml_general/getAccounts', array('component' => Ess_M2ePro_Helper_Component_Walmart::NICK)); ?>', {
                method: 'get',
                onSuccess: function(transport) {
                    accountsList = transport.responseText.evalJSON();

                    if (accountsList.length == 0) {
                        account_add_btn.down('span').update('<?php echo Mage::helper('M2ePro')->__('Add'); ?>');
                        account_label_el.update('<?php echo Mage::helper('M2ePro')->__('Account not found, please create it.'); ?>');
                        account_label_el.show();
                        account_select_el.hide();
                        account_note.hide();
                        marketplace_info.hide();
                        return;
                    }

                    account_note.show();
                    marketplace_info.show();

                    account_select_el.update();
                    account_select_el.appendChild(new Element('option', {style: 'display: none'}));
                    accountsList.each(function(account) {
                        account_select_el.appendChild(new Element('option', {value: account.id})).insert(account.title);
                    });

                    account_add_btn.down('span').update('<?php echo Mage::helper('M2ePro')->__('Add Another'); ?>');

                    if (accountsList.length == 1) {
                        var account = accountsList[0];

                        account_select_el.setValue(account.id);

                        var accountLink = M2ePro.url.get('adminhtml_walmart_account/edit', {'id': account.id});
                        var linkElement = new Element('a', {
                            'href': accountLink,
                            'target': '_blank'
                        }).update(account.title);

                        account_label_el.update(linkElement);

                        account_label_el.show();
                        account_select_el.hide();
                    } else {
                        account_select_el.setValue(accountsList[0].id);

                        account_label_el.hide();
                        account_select_el.show();
                    }

                    //firefox can't simulate events for disabled elements
                    if (account_select_el.disabled) {
                        account_select_el.enable();
                        account_select_el.simulate('change');
                        account_select_el.disable();
                    } else {
                        account_select_el.simulate('change');
                    }

                    callback && callback();
                }
            });
        };

        $('account_id').observe('change', function() {
            if ($('account_id').getValue() == '') {
                return;
            }
            accountsList.each(function(account){
                if (account.id == $('account_id').getValue()) {
                    $('marketplace_title').innerHTML = account.marketplace_title;
                    $('marketplace_url').innerHTML = account.marketplace_url;
                    $('marketplace_id').value = account.marketplace_id;
                    $('marketplace_id').simulate('change');
                    throw $break;
                }
            });
        });

        renderAccounts(function() {
            <?php if ($accountId) {?>
            var account_select_el = $('account_id');

            account_select_el.setValue(<?php echo $accountId; ?>);

            //firefox can't simulate events for disabled elements
            if (account_select_el.disabled) {
                account_select_el.enable();
                account_select_el.simulate('change');
                account_select_el.disable();
            } else {
                account_select_el.simulate('change');
            }
            <?php } ?>
        });

        $('add_account_button').observe('click', function() {
            var win = window.open('<?php echo $this->getUrl('*/adminhtml_walmart_account/new',array(
                'close_on_save' => true,
                'wizard' => (bool)$this->getRequest()->getParam('wizard',false)
            )); ?>');

            var intervalId = setInterval(function() {

                if (!win.closed) {
                    return;
                }

                clearInterval(intervalId);

                renderAccounts();

            }, 1000);
        });
    };

    var init = function() {

        initAccount();

    };

    Event.observe(window,'load',init);

</script>