<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }
    //-----------------------------

    Event.observe(window, 'load', function() {
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });

</script>