<style>
    .decorated-list li{
        margin-bottom: .5em;
    }
</style>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"></td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('view_header'); ?>

<div class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

    <?php echo Mage::helper('M2ePro')->__(
        'Products were successfully added to M2E Pro Listing.<br>
        You can Review Your Products prior to listing them on Walmart or List Added Products Now.
    '); ?>

    <div style="margin-top: 10px">
        <?php
            echo $this->getChildHtml('review');
            echo '&nbsp;';
            if ($this->getSource() === Ess_M2ePro_Block_Adminhtml_Walmart_Listing_Add_SourceMode::SOURCE_OTHER) {
                echo $this->getChildHtml('back_to_listing_other');
            } else {
                echo $this->getChildHtml('list');
            }
        ?>
    </div>

</div>
