<?php
    /** @var Ess_M2ePro_Block_Adminhtml_Ebay_Template_Synchronization_Edit_Form_Tabs_Relist $this */

    $default = $this->getDefault();
    $formData = $this->getFormData();

    $formData = array_merge($default, $formData);

?>

<script type="text/javascript">

    var init = function() {
        $('relist_mode').observe('change', EbayTemplateSynchronizationHandlerObj.relistMode_change);
        $('relist_qty_magento').observe('change', EbayTemplateSynchronizationHandlerObj.relistQty_change);
        $('relist_qty_calculated').observe('change', EbayTemplateSynchronizationHandlerObj.relistQty_change);
    };

    <?php if ($this->getRequest()->isXmlHttpRequest()): ?>
        init();
    <?php else: ?>
        Event.observe(window, 'load', init);
    <?php endif; ?>

</script>

<div id="block_notice_ebay_template_synchronization_form_data_relist" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Relist Rules'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'If <b>Relist Action</b> is enabled, M2E Pro will Relist Items on eBay if they meet the Conditions you set.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/QQAJAQ')
    ); ?>
</div>

<div class="entry-edit" id="magento_block_ebay_template_synchronization_form_data_relist_filters">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist Action'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_mode" name="synchronization[relist_mode]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_NONE; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_YES; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Choose whether you want to Relist Items covered by M2E Pro Listings using this Policy if the Relist Conditions are met.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_filter_user_lock_tr_container" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist When Stopped Manually'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_filter_user_lock" name="synchronization[relist_filter_user_lock]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Choose whether you want the Automatic Relist Rules to Relist Items even if they\'ve been Stopped manually.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_send_data_tr_container" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Synchronize Data'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_send_data" name="synchronization[relist_send_data]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_SEND_DATA_NONE; ?>" <?php if ($formData['relist_send_data'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_SEND_DATA_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_SEND_DATA_YES; ?>" <?php if ($formData['relist_send_data'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_SEND_DATA_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span>
                                <?php echo Mage::helper('M2ePro')->__(
                                    '<b>No:</b> Items are Relisted on eBay as per previously Listed Information and Settings, ignoring any changes that have been made on Magento.<br/>
                                    <b>Yes:</b> Any changes that have been made in Magento to Items that are being Relisted will be Reflected on the eBay Listing.'
                                ); ?>
                            </span>
                        </p>
                    </td>
                </tr>

           </table>

       </div>
   </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_synchronization_form_data_relist_rules" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Relist Conditions'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Product Status'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_status_enabled" name="synchronization[relist_status_enabled]" class="required-entry M2ePro-validate-stop-relist-conditions-product-status">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_STATUS_ENABLED_NONE; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_STATUS_ENABLED_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_STATUS_ENABLED_YES; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_STATUS_ENABLED_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                '<b>Enabled:</b> Relist Items automatically on eBay if they have a Magento Product status of enabled.
                                <b>Any:</b> Relist Items automatically on eBay with any Magento Product status.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stock Availability'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_is_in_stock" name="synchronization[relist_is_in_stock]" class="required-entry M2ePro-validate-stop-relist-conditions-stock-availability">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_IS_IN_STOCK_NONE; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_IS_IN_STOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_IS_IN_STOCK_YES; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_IS_IN_STOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('In Stock'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                '<b>In Stock:</b> Relist Items automatically if Products are in Stock.<br/>
                                <b>Any:</b> Relist Items automatically, regardless of Stock availability.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Magento Quantity'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_qty_magento" name="synchronization[relist_qty_magento]" class="required-entry M2ePro-validate-stop-relist-conditions-item-qty" qty_type="magento">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_LESS; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_MORE; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN; ?>" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                '<b>Any:</b> Relist Items automatically with any Quantity available.<br/>
                                <b>More or Equal: </b> Relist Items automatically if the Quantity available in Magento is at least equal to the number you set.<br/>
                                <b>Between:</b> Relist Items automatically if the Quantity available in Magento is between the minimum and maximum numbers you set.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_qty_magento_value_container" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_magento_value">
                            <span id="relist_qty_magento_item" <?php if ($formData['relist_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="relist_qty_magento_item_min" <?php if ($formData['relist_qty_magento'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_magento_value" name="synchronization[relist_qty_magento_value]" value="<?php echo $this->escapeHtml($formData['relist_qty_magento_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="relist_qty_magento_value_max_container" <?php if ($formData['relist_qty_magento'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_magento_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_magento_value_max" name="synchronization[relist_qty_magento_value_max]" value="<?php echo $this->escapeHtml($formData['relist_qty_magento_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Calculated Quantity'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_qty_calculated" name="synchronization[relist_qty_calculated]" class="required-entry M2ePro-validate-stop-relist-conditions-item-qty" qty_type="calculated">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_LESS; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_MORE; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN; ?>" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                    '<b>Any:</b> Relist Items automatically with any Quantity available.<br/>
                                    <b>More or Equal: </b> Relist Items automatically if the Quantity according to the Price, Quantity and Format Policy is at least equal to the number you set.<br/>
                                    <b>Between:</b> Relist Items automatically if the Quantity according to the Price, Quantity and Format Policy is between the minimum and maximum numbers you set.'
                                ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_qty_calculated_value_container" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_calculated_value">
                            <span id="relist_qty_calculated_item" <?php if ($formData['relist_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="relist_qty_calculated_item_min" <?php if ($formData['relist_qty_calculated'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_calculated_value" name="synchronization[relist_qty_calculated_value]" value="<?php echo $this->escapeHtml($formData['relist_qty_calculated_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="relist_qty_calculated_value_max_container" <?php if ($formData['relist_qty_calculated'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_calculated_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_calculated_value_max" name="synchronization[relist_qty_calculated_value_max]" value="<?php echo $this->escapeHtml($formData['relist_qty_calculated_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>