<?php
    /** @var Ess_M2ePro_Block_Adminhtml_Ebay_Template_Synchronization_Edit_Form_Tabs_Stop $this */

    $default = $this->getDefault();
    $formData = $this->getFormData();

    $formData = array_merge($default, $formData);

?>

<script type="text/javascript">

    var init = function() {
        $('stop_qty_magento').observe('change', EbayTemplateSynchronizationHandlerObj.stopQty_change);
        $('stop_qty_calculated').observe('change', EbayTemplateSynchronizationHandlerObj.stopQty_change);
    };

    <?php if ($this->getRequest()->isXmlHttpRequest()): ?>
        init();
    <?php else: ?>
        Event.observe(window, 'load', init);
    <?php endif; ?>

</script>

<div id="block_notice_ebay_template_synchronization_form_data_stop" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Stop Rules'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Set the Conditions when M2E Pro should stop Listings on eBay.<br/><br/>
        If all Conditions are set to No or No Action then no eBay Items using this Synchronization Policy will be Stopped.
        If all Options are enabled, then an Item will be Stopped if at least one of the Stop Conditions is met.<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/QgAJAQ')
    ); ?>
</div>

<div class="entry-edit" id="magento_block_ebay_template_synchronization_form_data_stop_rules">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Stop Conditions'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stop When Status Disabled'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="stop_status_disabled" name="synchronization[stop_status_disabled]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_STATUS_DISABLED_NONE; ?>" <?php if ($formData['stop_status_disabled'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_STATUS_DISABLED_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_OUT_OFF_STOCK_YES; ?>" <?php if ($formData['stop_status_disabled'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_STATUS_DISABLED_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically stops an Item that is on eBay if Status is changed to \'Disabled\' in Magento.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stop When Out Of Stock'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="stop_out_off_stock" name="synchronization[stop_out_off_stock]" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_OUT_OFF_STOCK_NONE; ?>" <?php if ($formData['stop_out_off_stock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_OUT_OFF_STOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_OUT_OFF_STOCK_YES; ?>" <?php if ($formData['stop_out_off_stock'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_OUT_OFF_STOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically stops an Item that is on eBay if Stock Availability is changed to \'Out of Stock\' in Magento.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stop When Magento Quantity Is'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="stop_qty_magento" name="synchronization[stop_qty_magento]" class="required-entry" qty_type="magento">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE; ?>" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_LESS; ?>" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less or Equal'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_MORE; ?>" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN; ?>" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically stops an Item on eBay if Magento Quantity is changed <b>and</b> it meets the selected Conditions.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="stop_qty_magento_value_container" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="stop_qty_magento_value">
                            <span id="stop_qty_magento_item" <?php if ($formData['stop_qty_magento'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="stop_qty_magento_item_min" <?php if ($formData['stop_qty_magento'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="stop_qty_magento_value" name="synchronization[stop_qty_magento_value]" value="<?php echo $this->escapeHtml($formData['stop_qty_magento_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="stop_qty_magento_value_max_container" <?php if ($formData['stop_qty_magento'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="stop_qty_magento_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="stop_qty_magento_value_max" name="synchronization[stop_qty_magento_value_max]" value="<?php echo $this->escapeHtml($formData['stop_qty_magento_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stop When Calculated Quantity Is'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="stop_qty_calculated" name="synchronization[stop_qty_calculated]" class="required-entry" qty_type="calculated">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE; ?>" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_LESS; ?>" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less or Equal'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_MORE; ?>" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN; ?>" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically stops an Item on eBay if calculated Quantity according to the Price, Quantity and Format Policy is changed <b>and</b> it meets the selected Conditions.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="stop_qty_calculated_value_container" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="stop_qty_calculated_value">
                            <span id="stop_qty_calculated_item" <?php if ($formData['stop_qty_calculated'] == Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: <span class="required">*</span></span>
                            <span id="stop_qty_calculated_item_min" <?php if ($formData['stop_qty_calculated'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="stop_qty_calculated_value" name="synchronization[stop_qty_calculated_value]" value="<?php echo $this->escapeHtml($formData['stop_qty_calculated_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="stop_qty_calculated_value_max_container" <?php if ($formData['stop_qty_calculated'] != Ess_M2ePro_Model_Ebay_Template_Synchronization::STOP_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="stop_qty_calculated_value_max"><?php echo Mage::helper('M2ePro')->__('Max Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="stop_qty_calculated_value_max" name="synchronization[stop_qty_calculated_value_max]" value="<?php echo $this->escapeHtml($formData['stop_qty_calculated_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits M2ePro-validate-conditions-between" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>