<div id="template_shippingOverride_pop_up_content">
    <div style="padding: 5px 0px;">

        <?php if(count($this->getMessages()) > 0) : ?>
            <div id="template_shippingOverride_error_block">
                <?php echo $this->getWarnings(); ?>
            </div>
        <?php endif; ?>

        <div id="block_notice_amazon_new_asin_description_policy_popup_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Assign Shipping Override Policy'); ?>">
            <?php echo Mage::helper('M2ePro')->__('The Shipping Override Policy is using to edit/change the Shipping
                Settings provided in Amazon Seller Central.<br/>
                You can select the Policy from the list of already created or add a new one for your Product by
                pressing <strong>Add New Shipping Override Policy</strong> Button.'); ?>
        </div>

        <div id="template_shippingOverride_grid" style="margin: 10px auto; height: 380px !important; overflow-y: auto; overflow-x: hidden;">
        </div>

    </div>
</div>