<div id="block_notice_ebay_listing_other" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows eBay Accounts and Sites that have 3rd Party Listings associated with them. (3rd Party Listings are eBay Listings that haven\'t been added by M2E Pro.)<br/><br/>
        Filter by Account and eBay Site and click a line to see the Listings.<br/><br/>
        To import 3rd Party Listings, <b>Import 3rd Party Listings</b> must be enabled for an eBay Account
        in (%menu_root_account%) and <b>3rd Party Listings Synchronization</b>
        must be enabled in (%menu_root_synchronization%).<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration', 'Accounts', '[eBay Account] > 3rd Party Listings Tab'),
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration', 'Synchronization'),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/HQAJAQ')
    ); ?>
</div>