<?php
/*
 * @author     M2E Pro Developers Team
 * @copyright  M2E LTD
 * @license    Commercial use is forbidden
 */

// @codingStandardsIgnoreFile

/** @var $this Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Other_Help */

?>

<div id="block_notice_ebay_listing_other" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Unmanaged Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows eBay Accounts and Marketplaces that have Unmanaged Listings associated with them. (Unmanaged Listings are eBay Listings that haven\'t been added by M2E Pro.)<br/><br/>
        Filter by Account and Marketplace and click a line to see the Listings.<br/><br/>
        To import Unmanaged Listings, <b>Import Unmanaged Listings</b> must be enabled for an eBay Account
        in (%menu_root_account%).<br/><br/>
        More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/View_Ebay')->getPageNavigationPath('configuration', 'Accounts', '[eBay Account] > Unmanaged Listings Tab'),
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(null, null, 'unmanaged-listing')
    ); ?>
</div>